# Generated by Django 6.0.5 on 2026-05-12 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_remove_ordonnance_consultation_and_more'),
        ('facturation', '0001_initial'),
        ('hospitalisation', '0001_initial'),
        ('medecins', '0006_categoriearticle_typearticle_unitemesure_and_more'),
        ('patients', '0001_initial'),
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeMedicaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom du groupe')),
                ('maladies', models.CharField(blank=True, max_length=500, verbose_name='Maladies')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin', verbose_name='Docteur')),
            ],
            options={
                'verbose_name': 'Groupe de médicaments',
                'verbose_name_plural': 'Groupes de médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('maladies', models.CharField(blank=True, max_length=500, verbose_name='Maladies')),
                ('date_ordonnance', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ordonnance")),
                ('avertissement_grossesse', models.BooleanField(default=False, verbose_name='Avertissement de grossesse')),
                ('type_ordonnance', models.CharField(choices=[('interne', 'Ordonnance interne'), ('externe', 'Ordonnance externe')], default='interne', max_length=20, verbose_name="Type d'ordonnance")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('prescrit', 'Prescrit')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name="Notes d'ordonnance")),
                ('cueillettes', models.CharField(blank=True, max_length=300, verbose_name='Cueillettes')),
                ('livre', models.BooleanField(default=False, verbose_name='Livré')),
                ('compagnie_assurance', models.CharField(blank=True, max_length=200, verbose_name="Compagnie d'assurance")),
                ('reclamation', models.CharField(blank=True, max_length=300, verbose_name='Réclamation')),
                ('ancienne_ordonnance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordonnances.ordonnance', verbose_name='Ancienne ordonnance')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='consultations.consultation', verbose_name='Consultation')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.facture', verbose_name='Facture')),
                ('groupe_medicaments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordonnances.groupemedicaments', verbose_name='Groupe de médicaments')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.hospitalisation', verbose_name='Hospitalisation')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='medecins.medecin', verbose_name='Docteur prescripteur')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='patients.patient', verbose_name='Patient')),
                ('police_assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.assurance', verbose_name="Police d'assurance")),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.rendezvous', verbose_name='Rendez-vous')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'ordering': ['-date_ordonnance'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_libre', models.CharField(blank=True, max_length=200, verbose_name='Médicament (saisie libre)')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantité')),
                ('unite_dosage', models.CharField(blank=True, max_length=100, verbose_name='Unité de dosage')),
                ('qte_par_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Qté par jour')),
                ('jours', models.IntegerField(blank=True, null=True, verbose_name='Jours')),
                ('commentaire', models.CharField(blank=True, max_length=500, verbose_name='Commentaire')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.medicament', verbose_name='Nom du médicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ordonnances.ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
            },
        ),
    ]
