# Generated by Django 6.0.5 on 2026-05-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0001_initial'),
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupemedicaments',
            name='limite',
            field=models.IntegerField(default=0, verbose_name='Limite'),
        ),
        migrations.CreateModel(
            name='LigneGroupeMedicaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_libre', models.CharField(blank=True, max_length=200, verbose_name='Médicament (libre)')),
                ('autorise', models.BooleanField(default=True, verbose_name='Autorisé')),
                ('frequence_posologique', models.CharField(blank=True, max_length=200, verbose_name='Fréquence posologique')),
                ('dosage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dosage')),
                ('unite_dosage', models.CharField(blank=True, max_length=100, verbose_name='Unité de dosage')),
                ('qte_par_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Qté par jour')),
                ('jours', models.IntegerField(blank=True, null=True, verbose_name='Jours')),
                ('commentaire', models.CharField(blank=True, max_length=500, verbose_name='Commentaire')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ordonnances.groupemedicaments', verbose_name='Groupe')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.medicament', verbose_name='Nom du médicament')),
            ],
            options={
                'verbose_name': 'Ligne de groupe de médicaments',
                'verbose_name_plural': 'Lignes de groupe de médicaments',
            },
        ),
    ]
