# Generated by Django 6.0.5 on 2026-05-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0002_groupemedicaments_limite_lignegroupemedicaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom de la maladie')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code CIM-10')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='groupemedicaments',
            name='maladies',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='maladies',
        ),
        migrations.AddField(
            model_name='groupemedicaments',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordonnances.maladie', verbose_name='Maladie'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordonnances.maladie', verbose_name='Maladie'),
        ),
    ]
