# Generated by Django 6.0.5 on 2026-05-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0002_remove_consultation_fk'),
        ('ordonnances', '0003_maladie_remove_groupemedicaments_maladies_and_more'),
    ]

    operations = [
    ]
