# Generated by Django 6.0.5 on 2026-05-28 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('medicament', 'Médicament'), ('consommable', 'Consommable médical'), ('equipement', 'Équipement & matériel')], default='medicament', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de stock',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyée'), ('partiel', 'Reçu partiellement'), ('recu', 'Reçu complet'), ('annule', 'Annulée')], default='brouillon', max_length=20)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_commandes', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande de stock',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LotProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_reception', models.DateField(default=django.utils.timezone.now)),
                ('prix_achat_lot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Lot',
                'ordering': ['date_peremption'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('medicament', 'Médicament'), ('consommable', 'Consommable médical'), ('equipement', 'Équipement & matériel')], default='medicament', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unite_mesure', models.CharField(default='unité', max_length=30)),
                ('dci', models.CharField(blank=True, max_length=200, verbose_name='DCI / Principe actif')),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('forme', models.CharField(blank=True, choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('creme', 'Crème'), ('pommade', 'Pommade'), ('gouttes', 'Gouttes'), ('suppositoire', 'Suppositoire'), ('autre', 'Autre')], max_length=20)),
                ('prescription_obligatoire', models.BooleanField(default=False)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_alerte', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('stock_minimum', models.DecimalField(decimal_places=2, default=5, max_digits=12)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categoriestock')),
                ('fournisseur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement inventaire'), ('peremption', 'Péremption'), ('retour', 'Retour fournisseur'), ('transfert', 'Transfert interne')], max_length=20)),
                ('motif', models.CharField(blank=True, choices=[('achat', 'Achat fournisseur'), ('dispensation', 'Dispensation patient'), ('hospitalisation', 'Hospitalisation'), ('urgence', 'Urgence'), ('inventaire', 'Inventaire'), ('perte', 'Perte / Casse'), ('don', 'Don / Subvention'), ('autre', 'Autre')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_avant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_apres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_mouvements', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.lotproduit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='lotproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stock.produit'),
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_recue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.commandestock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
            },
        ),
    ]
