# Generated by Django 6.0.5 on 2026-05-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_inventaire_ligneinventaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandestock',
            name='pharmacie',
            field=models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], default='wale_yamoussoukro', max_length=30),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='pharmacie',
            field=models.CharField(blank=True, choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(blank=True, choices=[('achat', 'Achat fournisseur'), ('livraison', 'Livraison à une pharmacie'), ('inventaire', 'Inventaire'), ('peremption', 'Péremption / Perte'), ('retour', 'Retour fournisseur'), ('don', 'Don / Subvention'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('entree', 'Entrée en stock'), ('livraison', 'Livraison pharmacie'), ('ajustement', 'Ajustement inventaire'), ('peremption', 'Péremption'), ('retour', 'Retour fournisseur')], max_length=20),
        ),
    ]
