# Generated by Django 6.0.5 on 2026-05-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_commandestock_pharmacie_mouvementstock_pharmacie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandestock',
            name='pharmacie',
        ),
    ]
