# Generated by Django 6.0.5 on 2026-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_demandepharmacie_lignedemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepharmacie',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_livraison', 'En livraison'), ('approuvee', 'Confirmée'), ('partielle', 'Confirmée partiellement'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
