# Generated by Django 6.0.5 on 2026-05-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_demandepharmacie_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='date_peremption',
            field=models.DateField(blank=True, null=True),
        ),
    ]
