# Generated by Django 6.0.5 on 2026-05-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_ligneinventaire_date_peremption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheBesoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('pharmacie', models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis pour validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('notes_direction', models.TextField(blank=True, verbose_name='Observations direction')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_besoins_creees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_besoins_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche de besoins',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneFicheBesoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qte_recue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qte_dispensee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cmm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qte_commander', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qte_accordee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.fichebesoins')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne fiche besoins',
                'ordering': ['produit__type', 'produit__nom'],
            },
        ),
    ]
