# Generated by Django 6.0.5 on 2026-06-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_copy_fournisseurs'),
        ('stock', '0009_fichebesoins_lignefichebesoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotproduit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandestock',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_stock', to='achats.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.fournisseur'),
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
