# Generated by Django 6.0.5 on 2026-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_lotproduit_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichebesoins',
            name='pharmacie',
            field=models.CharField(blank=True, choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], default='', max_length=30),
        ),
    ]
