# Generated by Django 6.0.5 on 2026-06-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_fiche_besoins_pharmacie_optional'),
    ]

    operations = [
        # 1. Créer la table UniteMesure
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Abréviation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['nom'],
            },
        ),
        # 2. Convertir unite_mesure de CharField en FK nullable
        #    (SQLite copiera le texte tel quel dans la colonne INTEGER)
        migrations.AlterField(
            model_name='produit',
            name='unite_mesure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.unitemesure', verbose_name='Unité de mesure'),
        ),
        # 3. Nettoyer les valeurs texte invalides avant que Django vérifie les FK
        #    typeof() retourne 'text' pour les anciennes valeurs VARCHAR copiées
        migrations.RunSQL(
            "UPDATE stock_produit SET unite_mesure_id = NULL WHERE typeof(unite_mesure_id) = 'text'",
            migrations.RunSQL.noop,
        ),
    ]
