# Generated by Django 6.0.5 on 2026-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_unitemesure_alter_produit_unite_mesure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitemesure',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Unité de mesure', 'verbose_name_plural': 'Unités de mesure'},
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Groupe / Catégorie'),
        ),
    ]
