# Generated by Django 5.1.6 on 2026-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_produit_unite_mesure_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(blank=True, choices=[('achat', 'Achat fournisseur'), ('livraison', 'Livraison à une pharmacie'), ('prescription', 'Ordonnance médicale'), ('inventaire', 'Inventaire'), ('peremption', 'Péremption / Perte'), ('retour', 'Retour fournisseur'), ('don', 'Don / Subvention'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('entree', 'Entrée en stock'), ('livraison', 'Livraison pharmacie'), ('prescription', 'Dispensation ordonnance'), ('ajustement', 'Ajustement inventaire'), ('peremption', 'Péremption'), ('retour', 'Retour fournisseur')], max_length=20),
        ),
    ]
