# Generated by Django 5.2.15 on 2026-07-22 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_produit_unite_mesure_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demandepharmacie',
            index=models.Index(fields=['pharmacie', 'statut'], name='stock_deman_pharmac_bf8835_idx'),
        ),
    ]
