# Generated by Django 6.0.5 on 2026-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_unitemesure_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitemesure',
            name='categorie',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Groupe / Catégorie'),
        ),
    ]
