# Generated by Django 5.2.15 on 2026-07-24 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_add_numero_lot_ligne_reception'),
        ('stock', '0014_demandepharmacie_stock_deman_pharmac_bf8835_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='modifie_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commandestock',
            index=models.Index(fields=['statut'], name='stock_comma_statut_73f9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='fichebesoins',
            index=models.Index(fields=['statut', 'pharmacie'], name='stock_fiche_statut_ea60c7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventaire',
            index=models.Index(fields=['statut'], name='stock_inven_statut_76a14f_idx'),
        ),
        migrations.AddIndex(
            model_name='lotproduit',
            index=models.Index(fields=['date_peremption', 'quantite_actuelle'], name='stock_lotpr_date_pe_e8b916_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type', 'date'], name='stock_mouve_type_e49c85_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['actif', 'type'], name='stock_produ_actif_f45dcc_idx'),
        ),
    ]
