# Generated by Django 5.2.15 on 2026-07-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_add_prescription_movement_type'),
        ('stock', '0015_modifie_par_et_index'),
    ]

    operations = [
    ]
