# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_merge_20260724_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['type', 'nom'], 'permissions': [('can_gerer_stock', 'Peut gérer le stock')], 'verbose_name': 'Produit'},
        ),
    ]
