# Generated by Django 5.1.6 on 2026-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_merge_20260724_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotproduit',
            name='conditionnement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
