# Generated by Django 5.1.6 on 2026-09-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_produit_options'),
        ('stock', '0017_lotproduit_conditionnement'),
    ]

    operations = [
    ]
