# Generated by Django 5.2.16 on 2026-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_merge_20260926_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitemesure',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='unitemesure',
            name='precision_arrondi',
        ),
        migrations.RemoveField(
            model_name='unitemesure',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='unitemesure',
            name='type_unite',
        ),
        migrations.DeleteModel(
            name='CategorieUniteMesure',
        ),
    ]
