# Generated by Django 5.1.6 on 2026-10-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_remove_unitemesure_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.lotproduit'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de lot'),
        ),
    ]
