# Generated by Django 6.0.5 on 2026-05-29 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_constante_new_fields'),
        ('pharmacie', '0001_initial'),
        ('stock', '0006_demandepharmacie_lignedemande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensationOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30)),
                ('statut', models.CharField(choices=[('complete', 'Complète'), ('partielle', 'Partielle')], default='complete', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('dispense_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to=settings.AUTH_USER_MODEL)),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation', to='consultations.ordonnance')),
            ],
            options={
                'verbose_name': 'Dispensation ordonnance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneDispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_libre', models.CharField(blank=True, max_length=200)),
                ('quantite_prescrite', models.IntegerField(default=1)),
                ('quantite_dispensee', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.dispensationordonnance')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne de dispensation',
            },
        ),
        migrations.CreateModel(
            name='MouvementPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30)),
                ('type', models.CharField(choices=[('entree', 'Entrée (dotation)'), ('dispensation', 'Dispensation ordonnance'), ('ajustement', 'Ajustement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_avant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_apres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_pharmacie', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_pharmacie', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Mouvement pharmacie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_pharmacie', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Stock pharmacie',
                'ordering': ['pharmacie', 'produit__nom'],
                'unique_together': {('pharmacie', 'produit')},
            },
        ),
    ]
