# Generated by Django 6.0.5 on 2026-05-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_constante_new_fields'),
        ('patients', '0016_merge_20260528_2008'),
        ('pharmacie', '0002_dispensationordonnance_lignedispensation_and_more'),
        ('stock', '0009_fichebesoins_lignefichebesoins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementpharmacie',
            name='type',
            field=models.CharField(choices=[('entree', 'Entrée (dotation)'), ('dispensation', 'Dispensation ordonnance'), ('vente', 'Vente caisse'), ('ajustement', 'Ajustement')], max_length=20),
        ),
        migrations.CreateModel(
            name='VentePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('assurance', 'Assurance')], default='especes', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('annulee', 'Annulée')], default='payee', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_pharmacie', to=settings.AUTH_USER_MODEL)),
                ('ordonnance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_pharmacie', to='consultations.ordonnance')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_pharmacie', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Vente pharmacie',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.ventepharmacie')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
            },
        ),
    ]
