# Generated by Django 6.0.5 on 2026-05-30 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_alter_mouvementpharmacie_type_ventepharmacie_and_more'),
        ('stock', '0009_fichebesoins_lignefichebesoins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementpharmacie',
            name='type',
            field=models.CharField(choices=[('entree', 'Entrée (dotation)'), ('dispensation', 'Dispensation ordonnance'), ('vente', 'Vente caisse'), ('retour', 'Retour produit'), ('ajustement', 'Ajustement')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventairePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(choices=[('wale_toumbokro', 'Walé Toumbokro'), ('wale_yamoussoukro', 'Walé Yamoussoukro')], max_length=30)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_inventaire', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_pharmacie', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_pharmacie_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire pharmacie',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventairePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.inventairepharmacie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne inventaire pharmacie',
            },
        ),
    ]
