# Generated by Django 6.0.5 on 2026-06-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('pharmacie', '0004_alter_mouvementpharmacie_type_inventairepharmacie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotmedicament',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandepharmacies',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.fournisseur'),
        ),
    ]
