# Generated by Django 6.0.5 on 2026-06-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_alter_lotmedicament_fournisseur_and_more'),
        ('services', '0009_alter_lignefournisseurarticle_fournisseur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
