# Generated by Django 5.2.15 on 2026-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0006_delete_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedispensation',
            name='achete_ailleurs',
            field=models.BooleanField(default=False, help_text='Le patient a obtenu ce médicament dans une autre pharmacie'),
        ),
    ]
