# Generated by Django 5.2.15 on 2026-07-22 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_ordonnance_medecin'),
        ('patients', '0023_alter_rendezvous_cpn_type_visite_and_more'),
        ('pharmacie', '0007_lignedispensation_achete_ailleurs'),
        ('stock', '0014_demandepharmacie_stock_deman_pharmac_bf8835_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispensationordonnance',
            index=models.Index(fields=['pharmacie', '-date'], name='pharmacie_d_pharmac_e8b169_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairepharmacie',
            index=models.Index(fields=['pharmacie', 'statut'], name='pharmacie_i_pharmac_f402d1_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementpharmacie',
            index=models.Index(fields=['pharmacie', '-date'], name='pharmacie_m_pharmac_15434f_idx'),
        ),
        migrations.AddIndex(
            model_name='ventepharmacie',
            index=models.Index(fields=['pharmacie', 'date_vente'], name='pharmacie_v_pharmac_bba915_idx'),
        ),
    ]
