# Generated by Django 5.1.6 on 2026-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0008_dispensationordonnance_pharmacie_d_pharmac_e8b169_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaciePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('gerer_stock_pharmacie', "Peut gérer le stock d'une pharmacie (dispensation, dotation, inventaire, retours, livraisons)"), ('valider_vente_pharmacie', 'Peut valider ou annuler une vente en pharmacie'), ('voir_rapport_financier_pharmacie', "Peut voir les rapports financiers de la pharmacie (recettes, chiffre d'affaires)")],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
