# Generated by Django 5.2.16 on 2026-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_pharmaciepermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementpharmacie',
            name='type',
            field=models.CharField(choices=[('initial', 'Stock initial'), ('entree', 'Entrée (dotation)'), ('dispensation', 'Dispensation ordonnance'), ('vente', 'Vente caisse'), ('retour', 'Retour produit'), ('ajustement', 'Ajustement')], max_length=20),
        ),
    ]
