# Generated by Django 6.0.7 on 2026-09-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_remove_ligneordonnance_medicament'),
        ('facturation', '0021_remove_lignefacture_medicament'),
        ('pharmacie', '0010_alter_mouvementpharmacie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='lotmedicament',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='lotmedicament',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='cree_par',
        ),
        migrations.DeleteModel(
            name='CategorieMedicament',
        ),
        migrations.DeleteModel(
            name='LotMedicament',
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
        migrations.DeleteModel(
            name='MouvementStock',
        ),
    ]
