"""Retire `CommandePharmacies`, dernier morceau de la chaîne d'origine.

24 en-têtes de commande fournisseur, d'avril à août 2026, pour 41 855 587 F —
et aucune ligne de détail : rien ne pointait vers ce modèle, aucun écran ne
l'ouvrait, aucune permission n'était attribuée. Le module `achats` tient ce rôle
depuis. Les 24 lignes ont été exportées en CSV avant la suppression.

La migration retire aussi le ContentType et les quatre permissions laissés
derrière, comme 0012 l'a fait pour les autres.
"""

# Generated by Django 6.0.7 on 2026-09-25 10:37

from django.db import migrations


def nettoyer(apps, schema_editor):
    """ContentType et permissions du modèle supprimé."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    types = ContentType.objects.filter(
        app_label='pharmacie', model='commandepharmacies')
    Permission.objects.filter(content_type__in=types).delete()
    types.delete()


def ne_rien_faire(apps, schema_editor):
    """Django recrée ces lignes si le modèle revient."""


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0012_nettoyage_ancienne_chaine'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandePharmacies',
        ),
        migrations.RunPython(nettoyer, ne_rien_faire),
    ]
