# Generated by Django 6.0.7 on 2026-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0013_delete_commandepharmacies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementpharmacie',
            name='type',
            field=models.CharField(choices=[('initial', 'Stock initial'), ('entree', 'Entrée (dotation)'), ('dispensation', 'Dispensation ordonnance'), ('vente', 'Vente caisse'), ('facture', 'Facture encaissée'), ('retour', 'Retour produit'), ('ajustement', 'Ajustement')], max_length=20),
        ),
    ]
