# Generated by Django 6.0.5 on 2026-05-28 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0002_initial'),
        ('facturation', '0001_initial'),
        ('laboratoire', '0001_initial'),
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code_cim', models.CharField(blank=True, max_length=20, verbose_name='Code CIM-10')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('lab_groupe', models.CharField(blank=True, max_length=200, verbose_name='Lab Groupe')),
                ('est_demande_groupe', models.BooleanField(default=False, verbose_name='Est une demande de groupe')),
                ('type_test', models.CharField(blank=True, choices=[('pathologie', 'Pathologie'), ('biologie', 'Biologie'), ('microbiologie', 'Microbiologie'), ('hematologie', 'Hématologie'), ('biochimie', 'Biochimie'), ('immunologie', 'Immunologie'), ('autre', 'Autre')], max_length=50, verbose_name='Type du test')),
                ('centre_collecte', models.CharField(blank=True, max_length=200, verbose_name='Centre de collecte')),
                ('envoyer_autre_lab', models.BooleanField(default=False, verbose_name='Envoyer à un autre lab')),
                ('sampler', models.CharField(blank=True, max_length=200, verbose_name='Sampler')),
                ('date_actes', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure des actes (prélèvement)')),
                ('echantillon_du_test', models.BooleanField(default=False, verbose_name='Échantillon du test')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('demande', 'Demandé'), ('accepte', 'Accepté'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('raison_refus', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('type_segment', models.CharField(blank=True, default='H', max_length=10, verbose_name='Type de segment')),
                ('nom_fichier', models.CharField(blank=True, default='WAL001.HPR', max_length=100, verbose_name='Nom du fichier')),
                ('code_emetteur', models.CharField(blank=True, default='001', max_length=50, verbose_name='Code émetteur')),
                ('nom_emetteur', models.CharField(blank=True, max_length=200, verbose_name='Nom émetteur')),
                ('code_recepteur', models.CharField(blank=True, default='002', max_length=50, verbose_name='Code récepteur')),
                ('nom_recepteur', models.CharField(blank=True, default='CMSWALE.0000', max_length=200, verbose_name='Nom récepteur')),
                ('identifiant_recepteur', models.CharField(blank=True, default='WALE.SYSLAM', max_length=200, verbose_name='Identifiant récepteur')),
                ('type_message', models.CharField(blank=True, default='DRA', max_length=10, verbose_name='Type de message')),
                ('mode_traitement', models.CharField(blank=True, default='P', max_length=10, verbose_name='Mode de traitement')),
                ('version_type', models.CharField(blank=True, default='H2.4', max_length=10, verbose_name='Version et type')),
                ('type_liaison', models.CharField(blank=True, default='L', max_length=10, verbose_name='Type de liaison')),
                ('liste_prix', models.CharField(blank=True, max_length=100, verbose_name='Liste de prix')),
                ('type_segment_patient', models.CharField(blank=True, default='P', max_length=10, verbose_name='Type de segment patient')),
                ('rang_segment_patient', models.CharField(blank=True, default='D', max_length=10, verbose_name='Rang du segment patient')),
                ('type_code', models.CharField(blank=True, default='L', max_length=10, verbose_name='Type de code')),
                ('priorite', models.CharField(blank=True, default='C', max_length=10, verbose_name='Priorité')),
                ('code_action', models.CharField(blank=True, default='N', max_length=10, verbose_name='Code action')),
                ('date_heure_resultats', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure des résultats')),
                ('statuts_resultats', models.CharField(blank=True, default='F', max_length=10, verbose_name='Statuts des résultats')),
                ('couts_transport', models.CharField(blank=True, default='WALK', max_length=100, verbose_name='Coûts transport')),
                ('type_segment_qbr', models.CharField(blank=True, default='QBR', max_length=10, verbose_name='Type de segment QBR')),
                ('type_segment_l', models.CharField(blank=True, default='L', max_length=10, verbose_name='Type de segment L')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin_prescripteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examen_prescrites', to='employer.employe', verbose_name='Docteur prescripteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_examen', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examen', to='patients.rendezvous', verbose_name='Rendez-vous')),
            ],
            options={
                'verbose_name': "Demande d'examen",
                'verbose_name_plural': "Demandes d'examen",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_execution', models.CharField(blank=True, max_length=100, verbose_name="Délai d'exécution")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de vente')),
                ('instructions_speciales', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='soins.demandeexamen', verbose_name='Demande')),
                ('type_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeexamen', verbose_name='Test')),
            ],
            options={
                'verbose_name': "Ligne de demande d'examen",
                'verbose_name_plural': "Lignes de demande d'examen",
            },
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('motif', models.CharField(blank=True, max_length=500, verbose_name='Motif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_de_paiement', 'Paiement en attente'), ('en_cours', 'Soins en cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=25, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='soins/photos/', verbose_name='Photo')),
                ('statut_maladie', models.CharField(blank=True, choices=[('', '—'), ('aigu', 'Aigu'), ('chronique', 'Chronique'), ('inchange', 'Inchangé'), ('gueri', 'Guéri'), ('ameliorant', 'Améliorant'), ('aggravant', 'Aggravant')], max_length=20, verbose_name='Statut de la maladie')),
                ('severite', models.CharField(blank=True, choices=[('', '—'), ('moderee', 'Modérée'), ('severe', 'Sévère')], max_length=20, verbose_name='Sévérité')),
                ('date_guerison', models.DateField(blank=True, null=True, verbose_name='Date de guérison')),
                ('maladie_infectieuse', models.BooleanField(default=False, verbose_name='Maladie infectieuse')),
                ('maladie_allergique', models.BooleanField(default=False, verbose_name='Maladie allergique')),
                ('lactation', models.BooleanField(default=False, verbose_name='Lactation')),
                ('avertissement_grossesse', models.BooleanField(default=False, verbose_name='Avertissement de grossesse')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='employer.departement', verbose_name='Département')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='facturation.facture', verbose_name='Facture')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_effectues', to='employer.employe', verbose_name='Infirmier/Agent de soins')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='patients.rendezvous', verbose_name='Rendez-vous')),
                ('service_inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_inscrits', to='services.articleservice', verbose_name="Service d'inscription")),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ['-date_heure'],
                'permissions': [('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'Soins en cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='État')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='employer.departement', verbose_name='Département')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='facturation.facture', verbose_name='Facture')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_effectuees', to='employer.employe', verbose_name='Infirmier')),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soins.maladie', verbose_name='Maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures_soins', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='patients.rendezvous', verbose_name='Rendez-vous')),
                ('soin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='services.articleservice', verbose_name='Soin')),
                ('soin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='soins.soin', verbose_name='Soin infirmier')),
            ],
            options={
                'verbose_name': 'Procédure de soin',
                'verbose_name_plural': 'Liste des soins',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examen', to='soins.soin', verbose_name='Soin'),
        ),
    ]
