# Generated by Django 6.0.5 on 2026-05-28 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0019_fonction_categorie_data'),
        ('facturation', '0001_initial'),
        ('medecins', '0005_departement'),
        ('patients', '0009_add_cpn5plus_choice'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code_cim', models.CharField(blank=True, max_length=20, verbose_name='Code CIM-10')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('motif', models.CharField(blank=True, max_length=500, verbose_name='Motif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_de_paiement', 'En attente de paiement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=25, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='soins/photos/', verbose_name='Photo')),
                ('statut_maladie', models.CharField(blank=True, choices=[('', '—'), ('aigu', 'Aigu'), ('chronique', 'Chronique'), ('inchange', 'Inchangé'), ('gueri', 'Guéri'), ('ameliorant', 'Améliorant'), ('aggravant', 'Aggravant')], max_length=20, verbose_name='Statut de la maladie')),
                ('severite', models.CharField(blank=True, choices=[('', '—'), ('moderee', 'Modérée'), ('severe', 'Sévère')], max_length=20, verbose_name='Sévérité')),
                ('date_guerison', models.DateField(blank=True, null=True, verbose_name='Date de guérison')),
                ('maladie_infectieuse', models.BooleanField(default=False, verbose_name='Maladie infectieuse')),
                ('maladie_allergique', models.BooleanField(default=False, verbose_name='Maladie allergique')),
                ('lactation', models.BooleanField(default=False, verbose_name='Lactation')),
                ('avertissement_grossesse', models.BooleanField(default=False, verbose_name='Avertissement de grossesse')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='medecins.departement', verbose_name='Département')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='facturation.facture', verbose_name='Facture')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_effectues', to='employer.employe', verbose_name='Infirmier/Agent de soins')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='patients.rendezvous', verbose_name='Rendez-vous')),
                ('service_inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_inscrits', to='services.articleservice', verbose_name="Service d'inscription")),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ['-date_heure'],
                'permissions': [('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='État')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='medecins.departement', verbose_name='Département')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='facturation.facture', verbose_name='Facture')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_effectuees', to='employer.employe', verbose_name='Infirmier')),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soins.maladie', verbose_name='Maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures_soins', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='patients.rendezvous', verbose_name='Rendez-vous')),
                ('soin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='services.articleservice', verbose_name='Soin')),
                ('soin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='soins.soin', verbose_name='Soin infirmier')),
            ],
            options={
                'verbose_name': 'Procédure de soin',
                'verbose_name_plural': 'Liste des soins',
                'ordering': ['-date'],
            },
        ),
    ]
