# Generated by Django 6.0.5 on 2026-05-17 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0003_add_nationalite_to_employe'),
        ('patients', '0003_patient_medecin_referent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('motif', models.CharField(blank=True, max_length=500, verbose_name='Motif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_effectues', to='employe.employe', verbose_name='Infirmier/Agent de soins')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='patients.rendezvous', verbose_name='Rendez-vous')),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ['-date_heure'],
            },
        ),
    ]
