# Generated by Django 6.0.5 on 2026-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='avertissement_grossesse',
            field=models.BooleanField(default=False, verbose_name='Avertissement de grossesse'),
        ),
        migrations.AddField(
            model_name='soin',
            name='date_guerison',
            field=models.DateField(blank=True, null=True, verbose_name='Date de guérison'),
        ),
        migrations.AddField(
            model_name='soin',
            name='departement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='soin',
            name='lactation',
            field=models.BooleanField(default=False, verbose_name='Lactation'),
        ),
        migrations.AddField(
            model_name='soin',
            name='maladie_allergique',
            field=models.BooleanField(default=False, verbose_name='Maladie allergique'),
        ),
        migrations.AddField(
            model_name='soin',
            name='maladie_infectieuse',
            field=models.BooleanField(default=False, verbose_name='Maladie infectieuse'),
        ),
        migrations.AddField(
            model_name='soin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='soins/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='soin',
            name='service_inscription',
            field=models.CharField(blank=True, max_length=200, verbose_name="Service d'inscription"),
        ),
        migrations.AddField(
            model_name='soin',
            name='severite',
            field=models.CharField(blank=True, choices=[('', '—'), ('legere', 'Légère'), ('moderee', 'Modérée'), ('severe', 'Sévère'), ('critique', 'Critique')], max_length=20, verbose_name='Sévérité'),
        ),
        migrations.AddField(
            model_name='soin',
            name='statut_maladie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Statut de la maladie'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('courant', 'Courant'), ('complete', 'Complété'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
    ]
