# Generated by Django 6.0.5 on 2026-05-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soin',
            options={'ordering': ['-date_heure'], 'permissions': [('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')], 'verbose_name': 'Soin', 'verbose_name_plural': 'Soins'},
        ),
        migrations.AddField(
            model_name='soin',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_de_paiement', 'En attente de paiement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=25, verbose_name='Statut'),
        ),
    ]
