# Generated by Django 6.0.5 on 2026-05-18 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_add_nationalite_to_employe'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
        ('soins', '0002_soin_avertissement_grossesse_soin_date_guerison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='employe.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='service_inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_inscrits', to='services.articleservice', verbose_name="Service d'inscription"),
        ),
    ]
