# Generated by Django 6.0.5 on 2026-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_departement_diplome_etiquette_specialite_and_more'),
        ('soins', '0002_alter_soin_options_soin_facture_alter_soin_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduresoin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='employer.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='proceduresoin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_effectuees', to='employer.employe', verbose_name='Infirmier'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='employer.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_effectues', to='employer.employe', verbose_name='Infirmier/Agent de soins'),
        ),
    ]
