# Generated by Django 6.0.5 on 2026-05-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0002_alter_soin_options_soin_facture_alter_soin_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soin',
            options={'ordering': ['-date_creation'], 'permissions': [('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')], 'verbose_name': 'Soin', 'verbose_name_plural': 'Soins'},
        ),
        migrations.RemoveField(
            model_name='soin',
            name='date_heure',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='infirmier',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='rendez_vous',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='service_inscription',
        ),
    ]
