# Generated by Django 6.0.5 on 2026-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0003_alter_soin_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Programmé'), ('courant', 'Courant'), ('complete', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
    ]
