# Generated by Django 6.0.5 on 2026-05-29 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('soins', '0003_remove_soin_numero_infirmier_rendez_vous_date_heure_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure'),
        ),
        migrations.AddField(
            model_name='soin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_pris_en_charge', to='employer.employe', verbose_name='Infirmier responsable'),
        ),
        migrations.AddField(
            model_name='soin',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Numéro'),
        ),
    ]
