# Generated by Django 6.0.5 on 2026-05-18 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_add_nationalite_to_employe'),
        ('facturation', '0002_remove_consultation_fk'),
        ('patients', '0003_patient_medecin_referent'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
        ('soins', '0004_add_nom_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('courant', 'Courant'), ('complete', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='ProcedureSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('maladie', models.CharField(blank=True, max_length=300, verbose_name='Maladie')),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('courant', 'Courant'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='programme', max_length=20, verbose_name='État')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='employe.departement', verbose_name='Département')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='facturation.facture', verbose_name='Facture')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_effectuees', to='employe.employe', verbose_name='Infirmier')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures_soins', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='patients.rendezvous', verbose_name='Rendez-vous')),
                ('soin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='services.articleservice', verbose_name='Soin')),
            ],
            options={
                'verbose_name': 'Procédure de soin',
                'verbose_name_plural': 'Liste des soins',
                'ordering': ['-date'],
            },
        ),
    ]
