# Generated by Django 6.0.5 on 2026-05-29 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_add_registres_cpn_accouchement_postnatale_curatif'),
        ('soins', '0004_soin_numero_infirmier_date_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduresoin',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.pathologie', verbose_name='Maladie'),
        ),
    ]
