# Generated by Django 6.0.5 on 2026-05-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0005_maladie_fk_to_pathologie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maladie',
        ),
    ]
