# Generated by Django 6.0.5 on 2026-05-30 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0006_drop_maladie_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresoin',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='proceduresoin',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='proceduresoin',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
