# Generated by Django 6.0.5 on 2026-05-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0006_add_maladie'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresoin',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='soins.soin', verbose_name='Soin infirmier'),
        ),
    ]
