# Generated by Django 6.0.5 on 2026-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0007_add_soin_fk_to_proceduresoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduresoin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('courant', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('courant', 'En cours'), ('complete', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
    ]
