# Generated by Django 6.0.5 on 2026-06-02 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0017_update_visites_saf_articleservice'),
        ('soins', '0008_add_audit_fields_to_soin'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_lies', to='hospitalisation.hospitalisation', verbose_name='Hospitalisation liée'),
        ),
    ]
