# Generated by Django 6.0.5 on 2026-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0009_rename_statut_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduresoin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='statut_maladie',
            field=models.CharField(blank=True, choices=[('', '—'), ('aigu', 'Aigu'), ('chronique', 'Chronique'), ('inchange', 'Inchangé'), ('gueri', 'Guéri'), ('ameliorant', 'Améliorant'), ('aggravant', 'Aggravant')], max_length=20, verbose_name='Statut de la maladie'),
        ),
    ]
