# Generated by Django 6.0.5 on 2026-06-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_employe_biometric_id_alter_conge_statut'),
        ('patients', '0017_merge_0016'),
        ('services', '0009_alter_lignefournisseurarticle_fournisseur'),
        ('soins', '0009_add_hospitalisation_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code_cim', models.CharField(blank=True, max_length=20, verbose_name='Code CIM-10')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='soin',
            options={'ordering': ['-date_heure'], 'permissions': [('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')], 'verbose_name': 'Soin', 'verbose_name_plural': 'Soins'},
        ),
        migrations.RemoveField(
            model_name='proceduresoin',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='proceduresoin',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='proceduresoin',
            name='modifie_par',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='date_termine',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='hospitalisation',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='modifie_par',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='termine_par',
        ),
        migrations.AddField(
            model_name='soin',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='patients.rendezvous', verbose_name='Rendez-vous'),
        ),
        migrations.AddField(
            model_name='soin',
            name='service_inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_inscrits', to='services.articleservice', verbose_name="Service d'inscription"),
        ),
        migrations.AlterField(
            model_name='soin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_effectues', to='employer.employe', verbose_name='Infirmier/Agent de soins'),
        ),
        migrations.AlterField(
            model_name='soin',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='proceduresoin',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soins.maladie', verbose_name='Maladie'),
        ),
    ]
