# Generated by Django 6.0.6 on 2026-07-09 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0012_modulespecialise'),
        ('soins', '0009_add_hospitalisation_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduresoin',
            name='departement',
        ),
        migrations.AddField(
            model_name='proceduresoin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_soins', to='medecins.departement', verbose_name='Département'),
        ),
        migrations.RemoveField(
            model_name='soin',
            name='departement',
        ),
        migrations.AddField(
            model_name='soin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='medecins.departement', verbose_name='Département'),
        ),
    ]
