# Generated by Django 6.0.6 on 2026-08-22 18:23

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_creer_centres_initiaux'),
        ('soins', '0010_alter_proceduresoin_departement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduresoin',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date'], 'verbose_name': 'Procédure de soin', 'verbose_name_plural': 'Liste des soins'},
        ),
        migrations.AlterModelOptions(
            name='soin',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_creation'], 'permissions': [('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')], 'verbose_name': 'Soin', 'verbose_name_plural': 'Soins'},
        ),
        migrations.AlterModelManagers(
            name='proceduresoin',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='soin',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='proceduresoin',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='soin',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
