# Generated by Django 6.0.5 on 2026-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0010_statut_maladie_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='severite',
            field=models.CharField(blank=True, choices=[('', '—'), ('moderee', 'Modérée'), ('severe', 'Sévère')], max_length=20, verbose_name='Sévérité'),
        ),
    ]
