# Generated by Django 6.0.7 on 2026-09-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0011_alter_proceduresoin_options_alter_soin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduresoin',
            options={'base_manager_name': 'all_objects', 'default_permissions': (), 'ordering': ['-date'], 'permissions': [('view_proceduresoin', 'Peut consulter les procédures de soin'), ('add_proceduresoin', 'Peut créer une procédure de soin'), ('change_proceduresoin', 'Peut modifier une procédure de soin'), ('delete_proceduresoin', 'Peut supprimer une procédure de soin')], 'verbose_name': 'Procédure de soin', 'verbose_name_plural': 'Liste des soins'},
        ),
        migrations.AlterModelOptions(
            name='soin',
            options={'base_manager_name': 'all_objects', 'default_permissions': (), 'ordering': ['-date_creation'], 'permissions': [('view_soin', 'Peut consulter les soins'), ('add_soin', 'Peut créer un soin'), ('change_soin', 'Peut modifier un soin'), ('delete_soin', 'Peut supprimer un soin'), ('can_creer_facture', 'Peut créer une facture de soin'), ('can_administrer_soin', 'Peut administrer un soin')], 'verbose_name': 'Soin', 'verbose_name_plural': 'Soins'},
        ),
    ]
