# Generated by Django 5.2.15 on 2026-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_couleurs_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(blank=True, help_text="Couleur d'accent personnalisée (hex, ex: #3e6f3e). Vide = couleur par défaut du logo.", max_length=7, null=True),
        ),
    ]
