# Generated by Django 5.2.15 on 2026-07-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Délai d'inactivité avant déconnexion automatique, en minutes. 0 = désactivé."),
        ),
    ]
