# Generated by Django 5.1.6 on 2026-08-03 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
        ('core', '0005_userprofile_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='centre_actif',
            field=models.ForeignKey(blank=True, help_text="Centre actuellement sélectionné par l'utilisateur.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_actifs', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='centres',
            field=models.ManyToManyField(blank=True, help_text="Centres auxquels cet utilisateur a accès. Le personnel fixe n'en a qu'un ; un médecin intervenant dans plusieurs centres peut en avoir plusieurs.", related_name='profils', to='centres.centre'),
        ),
    ]
