# Generated by Django 5.2.16 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_userprofile_centres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactivite',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('statut', 'Changement de statut'), ('modif', 'Modification'), ('system', 'Système'), ('suppression', 'Suppression'), ('connexion', 'Connexion')], default='note', max_length=12),
        ),
    ]
