# Generated by Django 6.0.7 on 2026-09-21 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_userprofile_centres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='luminosite',
            field=models.PositiveSmallIntegerField(default=100, help_text="Luminosité de l'interface, en pourcentage (70 à 100). 100 = aucun assombrissement, rendu d'origine. Les validateurs sont le seul rempart contre une valeur saisie ici qui rendrait l'interface illisible pour l'utilisateur, sans issue de son côté.", validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
