# Generated by Django 5.2.16 on 2026-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_logactivite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivite',
            name='duree_secondes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (secondes)'),
        ),
        migrations.AddField(
            model_name='logactivite',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
    ]
