# Generated by Django 5.2.16 on 2026-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_logactivite_duree_secondes_logactivite_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivite',
            name='module',
            field=models.CharField(blank=True, help_text="Nom de l'app Django concernée — indépendant de l'objet lié, nécessaire pour les événements sans objet précis (consultation d'une page, connexion).", max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='logactivite',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('statut', 'Changement de statut'), ('modif', 'Modification'), ('system', 'Système'), ('suppression', 'Suppression'), ('connexion', 'Connexion'), ('consultation', 'Consultation')], default='note', max_length=12),
        ),
    ]
