# Generated by Django 6.0.7 on 2026-09-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_luminosite'),
        ('core', '0011_backfill_logactivite_module'),
    ]

    operations = [
    ]
