# Generated by Django 6.0.7 on 2026-10-09 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260922_1020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('echec', 'Échec')], default='en_cours', max_length=10)),
                ('etape', models.CharField(blank=True, help_text='Phase en cours : lecture du fichier, enregistrement…', max_length=100)),
                ('total', models.PositiveIntegerField(default=0, help_text="0 tant que le fichier n'est pas lu.")),
                ('traites', models.PositiveIntegerField(default=0)),
                ('crees', models.PositiveIntegerField(default=0)),
                ('mis_a_jour', models.PositiveIntegerField(default=0)),
                ('ignores', models.PositiveIntegerField(default=0)),
                ('erreurs', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tâche d'import",
                'verbose_name_plural': "Tâches d'import",
                'ordering': ['-date_debut'],
            },
        ),
    ]
