# Generated by Django 5.2.16 on 2026-08-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('icone', models.CharField(default='bi-book-half', help_text="Classe d'icône Bootstrap Icons (ex: bi-people-fill)", max_length=50, verbose_name='Icône')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie de guide',
                'verbose_name_plural': 'Catégories de guide',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(help_text='Texte explicatif. Une ligne vide sépare les paragraphes.', verbose_name='Contenu')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='guide.guidecategorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article de guide',
                'verbose_name_plural': 'Articles de guide',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
