# Generated by Django 5.2.16 on 2026-08-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_contenu_de_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidearticle',
            name='icone',
            field=models.CharField(default='bi-info-circle-fill', help_text="Classe d'icône Bootstrap Icons (ex: bi-list-check)", max_length=50, verbose_name='Icône'),
        ),
    ]
