# Generated by Django 5.2.16 on 2026-08-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_contenu_detaille'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidecategorie',
            options={'ordering': ['groupe_ordre', 'ordre', 'nom'], 'verbose_name': 'Catégorie de guide', 'verbose_name_plural': 'Catégories de guide'},
        ),
        migrations.AddField(
            model_name='guidecategorie',
            name='groupe',
            field=models.CharField(blank=True, help_text='Section du sommaire regroupant plusieurs catégories proches (ex: Ressources humaines)', max_length=100, verbose_name='Groupe'),
        ),
        migrations.AddField(
            model_name='guidecategorie',
            name='groupe_ordre',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre du groupe'),
        ),
    ]
