# Generated by Django 6.0.5 on 2026-06-09 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0009_fichebesoins_lignefichebesoins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=30, verbose_name='Tél. contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email contact')),
                ('specialites', models.TextField(blank=True, verbose_name='Types de produits fournis')),
                ('conditions_paiement', models.CharField(blank=True, max_length=200)),
                ('delai_livraison_moyen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai livraison moyen (j)')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BesoinAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('date_besoin_souhaite', models.DateField(blank=True, null=True, verbose_name='Date de livraison souhaitée')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_cours', 'En cours de traitement'), ('satisfait', 'Satisfait'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_achats_crees', to=settings.AUTH_USER_MODEL)),
                ('fiche_besoins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_achats', to='stock.fichebesoins', verbose_name='Fiche de besoins liée')),
            ],
            options={
                'verbose_name': "Besoin d'achat",
                'verbose_name_plural': "Besoins d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('en_livraison', 'En livraison'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_achats_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_achats', to='achats.fournisseur')),
            ],
            options={
                'verbose_name': "Commande d'achat",
                'verbose_name_plural': "Commandes d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=250, verbose_name='Désignation libre')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(default='unité', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.besoinachat')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne de besoin',
            },
        ),
        migrations.CreateModel(
            name='LigneProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('ligne_besoin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_proforma', to='achats.lignebesoin')),
            ],
            options={
                'verbose_name': 'Ligne de proforma',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('quantite_commandee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandeachat')),
                ('ligne_proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.ligneproforma')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_reception', models.DateField(verbose_name='Date de réception du document')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Réf. fournisseur')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='achats/proformas/', verbose_name='Document proforma')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('notes_direction', models.TextField(blank=True, verbose_name='Observations direction')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='achats.besoinachat')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='achats.fournisseur')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_soumis', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proforma',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='ligneproforma',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.proforma'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='proforma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commande', to='achats.proforma'),
        ),
        migrations.CreateModel(
            name='ReceptionAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_reception', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('partielle', 'Partielle'), ('non_conforme', 'Non conforme')], default='conforme', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='achats.commandeachat')),
                ('receptionne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Réception d'achat",
                'verbose_name_plural': "Réceptions d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneReceptionAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conforme', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achats.lignecommandeachat')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.receptionachat')),
            ],
            options={
                'verbose_name': 'Ligne de réception',
            },
        ),
    ]
