# Generated by Django 6.0.5 on 2026-06-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_copy_fournisseurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionachat',
            name='date_integration',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'intégration stock"),
        ),
        migrations.AddField(
            model_name='receptionachat',
            name='integre_en_stock',
            field=models.BooleanField(default=False, verbose_name='Intégré en stock'),
        ),
        migrations.AddField(
            model_name='receptionachat',
            name='integre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_integrees', to=settings.AUTH_USER_MODEL),
        ),
    ]
