# Generated by Django 6.0.5 on 2026-06-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_reception_integre_en_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereceptionachat',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de péremption'),
        ),
    ]
