# Generated by Django 6.0.5 on 2026-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_add_date_peremption_ligne_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereceptionachat',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de lot'),
        ),
    ]
