# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_add_numero_lot_ligne_reception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeachat',
            options={'ordering': ['-date_creation'], 'permissions': [('can_gerer_achats', 'Peut gérer les achats')], 'verbose_name': "Commande d'achat", 'verbose_name_plural': "Commandes d'achat"},
        ),
    ]
