# Generated by Django 6.0.5 on 2026-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_docteurreferentetiquette_employedepartement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
    ]
