# Generated by Django 6.0.5 on 2026-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_add_nationalite_to_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='stagiaire_societe',
            field=models.BooleanField(default=False, verbose_name='Stagiaire de la société'),
        ),
    ]
