# Matériel cryptographique du réseau "canal-sante" (généré par `cryptogen`,
# voir scripts/generate.sh). Trois organisations "acteurs de la prise en
# charge du patient" + l'organisation de l'orderer.

OrdererOrgs:
  - Name: Orderer
    Domain: orderer.wale-sante.local
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0

PeerOrgs:
  - Name: CentreSante
    Domain: centresante.wale-sante.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: VerificationFacture
    Domain: verificationfacture.wale-sante.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Regulateur
    Domain: regulateur.wale-sante.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
