# Generated by Django 6.0.4 on 2026-04-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delai_resultat_heures', models.IntegerField(default=24)),
            ],
            options={
                'verbose_name': "Type d'examen",
            },
        ),
        migrations.CreateModel(
            name='AnalyseLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_prelevement', models.DateTimeField(auto_now_add=True)),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_analyse', 'En analyse'), ('resultat', 'Résultat'), ('valide', 'Validé'), ('envoye', 'Envoyé')], default='recu', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('examen_demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.examendemande')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient')),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_tech', to=settings.AUTH_USER_MODEL)),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_val', to=settings.AUTH_USER_MODEL)),
                ('type_examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeexamen')),
            ],
            options={
                'verbose_name': 'Analyse laboratoire',
                'ordering': ['-date_prelevement'],
            },
        ),
        migrations.CreateModel(
            name='ExamenImagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_imagerie', models.CharField(choices=[('echographie', 'Échographie'), ('radiographie', 'Radiographie'), ('scanner', 'Scanner'), ('irm', 'IRM'), ('autre', 'Autre')], max_length=20)),
                ('zone_examinee', models.CharField(max_length=200)),
                ('date_examen', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_cours', 'En cours'), ('resultat', 'Résultat'), ('valide', 'Validé')], default='recu', max_length=20)),
                ('compte_rendu', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagerie/')),
                ('urgent', models.BooleanField(default=False)),
                ('examen_demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.examendemande')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageries', to='patients.patient')),
                ('radiologue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen imagerie',
            },
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre', models.CharField(max_length=200)),
                ('valeur', models.CharField(max_length=200)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('valeur_normale_min', models.CharField(blank=True, max_length=100)),
                ('valeur_normale_max', models.CharField(blank=True, max_length=100)),
                ('interpretation', models.CharField(blank=True, choices=[('normal', 'Normal'), ('eleve', 'Élevé'), ('bas', 'Bas'), ('critique', 'Critique')], max_length=20)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='laboratoire.analyselaboratoire')),
            ],
            options={
                'verbose_name': "Résultat d'analyse",
            },
        ),
    ]
