# Generated by Django 5.1.6 on 2026-05-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0001_initial'),
        ('patients', '0011_typevisite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_test', models.CharField(blank=True, choices=[('hematologie', 'Hématologie'), ('biochimie', 'Biochimie'), ('bacteriologie', 'Bactériologie'), ('serologie', 'Sérologie'), ('parasitologie', 'Parasitologie'), ('pathologie', 'Pathologie'), ('imagerie', 'Imagerie'), ('autre', 'Autre')], max_length=50)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('demande', 'Demandé'), ('accepte', 'Accepté'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='brouillon', max_length=20)),
                ('date_prelevement', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_examens', to='patients.patient')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_tech', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'examen",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=300)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instructions', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.demandeexamen')),
                ('type_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeexamen')),
            ],
            options={
                'verbose_name': "Ligne de demande d'examen",
            },
        ),
    ]
