# Generated by Django 6.0.5 on 2026-05-20 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratoire', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyselaboratoire',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='analyselaboratoire',
            name='technicien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyselaboratoire',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_val', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenimagerie',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageries', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='examenimagerie',
            name='radiologue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultatanalyse',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='laboratoire.analyselaboratoire'),
        ),
        migrations.AddField(
            model_name='analyselaboratoire',
            name='type_examen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeexamen'),
        ),
    ]
