# Generated by Django 5.1.6 on 2026-05-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('laboratoire', '0002_demandeexamen_lignedemandeexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamen',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examens', to='facturation.facture'),
        ),
    ]
