# Generated by Django 6.0.5 on 2026-05-19 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_add_stagiaire_societe'),
        ('laboratoire', '0002_remove_examen_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyselaboratoire',
            name='medecin_prescripteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_prescrites', to='employe.employe', verbose_name='Médecin prescripteur'),
        ),
    ]
