# Generated by Django 6.0.5 on 2026-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_departement_diplome_etiquette_specialite_and_more'),
        ('laboratoire', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyselaboratoire',
            name='medecin_prescripteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_prescrites', to='employer.employe', verbose_name='Médecin prescripteur'),
        ),
    ]
