# Generated by Django 6.0.5 on 2026-06-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0003_add_facture_to_demandeexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationHPRIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Configuration HPRIM', help_text='Libellé de cette configuration', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('emetteur_code', models.CharField(default='WALE', help_text='Code émetteur (ex. n° autorisation préfectorale) — champ 7.5', max_length=20)),
                ('emetteur_nom', models.CharField(default='CMS WALE', max_length=40)),
                ('recepteur_code', models.CharField(default='LABO', help_text='Code du laboratoire — champ 7.10', max_length=20)),
                ('recepteur_nom', models.CharField(default='LABORATOIRE', max_length=40)),
                ('type_liaison', models.CharField(choices=[('L', 'Laboratoires'), ('C', 'Clinique/hôpital'), ('R', 'Radiologie')], default='L', help_text='Table HPRIM 2 — champ 7.13', max_length=1)),
                ('prefixe_fichier', models.CharField(default='WALE', help_text='Préfixe RADIX 50 des noms de fichiers (A-Z, 0-9)', max_length=4)),
                ('ftp_host', models.CharField(blank=True, max_length=200)),
                ('ftp_port', models.IntegerField(default=21)),
                ('ftp_user', models.CharField(blank=True, max_length=100)),
                ('ftp_password', models.CharField(blank=True, max_length=200)),
                ('ftp_tls', models.BooleanField(default=False, verbose_name='FTPS (TLS)')),
                ('repertoire_envoi', models.CharField(blank=True, help_text='Dossier distant où déposer les demandes (ORM)', max_length=300)),
                ('repertoire_reception', models.CharField(blank=True, help_text='Dossier distant où relever les résultats (ORU)', max_length=300)),
                ('extension_temoin', models.CharField(default='.ok', max_length=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration HPRIM',
                'verbose_name_plural': 'Configurations HPRIM',
            },
        ),
        migrations.CreateModel(
            name='EchangeHPRIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('envoi', 'Envoi (ORM)'), ('reception', 'Réception (ORU)')], max_length=15)),
                ('contexte', models.CharField(help_text='ORM / ORU', max_length=5)),
                ('nom_fichier', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('transmis', 'Transmis'), ('recu', 'Reçu'), ('traite', 'Traité'), ('erreur', 'Erreur')], default='en_attente', max_length=15)),
                ('contenu', models.TextField(blank=True, help_text='Message HPRIM brut')),
                ('message_log', models.TextField(blank=True, help_text='Détails / erreurs', verbose_name='Journal')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_hprim', to='laboratoire.demandeexamen')),
            ],
            options={
                'verbose_name': 'Échange HPRIM',
                'verbose_name_plural': 'Échanges HPRIM',
                'ordering': ['-date_creation'],
            },
        ),
    ]
