# Generated by Django 6.0.5 on 2026-06-02 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0004_configurationhprim_echangehprim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErreurHPRIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier_errone', models.CharField(blank=True, help_text="Fichier d'origine en erreur (25.3)", max_length=20)),
                ('gravite', models.CharField(blank=True, choices=[('T', 'Rejet total du message'), ('P', 'Rejet partiel du message'), ('I', 'Pour information')], max_length=2)),
                ('type_erreur', models.CharField(blank=True, choices=[('A', 'Champ obligatoire absent'), ('I', 'Donnée inconnue ou incohérente'), ('S', 'Erreur de syntaxe')], max_length=2)),
                ('numero_ligne', models.CharField(blank=True, max_length=10)),
                ('adresse_segment', models.CharField(blank=True, help_text='Segment fautif (25.7)', max_length=200)),
                ('donnee_erronee', models.CharField(blank=True, help_text='N° HPRIM du champ (25.8)', max_length=50)),
                ('valeur_erronee', models.TextField(blank=True)),
                ('designation', models.TextField(blank=True, help_text='Description en clair (25.11)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs_hprim', to='laboratoire.demandeexamen')),
                ('echange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erreurs', to='laboratoire.echangehprim')),
            ],
            options={
                'verbose_name': 'Erreur HPRIM',
                'verbose_name_plural': 'Erreurs HPRIM',
                'ordering': ['-date_creation'],
            },
        ),
    ]
