# Generated by Django 5.1.6 on 2026-07-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0005_erreurhprim'),
        ('medecins', '0014_delete_modulespecialise'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamen',
            name='medecin_prescripteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examens', to='medecins.medecin'),
        ),
    ]
