# Generated by Django 5.1.6 on 2026-08-03 22:59

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_creer_centres_initiaux'),
        ('laboratoire', '0006_add_medecin_prescripteur_to_demandeexamen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationhprim',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Configuration HPRIM', 'verbose_name_plural': 'Configurations HPRIM'},
        ),
        migrations.AlterModelOptions(
            name='demandeexamen',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_creation'], 'verbose_name': "Demande d'examen"},
        ),
        migrations.AlterModelOptions(
            name='echangehprim',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_creation'], 'verbose_name': 'Échange HPRIM', 'verbose_name_plural': 'Échanges HPRIM'},
        ),
        migrations.AlterModelOptions(
            name='erreurhprim',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_creation'], 'verbose_name': 'Erreur HPRIM', 'verbose_name_plural': 'Erreurs HPRIM'},
        ),
        migrations.AlterModelManagers(
            name='configurationhprim',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='demandeexamen',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='echangehprim',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='erreurhprim',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='configurationhprim',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='echangehprim',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='erreurhprim',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
