# Generated by Django 5.1.6 on 2026-08-03 23:00

from django.db import migrations

MODELES = ['ConfigurationHPRIM', 'DemandeExamen', 'EchangeHPRIM', 'ErreurHPRIM']


def rattacher_a_wale(apps, schema_editor):
    Centre = apps.get_model('centres', 'Centre')
    wale = Centre.objects.filter(code='WALE').first()
    if wale is None:
        return
    for nom_modele in MODELES:
        Modele = apps.get_model('laboratoire', nom_modele)
        Modele.objects.filter(centre__isnull=True).update(centre=wale)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0007_alter_configurationhprim_options_and_more'),
        ('centres', '0002_creer_centres_initiaux'),
    ]

    operations = [
        migrations.RunPython(rattacher_a_wale, noop),
    ]
