# Generated by Django 5.1.6 on 2026-09-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0008_hprim_centre_data'),
        ('services', '0017_articleservice_code_hprim'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedemandeexamen',
            name='article_service',
            field=models.ForeignKey(blank=True, help_text='Article du catalogue Services (catégorie Examens biologiques) sélectionné à la création de la demande ; permet de retrouver le code HPRIM du laboratoire partenaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_demande_examen', to='services.articleservice', verbose_name='Article de service'),
        ),
    ]
