# Generated by Django 6.0.7 on 2026-09-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0009_lignedemandeexamen_article_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedemandeexamen',
            name='origine',
            field=models.CharField(choices=[('medecin', 'Demandé par le médecin'), ('caisse', 'Ajouté à la caisse')], default='medecin', max_length=10),
        ),
    ]
