# Generated by Django 6.0.5 on 2026-06-09 11:20

from django.db import migrations


def forwards(apps, schema_editor):
    Module = apps.get_model('modules_permissions', 'Module')
    Module.objects.filter(code='stock').update(url_name='stock_dashboard')


def backwards(apps, schema_editor):
    Module = apps.get_model('modules_permissions', 'Module')
    Module.objects.filter(code='stock').update(url_name='admin:pharmacie_lotmedicament_changelist')


class Migration(migrations.Migration):

    dependencies = [
        ('modules_permissions', '0005_update_facturation_url'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
