# Generated by Django 6.0.6 on 2026-07-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modules_permissions', '0005_update_facturation_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique (ex: patients.pathologie_config)', max_length=100, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='modules_permissions.module', verbose_name='Module parent')),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Éléments de menu',
                'ordering': ['module__order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GroupNavItemRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_nav_items', to='auth.group', verbose_name='Groupe')),
                ('nav_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_restrictions', to='modules_permissions.navitem', verbose_name='Élément de menu')),
            ],
            options={
                'verbose_name': 'Menu masqué pour un groupe',
                'verbose_name_plural': 'Menus masqués par groupe',
                'unique_together': {('group', 'nav_item')},
            },
        ),
        migrations.CreateModel(
            name='UserNavItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('hide', 'Masquer (même si le groupe l’autorise)'), ('show', 'Afficher (même si le groupe le masque)')], default='hide', max_length=10, verbose_name='Type')),
                ('nav_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='modules_permissions.navitem', verbose_name='Élément de menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_item_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Override menu utilisateur',
                'verbose_name_plural': 'Overrides menus utilisateurs',
                'unique_together': {('user', 'nav_item')},
            },
        ),
    ]
