# Generated by Django 6.0.5 on 2026-05-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie médicament',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CompagniePharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('partenaire', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Compagnie pharmaceutique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DosageMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('frequence', models.CharField(blank=True, max_length=100)),
                ('qte_totale_par_jour', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('jours', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
            options={
                'verbose_name': 'Dosage médicament',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EffetTherapeutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Effet thérapeutique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FormulaireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Formulaire du médicament',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RouteMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Route des médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('limite', models.IntegerField(default=0)),
                ('maladies', models.TextField(blank=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_medicament_catalogue', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Groupe de médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=300)),
                ('dci', models.CharField(blank=True, max_length=200, verbose_name='DCI')),
                ('forme', models.CharField(choices=[('comprime', 'Comprimé'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('gelule', 'Gélule'), ('solution', 'Solution'), ('autre', 'Autre')], default='comprime', max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('peut_etre_vendu', models.BooleanField(default=True)),
                ('peut_etre_achete', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('voie_administration', models.CharField(blank=True, max_length=200)),
                ('frequence', models.CharField(blank=True, max_length=100)),
                ('composant_actif', models.CharField(blank=True, max_length=300)),
                ('effets_indesirables', models.TextField(blank=True)),
                ('quantite_prescription_manuelle', models.BooleanField(default=False)),
                ('indications', models.TextField(blank=True)),
                ('remarques', models.TextField(blank=True)),
                ('avertissement_grossesse', models.BooleanField(default=False)),
                ('avertissement_lactation', models.BooleanField(default=False)),
                ('nom_produit_fabricant', models.CharField(blank=True, max_length=300)),
                ('code_produit_fabricant', models.CharField(blank=True, max_length=100)),
                ('url_produit', models.URLField(blank=True)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_alerte', models.IntegerField(default=10)),
                ('stock_minimum', models.IntegerField(default=5)),
                ('reference_interne', models.CharField(blank=True, max_length=100)),
                ('code_barres', models.CharField(blank=True, max_length=100)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicament.categoriemedicament')),
                ('compagnie_pharma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicament.compagniepharma')),
                ('effet_therapeutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicament.effettherapeutique')),
            ],
            options={
                'verbose_name': 'Médicament',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='LigneMedicamentGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorise', models.BooleanField(default=True)),
                ('frequence_posologique', models.CharField(blank=True, max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('unite_dosage', models.CharField(blank=True, max_length=50)),
                ('qte_par_jour', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('jours', models.IntegerField(default=1)),
                ('qte_totale', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commentaire', models.TextField(blank=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='medicament.groupemedicament')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicament.medicament')),
            ],
            options={
                'verbose_name': 'Ligne groupe médicament',
            },
        ),
    ]
