# Generated by Django 6.0.5 on 2026-05-20 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0008_add_quantite_stock_to_articleservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'medecins_departement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'db_table': 'medecins_diplome',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='DocteurReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_contact', models.CharField(choices=[('individu', 'Individu'), ('societe', 'Société')], default='individu', max_length=10, verbose_name='Type')),
                ('titre', models.CharField(blank=True, choices=[('', '—'), ('dr', 'Dr'), ('pr', 'Pr'), ('m', 'M.'), ('mme', 'Mme'), ('prof', 'Prof.')], max_length=10, verbose_name='Titre')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(blank=True, max_length=200, verbose_name='Prénom(s)')),
                ('genre', models.CharField(blank=True, choices=[('', '—'), ('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Genre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/referents/')),
                ('poste_occupe', models.CharField(blank=True, max_length=100, verbose_name='Poste Occupé')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True, verbose_name='Site Web')),
                ('langue', models.CharField(blank=True, default='Français', max_length=50, verbose_name='Langue')),
                ('adresse', models.TextField(blank=True)),
                ('tva', models.CharField(blank=True, max_length=50, verbose_name='TVA')),
                ('est_referent', models.BooleanField(default=True, verbose_name='Est le médecin référent')),
                ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('compte_client', models.CharField(blank=True, max_length=100, verbose_name='Compte client')),
                ('compte_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Compte fournisseur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Docteur Référent',
                'verbose_name_plural': 'Docteurs Référents',
                'db_table': 'medecins_docteurreferent',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('couleur', models.CharField(blank=True, default='#0ea5e9', max_length=7)),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'db_table': 'medecins_etiquette',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'db_table': 'medecins_specialite',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ContactAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(choices=[('contact', 'Contact'), ('facturation', 'Adresse de facturation'), ('livraison', 'Adresse de livraison'), ('autre', 'Autre adresse')], default='contact', max_length=20, verbose_name='Type')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('referent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_contacts_adresses', to='utilisateur.docteurreferent')),
            ],
            options={
                'verbose_name': 'Contact / Adresse',
                'verbose_name_plural': 'Contacts / Adresses',
                'db_table': 'medecins_contactadresse',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('', '—'), ('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Genre')),
                ('titre', models.CharField(blank=True, choices=[('', '—'), ('dr', 'Dr'), ('pr', 'Pr'), ('m', 'M.'), ('mme', 'Mme'), ('prof', 'Prof.')], max_length=10, verbose_name='Titre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/photos/')),
                ('est_medecin', models.BooleanField(default=False, verbose_name='Est Médecin/Docteur')),
                ('est_referent', models.BooleanField(default=False, verbose_name='Est Médecin Référent')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction / Poste')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('adresse', models.TextField(blank=True, verbose_name="Lieu d'habitation")),
                ('tva_numero_fiscal', models.CharField(blank=True, max_length=50, verbose_name='TVA / N° fiscal')),
                ('ordre_medecin', models.CharField(blank=True, max_length=50)),
                ('duree_consultation', models.PositiveSmallIntegerField(default=15, verbose_name='Durée consultation (min)')),
                ('chirurgien_principal', models.BooleanField(default=False)),
                ('taux_honoraire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employe_societe', models.BooleanField(default=True, verbose_name='Employé de la société')),
                ('stagiaire_societe', models.BooleanField(default=False, verbose_name='Stagiaire de la société')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='medecins/signatures/', verbose_name='Signature')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('langue', models.CharField(blank=True, default='Français', max_length=50, verbose_name='Langue')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('diplome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utilisateur.diplome', verbose_name='Éducation')),
                ('service_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.articleservice', verbose_name='service de consultation')),
                ('service_suivi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.articleservice', verbose_name='service de suivi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'medecins_medecin',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='medecin_interne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utilisateur.employe', verbose_name='Docteur référent (interne)'),
        ),
        migrations.CreateModel(
            name='DiplomePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du diplôme')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_diplomes_personnels', to='utilisateur.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Diplôme personnel',
                'verbose_name_plural': 'Diplômes personnels',
                'db_table': 'medecins_diplomepersonnel',
                'ordering': ['-annee', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='EmployeDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.departement')),
                ('employe', models.ForeignKey(db_column='medecin_id', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.employe')),
            ],
            options={
                'db_table': 'medecins_medecin_departements',
                'unique_together': {('employe', 'departement')},
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='+', through='utilisateur.EmployeDepartement', to='utilisateur.departement', verbose_name='Départements'),
        ),
        migrations.CreateModel(
            name='DocteurReferentEtiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docteurreferent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.docteurreferent')),
                ('etiquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.etiquette')),
            ],
            options={
                'db_table': 'medecins_docteurreferent_etiquettes',
                'unique_together': {('docteurreferent', 'etiquette')},
            },
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, related_name='+', through='utilisateur.DocteurReferentEtiquette', to='utilisateur.etiquette', verbose_name='Étiquettes'),
        ),
        migrations.AddField(
            model_name='employe',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utilisateur.specialite'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utilisateur.specialite', verbose_name='Spécialité'),
        ),
    ]
