# Generated by Django 6.0.5 on 2026-05-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='employes', through='utilisateur.EmployeDepartement', to='utilisateur.departement', verbose_name='Départements'),
        ),
    ]
