# Generated by Django 6.0.5 on 2026-05-27 14:34
# Edited: SeparateDatabaseAndState pour les modèles déplacés vers employer
# Les tables utilisateur_departement, utilisateur_diplome, utilisateur_etiquette,
# utilisateur_specialite, utilisateur_docteurreferent, utilisateur_contactadresse,
# utilisateur_docteurreferent_etiquettes sont conservées (reprises par employer).
# Seules utilisateur_employe, utilisateur_diplomepersonnel et
# utilisateur_employe_departements sont physiquement supprimées.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_departement_diplome_etiquette_specialite_and_more'),
        ('hospitalisation', '0003_alter_fichevisite_medecin_and_more'),
        ('laboratoire', '0003_alter_analyselaboratoire_medecin_prescripteur'),
        ('ordonnances', '0003_alter_groupemedicaments_medecin_and_more'),
        ('patients', '0002_alter_patient_medecin_referent_and_more'),
        ('soins', '0003_alter_proceduresoin_departement_and_more'),
        ('utilisateur', '0003_rename_tables'),
    ]

    operations = [
        # ── Tout en une seule SeparateDatabaseAndState ────────────────────────────
        # state_operations  : met à jour l'état Django (supprime tous les modèles)
        # database_operations : exécute uniquement les DROP TABLE pour les tables
        #                       qui n'appartiennent plus à aucun modèle actif
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Nettoyer DocteurReferent (table gardée par employer)
                migrations.RemoveField(
                    model_name='docteurreferent',
                    name='etiquettes',
                ),
                migrations.RemoveField(
                    model_name='docteurreferent',
                    name='medecin_interne',
                ),
                migrations.RemoveField(
                    model_name='docteurreferent',
                    name='specialite',
                ),
                migrations.RemoveField(
                    model_name='docteurreferentetiquette',
                    name='docteurreferent',
                ),
                migrations.AlterUniqueTogether(
                    name='docteurreferentetiquette',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='docteurreferentetiquette',
                    name='etiquette',
                ),
                # Nettoyer Employe utilisateur
                migrations.RemoveField(
                    model_name='employe',
                    name='service_consultation',
                ),
                migrations.RemoveField(
                    model_name='employe',
                    name='service_suivi',
                ),
                migrations.RemoveField(
                    model_name='employe',
                    name='specialite',
                ),
                migrations.RemoveField(
                    model_name='employe',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='employe',
                    name='diplome',
                ),
                migrations.RemoveField(
                    model_name='employe',
                    name='departements',
                ),
                migrations.RemoveField(
                    model_name='employedepartement',
                    name='departement',
                ),
                migrations.RemoveField(
                    model_name='employedepartement',
                    name='employe',
                ),
                migrations.AlterUniqueTogether(
                    name='employedepartement',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='diplomepersonnel',
                    name='employe',
                ),
                # Supprimer les modèles de l'état Django
                migrations.DeleteModel(name='ContactAdresse'),
                migrations.DeleteModel(name='Departement'),
                migrations.DeleteModel(name='Diplome'),
                migrations.DeleteModel(name='DiplomePersonnel'),
                migrations.DeleteModel(name='DocteurReferent'),
                migrations.DeleteModel(name='DocteurReferentEtiquette'),
                migrations.DeleteModel(name='Etiquette'),
                migrations.DeleteModel(name='Specialite'),
                migrations.DeleteModel(name='Employe'),
                migrations.DeleteModel(name='EmployeDepartement'),
            ],
            database_operations=[
                # DROP uniquement les tables qui ne sont plus utilisées
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS utilisateur_diplomepersonnel",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS utilisateur_employe_departements",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS utilisateur_employe",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
