# Generated by Django 5.1.6 on 2026-08-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centre',
                'ordering': ['nom'],
            },
        ),
    ]
