# Generated by Django 5.1.6 on 2026-08-03 22:50

from django.db import migrations

CENTRES = [
    {'nom': 'CMS WALE Yamoussoukro', 'code': 'WALE'},
    {'nom': 'CMS WALE Toumbokro', 'code': 'TOUMBOKRO'},
]


def creer_centres(apps, schema_editor):
    Centre = apps.get_model('centres', 'Centre')
    for data in CENTRES:
        Centre.objects.get_or_create(code=data['code'], defaults={'nom': data['nom'], 'actif': True})


def supprimer_centres(apps, schema_editor):
    Centre = apps.get_model('centres', 'Centre')
    Centre.objects.filter(code__in=[c['code'] for c in CENTRES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(creer_centres, supprimer_centres),
    ]
