from django.urls import path
from . import views

app_name = 'hospitalisation'

urlpatterns = [
    path('', views.hospitalisation_list, name='list'),
    path('nouveau/', views.hospitalisation_create, name='create'),
    path('<int:pk>/',              views.hospitalisation_detail,       name='detail'),
    path('<int:pk>/modifier/',     views.hospitalisation_edit,         name='edit'),
    path('<int:pk>/creer-facture/', views.hospitalisation_creer_facture, name='creer_facture'),
    path('<int:pk>/confirmer/',    views.hospitalisation_confirmer,    name='confirmer'),
    path('<int:pk>/installer/',    views.hospitalisation_installer,    name='installer'),
    path('<int:pk>/decharger/',    views.hospitalisation_decharger,    name='decharger'),
    path('<int:pk>/terminer/',     views.hospitalisation_terminer,     name='terminer'),
    path('<int:pk>/annuler/',      views.hospitalisation_annuler,      name='annuler'),
    path('<int:pk>/etat/',         views.hospitalisation_etat,         name='etat'),
    path('<int:pk>/ajouter-soin/', views.hospitalisation_ajouter_soin, name='ajouter_soin'),
    path('chambres/', views.chambres_list, name='chambres_list'),
    path('chambres/nouveau/', views.chambre_create, name='chambre_create'),
    path('chambres/<int:pk>/', views.chambre_detail, name='chambre_detail'),
    path('chambres/<int:pk>/modifier/', views.chambre_edit, name='chambre_edit'),
    path('chambres/export/', views.chambres_export, name='chambres_export'),
    path('chambres/importer/', views.chambres_import, name='chambres_import'),
    path('deces/', views.registre_deces, name='deces_list'),
    path('deces/nouveau/', views.deces_create, name='deces_create'),
    path('deces/<int:pk>/', views.deces_detail, name='deces_detail'),
    path('deces/<int:pk>/modifier/', views.deces_edit, name='deces_edit'),
    path('deces/export/', views.deces_export, name='deces_export'),
    path('deces/importer/', views.deces_import, name='deces_import'),
    path('configuration/', views.configuration, name='configuration'),
    path('configuration/batiments/', views.config_batiments, name='config_batiments'),
    path('configuration/liste-admission/', views.config_liste_admission, name='config_liste_admission'),
    path('configuration/liste-admission/nouveau/', views.liste_admission_create, name='liste_admission_create'),
    path('configuration/liste-admission/<int:pk>/modifier/', views.liste_admission_edit, name='liste_admission_edit'),
    path('configuration/liste-admission/<int:pk>/supprimer/', views.liste_admission_delete, name='liste_admission_delete'),
    path('configuration/liste-admission/export/', views.liste_admission_export, name='liste_admission_export'),
    path('configuration/liste-admission/importer/', views.liste_admission_import, name='liste_admission_import'),
    path('configuration/liste-service/', views.config_liste_service, name='config_liste_service'),
    path('configuration/liste-service/nouveau/', views.liste_service_create, name='liste_service_create'),
    path('configuration/liste-service/<int:pk>/modifier/', views.liste_service_edit, name='liste_service_edit'),
    path('configuration/liste-service/<int:pk>/supprimer/', views.liste_service_delete, name='liste_service_delete'),
    path('configuration/liste-service/export/', views.liste_service_export, name='liste_service_export'),
    path('configuration/liste-service/importer/', views.liste_service_import, name='liste_service_import'),
]
