# Generated by Django 6.0.5 on 2026-05-13 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompagniePharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compagnie pharmaceutique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FamilleArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': "Famille d'article",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ArticleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, verbose_name="Nom de l'article")),
                ('reference_interne', models.CharField(blank=True, max_length=100, verbose_name='Référence interne')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/photos/')),
                ('favori', models.BooleanField(default=False, verbose_name='Favori')),
                ('peut_etre_vendu', models.BooleanField(default=True, verbose_name='Peut être vendu')),
                ('peut_etre_achete', models.BooleanField(default=True, verbose_name='Peut être acheté')),
                ('forme', models.CharField(blank=True, choices=[('comprime', 'Comprimé'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('gelule', 'Gélule'), ('solution', 'Solution'), ('suppositoire', 'Suppositoire'), ('patch', 'Patch'), ('sachet', 'Sachet'), ('gouttes', 'Gouttes'), ('autre', 'Autre')], max_length=20, verbose_name='Forme')),
                ('voie_administration', models.CharField(blank=True, choices=[('orale', 'Orale'), ('injectable', 'Injectable / IV'), ('topique', 'Topique / Cutanée'), ('rectale', 'Rectale'), ('nasale', 'Nasale'), ('ophtalmique', 'Ophtalmique'), ('autre', 'Autre')], max_length=20, verbose_name="Voie d'administration")),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dosage')),
                ('dosage_unite', models.CharField(blank=True, max_length=50, verbose_name='Unité de dosage')),
                ('quantite_prescription_manuelle', models.BooleanField(default=False, verbose_name='Quantité de prescription manuelle')),
                ('frequence', models.CharField(blank=True, max_length=100, verbose_name='Fréquence')),
                ('composant_actif', models.CharField(blank=True, max_length=200, verbose_name='Composant actif')),
                ('effet_therapeutique', models.CharField(blank=True, max_length=200, verbose_name='Effet thérapeutique')),
                ('effets_indesirables', models.TextField(blank=True, verbose_name='Effets indésirables')),
                ('code_produit', models.CharField(blank=True, max_length=100, verbose_name='Code produit')),
                ('url_produit', models.URLField(blank=True, verbose_name='URL du produit')),
                ('nom_produit_fabricant', models.CharField(blank=True, max_length=200, verbose_name='Nom du produit')),
                ('avertissement_grossesse', models.BooleanField(default=False, verbose_name='Avertissement de grossesse')),
                ('avertissement_lactation', models.BooleanField(default=False, verbose_name='Avertissement de lactation')),
                ('indications', models.TextField(blank=True, verbose_name='Indications')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('type_article', models.CharField(choices=[('consommable', 'Consommable'), ('stockable', 'Peut être stocké'), ('service', 'Service'), ('autre', 'Autre')], default='consommable', max_length=20, verbose_name="Type d'article")),
                ('type_produit_hospitalier', models.CharField(blank=True, choices=[('medicament', 'Médicament'), ('consommable', 'Consommable médical'), ('equipement', 'Équipement'), ('service', 'Service médical'), ('examen', 'Examen / Analyse'), ('autre', 'Autre')], max_length=20, verbose_name='Type de produit hospitalier')),
                ('politique_facturation', models.CharField(choices=[('qtes_commandees', 'Quantités commandées'), ('qtes_livrees', 'Quantités livrées')], default='qtes_commandees', max_length=20, verbose_name='Politique de facturation')),
                ('refacturer_depenses', models.CharField(choices=[('non', 'Non'), ('au_cout', 'Au coût'), ('prix_vente', 'Prix de vente')], default='non', max_length=20, verbose_name='Re-facturer les dépenses')),
                ('unite_mesure', models.CharField(default='Unités', max_length=50, verbose_name='Unité de mesure')),
                ('unite_achat', models.CharField(default='Unités', max_length=50, verbose_name="Unité d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prix de vente (CFA)')),
                ('taxes_vente', models.CharField(blank=True, max_length=100, verbose_name='Taxes à la vente')),
                ('cout', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Coût')),
                ('code_barres', models.CharField(blank=True, max_length=100, verbose_name='Code-barres')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('description_vente', models.TextField(blank=True, verbose_name='Description vente')),
                ('taxes_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Taxes fournisseur')),
                ('politique_controle', models.CharField(choices=[('qtes_commandees', 'Sur les quantités commandées'), ('qtes_recues', 'Sur les quantités reçues')], default='qtes_recues', max_length=20, verbose_name='Politique de contrôle')),
                ('description_achat', models.TextField(blank=True, verbose_name='Description achat')),
                ('poids', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Poids (kg)')),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Volume (m³)')),
                ('delai_livraison_client', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Délai de livraison au client (jours)')),
                ('description_reception', models.TextField(blank=True, verbose_name='Description pour les réceptions')),
                ('description_livraison', models.TextField(blank=True, verbose_name='Description pour les bons de livraison')),
                ('description_transfert', models.TextField(blank=True, verbose_name='Description pour les transferts internes')),
                ('compte_revenus', models.CharField(blank=True, max_length=100, verbose_name='Compte de revenus')),
                ('compte_charges', models.CharField(blank=True, max_length=100, verbose_name='Compte de charges')),
                ('compte_ecart_prix', models.CharField(blank=True, max_length=100, verbose_name="Compte d'écart de prix")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.categoriearticle', verbose_name="Catégorie d'article")),
                ('compagnie_pharmaceutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.compagniepharma', verbose_name='Compagnie pharmaceutique')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.famillearticle', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Article / Service',
                'verbose_name_plural': 'Articles / Services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConditionnementArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionnement', models.CharField(max_length=100, verbose_name='Conditionnement')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité contenue')),
                ('unite_mesure', models.CharField(default='Unités', max_length=50, verbose_name='Unité de mesure')),
                ('pour_vente', models.BooleanField(default=True, verbose_name='Ventes')),
                ('pour_achat', models.BooleanField(default=True, verbose_name='Achats')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionnements', to='services.articleservice')),
            ],
            options={
                'verbose_name': 'Conditionnement',
            },
        ),
        migrations.CreateModel(
            name='LigneFournisseurArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article_fournisseur', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'article chez le fournisseur")),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('quantite_min', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité min.')),
                ('unite_mesure', models.CharField(default='Unités', max_length=50, verbose_name='Unité de mesure')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prix (CFA)')),
                ('delai_livraison', models.IntegerField(default=0, verbose_name='Délai de livraison (jours)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='services.articleservice')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': "Fournisseur de l'article",
                'ordering': ['fournisseur__nom'],
            },
        ),
        migrations.CreateModel(
            name='ReglePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_prix', models.CharField(max_length=100, verbose_name='Liste de prix')),
                ('applique_sur', models.CharField(blank=True, max_length=200, verbose_name='Appliqué sur')),
                ('quantite_min', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité min.')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (CFA)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_prix', to='services.articleservice')),
            ],
            options={
                'verbose_name': 'Règle de prix',
                'ordering': ['liste_prix'],
            },
        ),
        migrations.CreateModel(
            name='VarianteAttributArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristique', models.CharField(max_length=100, verbose_name='Caractéristique')),
                ('valeurs', models.CharField(max_length=300, verbose_name='Valeurs')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='services.articleservice')),
            ],
            options={
                'verbose_name': 'Attribut / Variante',
            },
        ),
    ]
