# Generated by Django 6.0.5 on 2026-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Abréviation')),
                ('categorie', models.CharField(choices=[('volume', 'Volume'), ('masse', 'Masse'), ('quantite', 'Quantité'), ('conditionnement', 'Conditionnement'), ('autre', 'Autre')], default='quantite', max_length=20, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['nom'],
            },
        ),
    ]
