# Generated by Django 6.0.5 on 2026-05-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_consommable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieUniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Catégorie d'unité de mesure",
                'verbose_name_plural': "Catégories d'unités de mesure",
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='precision_arrondi',
            field=models.DecimalField(decimal_places=5, default=0.01, max_digits=8, verbose_name="Précision d'arrondi"),
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='ratio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Ratio'),
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='type_unite',
            field=models.CharField(choices=[('pgumr', "Plus grande que l'unité de mesure de référence"), ('umrc', 'Unité de mesure de référence pour cette catégorie'), ('ppumr', "Plus petite que l'unité de mesure de référence")], default='umrc', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='unitemesure',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites', to='services.categorieunitemesure', verbose_name='Catégorie'),
        ),
    ]
