# Generated by Django 6.0.5 on 2026-05-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_categoriearticle_options_and_more'),
    ]

    operations = [
        # ── Articleservice : unite_mesure ─────────────────────────
        migrations.AddField(
            model_name='articleservice',
            name='unite_mesure_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='articles_um',
                to='services.unitemesure',
                verbose_name='Unité de mesure',
            ),
        ),
        migrations.RemoveField(model_name='articleservice', name='unite_mesure'),
        migrations.RenameField(model_name='articleservice', old_name='unite_mesure_fk', new_name='unite_mesure'),

        # ── Articleservice : unite_achat ──────────────────────────
        migrations.AddField(
            model_name='articleservice',
            name='unite_achat_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='articles_ua',
                to='services.unitemesure',
                verbose_name="Unité d'achat",
            ),
        ),
        migrations.RemoveField(model_name='articleservice', name='unite_achat'),
        migrations.RenameField(model_name='articleservice', old_name='unite_achat_fk', new_name='unite_achat'),

        # ── LigneFournisseurArticle : unite_mesure ────────────────
        migrations.AddField(
            model_name='lignefournisseurarticle',
            name='unite_mesure_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='services.unitemesure',
                verbose_name='Unité de mesure',
            ),
        ),
        migrations.RemoveField(model_name='lignefournisseurarticle', name='unite_mesure'),
        migrations.RenameField(model_name='lignefournisseurarticle', old_name='unite_mesure_fk', new_name='unite_mesure'),

        # ── ConditionnementArticle : unite_mesure ─────────────────
        migrations.AddField(
            model_name='conditionnementarticle',
            name='unite_mesure_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='services.unitemesure',
                verbose_name='Unité de mesure',
            ),
        ),
        migrations.RemoveField(model_name='conditionnementarticle', name='unite_mesure'),
        migrations.RenameField(model_name='conditionnementarticle', old_name='unite_mesure_fk', new_name='unite_mesure'),
    ]
