# Generated by Django 6.0.5 on 2026-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_articleservice_unite_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de service',
                'verbose_name_plural': 'Types de service',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='articleservice',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='articles', to='services.typeservice', verbose_name='Types de service'),
        ),
    ]
