# Generated by Django 6.0.5 on 2026-05-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_typeservice_articleservice_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleservice',
            options={'ordering': ['nom'], 'verbose_name': 'Article / Service', 'verbose_name_plural': 'Articles / Services'},
        ),
        migrations.AddField(
            model_name='articleservice',
            name='quantite_alerte',
            field=models.IntegerField(default=0, verbose_name="Quantité d'alerte"),
        ),
        migrations.AddField(
            model_name='articleservice',
            name='quantite_stock',
            field=models.IntegerField(default=0, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='articleservice',
            name='type_article',
            field=models.CharField(choices=[('prestation', 'Prestation'), ('consommable', 'Consommable'), ('stockable', 'Peut être stocké'), ('autre', 'Autre')], default='consommable', max_length=20, verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='articleservice',
            name='type_produit_hospitalier',
            field=models.CharField(blank=True, choices=[('medicament', 'Médicament'), ('consommable', 'Consommable médical'), ('equipement', 'Équipement'), ('service', 'Service médical'), ('examen', 'Examen / Analyse'), ('autre', 'Autre')], max_length=20, verbose_name='Type de produit hospitalier'),
        ),
    ]
