# Generated by Django 6.0.5 on 2026-06-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefournisseurarticle',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
