# Generated by Django 6.0.6 on 2026-07-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_lignefournisseurarticle_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleservice',
            name='types',
        ),
        migrations.DeleteModel(
            name='Consommable',
        ),
        migrations.DeleteModel(
            name='Typeservice',
        ),
    ]
