# Generated by Django 6.0.6 on 2026-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_articleservice_types_delete_consommable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleservice',
            name='reference_interne',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence interne'),
        ),
    ]
