# Generated by Django 6.0.6 on 2026-07-03 22:31

from django.db import migrations, models


def clean_reference_interne(apps, schema_editor):
    """Convert blank/empty reference_interne to NULL and deduplicate non-null values."""
    ArticleService = apps.get_model('services', 'ArticleService')

    # Step 1: convert blank strings to NULL
    ArticleService.objects.filter(reference_interne='').update(reference_interne=None)

    # Step 2: deduplicate non-null values by appending a suffix
    seen = {}
    for obj in ArticleService.objects.exclude(reference_interne=None).order_by('id'):
        ref = obj.reference_interne
        if ref in seen:
            seen[ref] += 1
            obj.reference_interne = f"{ref}_{seen[ref]}"
            obj.save(update_fields=['reference_interne'])
        else:
            seen[ref] = 1


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_articleservice_types_delete_consommable_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_reference_interne, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='articleservice',
            name='reference_interne',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence interne'),
        ),
    ]
