# Generated by Django 6.0.6 on 2026-07-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_categoriearticle_service_associe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriearticle',
            name='service_associe',
        ),
    ]
