# Generated by Django 5.2.15 on 2026-07-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_categoriearticle_service_associe'),
        ('services', '0012_remove_unitemesure_categorie_and_more'),
    ]

    operations = [
    ]
