# Generated by Django 6.0.6 on 2026-07-09 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0011_remove_medecin_service_remove_service_departement_and_more'),
        ('services', '0013_remove_categoriearticle_service_associe'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleservice',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.departement', verbose_name='Département'),
        ),
    ]
