# Generated by Django 5.2.15 on 2026-07-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_merge_20260708_0951'),
        ('services', '0014_articleservice_departement'),
    ]

    operations = [
    ]
