# Generated by Django 5.1.6 on 2026-09-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_merge_20260712_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleservice',
            name='type_test_labo',
            field=models.CharField(blank=True, choices=[('hematologie', 'Hématologie'), ('biochimie', 'Biochimie'), ('bacteriologie', 'Bactériologie'), ('serologie', 'Sérologie'), ('parasitologie', 'Parasitologie'), ('pathologie', 'Pathologie'), ('imagerie', 'Imagerie'), ('autre', 'Autre')], help_text='Pour un examen de laboratoire : sous-catégorie utilisée pour filtrer la liste des tests proposés selon le type de test choisi sur la demande.', max_length=20, verbose_name='Type de test (laboratoire)'),
        ),
    ]
