# Generated by Django 5.1.6 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_articleservice_type_test_labo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleservice',
            name='code_hprim',
            field=models.CharField(blank=True, help_text="Pour un examen de laboratoire : code attendu par le laboratoire partenaire pour reconnaître et router automatiquement l'analyse dans les échanges HPRIM. Laisser vide si le labo accepte le libellé seul.", max_length=50, verbose_name='Code HPRIM (laboratoire partenaire)'),
        ),
    ]
