# Generated by Django 6.0.7 on 2026-09-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_articleservice_code_hprim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriearticle',
            name='bloquer_serie_lot',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='compte_charges',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='compte_revenus',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='methode_cout',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='reservation_conditionnement',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='sequence_code_barres',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='strategie_enlevement',
        ),
        migrations.RemoveField(
            model_name='categoriearticle',
            name='valorisation_inventaire',
        ),
    ]
