# Generated by Django 6.0.7 on 2026-09-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_remove_categoriearticle_bloquer_serie_lot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleservice',
            name='avertissement_grossesse',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='avertissement_lactation',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='code_barres',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='composant_actif',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='compte_charges',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='compte_ecart_prix',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='compte_revenus',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='dosage_unite',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='effet_therapeutique',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='forme',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='indications',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='notes_internes',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='unite_achat',
        ),
        migrations.RemoveField(
            model_name='articleservice',
            name='voie_administration',
        ),
    ]
