# Generated by Django 6.0.5 on 2026-05-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_unite_mesure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_achat', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Prix d'achat (CFA)")),
                ('prix_vente', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prix de vente (CFA)')),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('quantite_alerte', models.IntegerField(default=0, verbose_name="Quantité d'alerte")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.categoriearticle', verbose_name='Catégorie')),
                ('unite_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.unitemesure', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'Consommable',
                'verbose_name_plural': 'Consommables',
                'ordering': ['nom'],
            },
        ),
    ]
