# Generated by Django 6.0.5 on 2026-05-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_categorieunitemesure_unitemesure_actif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriearticle',
            options={'ordering': ['nom'], 'verbose_name': "Catégorie d'article", 'verbose_name_plural': "Catégories d'article"},
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='bloquer_serie_lot',
            field=models.BooleanField(default=False, verbose_name='Bloquer les nouveaux numéros de série/lots'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='compte_charges',
            field=models.CharField(blank=True, max_length=200, verbose_name='Compte de charges'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='compte_revenus',
            field=models.CharField(blank=True, max_length=200, verbose_name='Compte de revenus'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='methode_cout',
            field=models.CharField(choices=[('prix_standard', 'Prix standard'), ('avco', 'Coût moyen (AVCO)'), ('fifo', 'Premier entré, premier sorti (FIFO)')], default='prix_standard', max_length=20, verbose_name='Méthode de coût'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='services.categoriearticle', verbose_name='Catégorie parente'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='reservation_conditionnement',
            field=models.CharField(choices=[('partiels', 'Réserver des conditionnements partiels'), ('entiers', 'Réserver seulement des conditionnements entiers')], default='partiels', max_length=10, verbose_name='Réserver les conditionnements'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='routes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Routes'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='sequence_code_barres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Séquence de code-barres'),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='strategie_enlevement',
            field=models.CharField(blank=True, choices=[('', '—'), ('fifo', 'Premier entré, premier sorti (FIFO)'), ('fefo', 'Premier périmé, premier sorti (FEFO)'), ('lifo', 'Dernier entré, premier sorti (LIFO)')], max_length=10, verbose_name="Forcer la stratégie d'enlèvement"),
        ),
        migrations.AddField(
            model_name='categoriearticle',
            name='valorisation_inventaire',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20, verbose_name="Valorisation de l'inventaire"),
        ),
        migrations.AlterField(
            model_name='categoriearticle',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='categoriearticle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categoriearticle',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
