# Generated by Django 5.1.6 on 2026-09-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AncrageBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evenement', models.CharField(editable=False, max_length=64, unique=True)),
                ('type_entite', models.CharField(choices=[('patient', 'Patient'), ('consultation', 'Consultation'), ('ordonnance', 'Ordonnance'), ('facture', 'Facture'), ('paiement', 'Paiement')], max_length=20)),
                ('id_entite', models.CharField(max_length=50, verbose_name="Code de l'entité")),
                ('code_patient', models.CharField(blank=True, max_length=20)),
                ('code_centre', models.CharField(blank=True, max_length=20)),
                ('empreinte_hash', models.CharField(editable=False, max_length=64, verbose_name='Empreinte (SHA-256)')),
                ('tx_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='ID transaction')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('erreur_message', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ancrage blockchain',
                'ordering': ['-date_creation'],
            },
        ),
    ]
