# Generated by Django 5.1.6 on 2026-09-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancrageblockchain',
            name='type_entite',
            field=models.CharField(choices=[('patient', 'Patient'), ('consultation', 'Consultation'), ('ordonnance', 'Ordonnance'), ('facture', 'Facture'), ('paiement', 'Paiement'), ('echange_hprim', 'Échange HPRIM (laboratoire)'), ('analyse_laboratoire', 'Analyse laboratoire')], max_length=20),
        ),
    ]
