from django.urls import path, include
from . import views
from facturation.views import facturation_list as _facturation_list_view
from medecins.views import (
    medecin_dashboard as _medecin_dashboard_view,
    medecins_export_csv as _medecins_export_csv_view,
    medecin_supprimer as _medecin_supprimer_view,
)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('api/dashboard-stats/', views.dashboard_stats_json, name='dashboard_stats_json'),
    path('tableau-de-bord/', views.kpi_dashboard, name='kpi_dashboard'),
    path('tableau-de-bord/rapports/', views.rapports_hub, name='rapports_hub'),
    path('login/', views.login_view, name='login'),
    path('bienvenue/', views.intro, name='intro'),
    path('logout/', views.logout_view, name='logout'),
    path('compte/', views.mon_compte, name='mon_compte'),
    path('compte/couleur-accent/', views.accent_color_set, name='accent_color_set'),

    # URLs des modules
    path('patients/', include('patients.urls')),
    path('medecins/',                        views.medecins_list,          name='medecins_list'),
    path('medecins/dashboard/',              _medecin_dashboard_view,      name='medecin_dashboard'),
    path('medecins/export/csv/',             _medecins_export_csv_view,    name='medecins_export_csv'),
    path('medecins/nouveau/',                views.medecin_create,         name='medecin_create'),
    path('medecins/<int:pk>/',               views.medecin_detail,         name='medecin_detail'),
    path('medecins/<int:pk>/modifier/',      views.medecin_edit,           name='medecin_edit'),
    path('medecins/<int:pk>/supprimer/',     _medecin_supprimer_view,      name='medecin_supprimer'),

    # Spécialités
    path('medecins/config/specialites/',                    views.medecins_specialites,             name='medecins_specialites'),
    path('medecins/config/specialites/export/',             views.medecins_export_specialites,       name='medecins_export_specialites'),
    path('medecins/config/specialites/import/',             views.medecins_import_specialites,       name='medecins_import_specialites'),
    path('medecins/config/specialites/nouveau/',            views.medecins_specialite_create,        name='medecins_specialite_create'),
    path('medecins/config/specialites/bulk-delete/',        views.medecins_specialite_bulk_delete,   name='medecins_specialite_bulk_delete'),
    path('medecins/config/specialites/<int:pk>/',           views.medecins_specialite_detail,        name='medecins_specialite_detail'),
    path('medecins/config/specialites/<int:pk>/modifier/',  views.medecins_specialite_edit,          name='medecins_specialite_edit'),

    # Départements
    path('medecins/config/departements/',                    views.medecins_departements,             name='medecins_departements'),
    path('medecins/config/departements/export/',             views.medecins_export_departements,       name='medecins_export_departements'),
    path('medecins/config/departements/import/',             views.medecins_import_departements,       name='medecins_import_departements'),
    path('medecins/config/departements/nouveau/',            views.medecins_departement_create,        name='medecins_departement_create'),
    path('medecins/config/departements/bulk-delete/',        views.medecins_departement_bulk_delete,   name='medecins_departement_bulk_delete'),
    path('medecins/config/departements/<int:pk>/',           views.medecins_departement_detail,        name='medecins_departement_detail'),
    path('medecins/config/departements/<int:pk>/modifier/',  views.medecins_departement_edit,          name='medecins_departement_edit'),

    # Services
    path('medecins/config/services/',                    views.medecins_services,             name='medecins_services'),
    path('medecins/config/services/export/',             views.medecins_export_services,       name='medecins_export_services'),
    path('medecins/config/services/import/',             views.medecins_import_services,       name='medecins_import_services'),
    path('medecins/config/services/nouveau/',            views.medecins_service_create,        name='medecins_service_create'),
    path('medecins/config/services/bulk-delete/',        views.medecins_service_bulk_delete,   name='medecins_service_bulk_delete'),
    path('medecins/config/services/<int:pk>/',           views.medecins_service_detail,        name='medecins_service_detail'),
    path('medecins/config/services/<int:pk>/modifier/',  views.medecins_service_edit,          name='medecins_service_edit'),
    path('consultations/', views.consultations_list, name='consultations_list'),
    path('soins/', include('soins.urls')),
    path('services/', include('services.urls')),
    path('pharmacie/', views.pharmacie_list, name='pharmacie_list'),
    path('pharmacie/', include('pharmacie.urls')),
    path('laboratoire/', views.laboratoire_list, name='laboratoire_list'),
    path('hospitalisation/', include('hospitalisation.urls')),
    path('facture/nouveau/', views.facture_create, name='facture_create'),
    path('facturation/', _facturation_list_view, name='facturation_list'),
    path('facturation/', include('facturation.urls')),
    path('laboratoire/nouvelle/', views.laboratoire_create, name='laboratoire_create'),
    path('laboratoire/<int:pk>/', views.laboratoire_detail, name='laboratoire_detail'),
    path('caisse/', views.caisse_list, name='caisse_list'),
    path('employes/', include('employer.urls')),
    path('ordonnances/', include('ordonnance.urls')),
    path('conges/', include('conges.urls')),
    path('presence/', include('presence.urls')),
    path('stock/', include('stock.urls')),
    path('achats/', include('achats.urls')),
    path('post-note/', views.post_note, name='post_note'),
    path('planning/', include('planning.urls')),
    path('gynecologie/', views.gynecologie_list, name='gynecologie_list'),
    path('gynecologie/rdv/', views.gynecologie_rdv, name='gynecologie_rdv'),
    path('gynecologie/rdv/nouveau/', views.gynecologie_rdv_create, name='gynecologie_rdv_create'),
    path('gynecologie/rdv/bulk/', views.gynecologie_rdv_bulk, name='gynecologie_rdv_bulk'),
    path('gynecologie/rdv/<int:pk>/', views.gynecologie_rdv_detail, name='gynecologie_rdv_detail'),
    path('gynecologie/rdv/<int:pk>/statut/', views.gynecologie_rdv_set_statut, name='gynecologie_rdv_set_statut'),
    path('gynecologie/rdv/<int:pk>/consultation/', views.gynecologie_demarrer_consultation, name='gynecologie_demarrer_consultation'),
    path('gynecologie/naissances/', views.gynecologie_registre_naissance, name='gynecologie_naissances'),
    path('gynecologie/naissances/nouveau/', views.gynecologie_naissance_create, name='gynecologie_naissance_create'),
]
