from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('compte/', views.mon_compte, name='mon_compte'),

    # URLs des modules
    path('patients/', include('patients.urls')),
    path('medecins/',                        views.medecins_list,    name='medecins_list'),
    path('medecins/nouveau/',                views.medecin_create,   name='medecin_create'),
    path('medecins/<int:pk>/',               views.medecin_detail,   name='medecin_detail'),
    path('medecins/<int:pk>/modifier/',      views.medecin_edit,     name='medecin_edit'),
    path('consultations/', views.consultations_list, name='consultations_list'),
    path('soins/', include('soins.urls')),
    path('services/', include('services.urls')),
    path('pharmacie/', views.pharmacie_list, name='pharmacie_list'),
    path('pharmacie/', include('pharmacie.urls')),
    path('laboratoire/', views.laboratoire_list, name='laboratoire_list'),
    path('hospitalisation/', views.hospitalisation_list, name='hospitalisation_list'),
    path('hospitalisation/', include('hospitalisation.urls')),
    path('facture/nouveau/', views.facture_create, name='facture_create'),
    path('facturation/', views.facturation_list, name='facturation_list'),
    path('facturation/', include('facturation.urls')),
    path('laboratoire/nouvelle/', views.laboratoire_create, name='laboratoire_create'),
    path('laboratoire/<int:pk>/', views.laboratoire_detail, name='laboratoire_detail'),
    path('caisse/', views.caisse_list, name='caisse_list'),
    path('employes/', include('employer.urls')),
    path('ordonnances/', include('ordonnance.urls')),
    path('conges/', include('conges.urls')),
    path('presence/', include('presence.urls')),
    path('stock/', include('stock.urls')),
    path('post-note/', views.post_note, name='post_note'),
    path('rapports/', views.rapports_list, name='rapports_list'),
    path('planning/', include('planning.urls')),
    path('gynecologie/', views.gynecologie_list, name='gynecologie_list'),
    path('gynecologie/rdv/', views.gynecologie_rdv, name='gynecologie_rdv'),
    path('gynecologie/rdv/nouveau/', views.gynecologie_rdv_create, name='gynecologie_rdv_create'),
    path('gynecologie/rdv/bulk/', views.gynecologie_rdv_bulk, name='gynecologie_rdv_bulk'),
    path('gynecologie/rdv/calendrier/', views.gynecologie_rdv_calendrier, name='gynecologie_rdv_calendrier'),
    path('gynecologie/rdv/kanban/', views.gynecologie_rdv_kanban, name='gynecologie_rdv_kanban'),
    path('gynecologie/cpn/suivi/', views.gynecologie_cpn_suivi, name='gynecologie_cpn_suivi'),
    path('gynecologie/rdv/<int:pk>/', views.gynecologie_rdv_detail, name='gynecologie_rdv_detail'),
    path('gynecologie/rdv/<int:pk>/statut/', views.gynecologie_rdv_set_statut, name='gynecologie_rdv_set_statut'),
    path('gynecologie/rdv/<int:pk>/consultation/', views.gynecologie_demarrer_consultation, name='gynecologie_demarrer_consultation'),
    path('gynecologie/naissances/', views.gynecologie_registre_naissance, name='gynecologie_naissances'),
    path('gynecologie/naissances/nouveau/', views.gynecologie_naissance_create, name='gynecologie_naissance_create'),
]
