# Generated by Django 6.0.5 on 2026-05-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bureau / Service',
                'verbose_name_plural': 'Bureaux / Services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages', to='planning.bureau')),
            ],
            options={
                'verbose_name': 'Plage horaire',
                'verbose_name_plural': 'Plages horaires',
                'ordering': ['bureau__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='PlanningHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField(unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('publie', models.BooleanField(default=False)),
                ('signataire', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning hebdomadaire',
                'verbose_name_plural': 'Plannings hebdomadaires',
                'ordering': ['-semaine_debut'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('personnel', models.CharField(blank=True, max_length=200)),
                ('plage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.plagehoraire')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.planninghebdomadaire')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'unique_together': {('planning', 'plage', 'jour')},
            },
        ),
    ]
