# Generated by Django 6.0.5 on 2026-05-18 15:26

from django.db import migrations

BUREAUX = [
    ('B1',             1,  [('M', 1)]),
    ('B2',             2,  [('M', 1)]),
    ('B3',             3,  [('M', 1), ('S', 2)]),
    ('B4',             4,  [('M', 1), ('S', 2)]),
    ('BS',             5,  [('M', 1), ('S', 2)]),
    ('Gynéco',         6,  [('M', 1)]),
    ('Sage-fem',       7,  [('M', 1), ('12h-15h', 2)]),
    ('PCC',            8,  [('S', 1)]),
    ('Déprano',        9,  [('S', 1), ('Matin', 2)]),
    ('Projet Diabète', 10, [('M', 1)]),
    ('Toumbokro',      11, [('M', 1)]),
    ('Cardiologie',    12, [('15h-18h', 1)]),
]


def forwards(apps, schema_editor):
    Bureau = apps.get_model('planning', 'Bureau')
    PlageHoraire = apps.get_model('planning', 'PlageHoraire')
    for nom, ordre, plages in BUREAUX:
        b = Bureau.objects.create(nom=nom, ordre=ordre, actif=True)
        for code, plage_ordre in plages:
            PlageHoraire.objects.create(bureau=b, code=code, ordre=plage_ordre)


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
