# Generated by Django 6.0.5 on 2026-05-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_initial_bureaux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vu_le', models.DateTimeField(auto_now_add=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vus_par', to='planning.planninghebdomadaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings_vus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning vu',
                'unique_together': {('user', 'planning')},
            },
        ),
    ]
