# Generated by Django 6.0.5 on 2026-05-18 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planningvu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifie_le', models.DateTimeField(auto_now_add=True)),
                ('resume', models.TextField(blank=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_planning', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='planning.planninghebdomadaire')),
            ],
            options={
                'verbose_name': 'Modification',
                'ordering': ['-modifie_le'],
            },
        ),
    ]
