# Generated by Django 6.0.5 on 2026-05-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_planningmodification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signataire_defaut', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Configuration planning',
            },
        ),
    ]
