# Generated by Django 6.0.5 on 2026-05-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_planningconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='PlanningGabarit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gabarit de planning',
                'verbose_name_plural': 'Gabarits de planning',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GabaritAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('personnel', models.CharField(blank=True, max_length=200)),
                ('plage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.plagehoraire')),
                ('gabarit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.planninggabarit')),
            ],
            options={
                'verbose_name': 'Affectation gabarit',
                'unique_together': {('gabarit', 'plage', 'jour')},
            },
        ),
    ]
