# Generated by Django 6.0.5 on 2026-06-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_affectation_note_gabarits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LignePermanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('personnel', models.CharField(blank=True, max_length=300)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanences', to='planning.planninghebdomadaire')),
            ],
            options={
                'verbose_name': 'Ligne de permanence',
                'verbose_name_plural': 'Lignes de permanence',
                'unique_together': {('planning', 'jour')},
            },
        ),
    ]
