# Generated by Django 6.0.5 on 2026-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_lignepermanence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepermanence',
            name='personnel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
