# Generated by Django 5.2.15 on 2026-07-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_lignepermanence_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabaritaffectation',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
