# Generated by Django 5.2.16 on 2026-09-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_finalize_signataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planninggabarit',
            name='cree_par',
        ),
        migrations.DeleteModel(
            name='GabaritAffectation',
        ),
        migrations.DeleteModel(
            name='PlanningGabarit',
        ),
    ]
