# Generated by Django 5.2.16 on 2026-09-22 09:40

from django.db import migrations, models


def backfill_fonction(apps, schema_editor):
    """La fonction était jusqu'ici un réglage unique global : chaque médecin
    signataire existant en hérite comme valeur de départ, ajustable ensuite
    individuellement."""
    PlanningConfig = apps.get_model('planning', 'PlanningConfig')
    MedecinSignataire = apps.get_model('planning', 'MedecinSignataire')
    config = PlanningConfig.objects.first()
    if config and config.fonction_signataire:
        MedecinSignataire.objects.update(fonction=config.fonction_signataire)


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_remove_planninggabarit_cree_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinsignataire',
            name='fonction',
            field=models.CharField(blank=True, choices=[('directeur_medical', 'Directeur Médical'), ('directrice_medicale', 'Directrice Médicale'), ('directeur_medical_adjoint', 'Directeur Médical Adjoint'), ('directrice_medicale_adjointe', 'Directrice Médicale Adjointe')], default='', help_text='Affichée au-dessus du nom sur les plannings imprimés/publiés signés par ce médecin.', max_length=40, verbose_name='Fonction'),
        ),
        migrations.RunPython(backfill_fonction, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='planningconfig',
            name='fonction_signataire',
        ),
    ]
