# Generated by Django 5.2.16 on 2026-09-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_remove_planningconfig_fonction_signataire_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lignepermanence',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lignepermanence',
            name='planning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anciennes_permanences', to='planning.planninghebdomadaire'),
        ),
        migrations.CreateModel(
            name='PermanenceCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40, verbose_name='Créneau (ex. 18h-08h)')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanence_creneaux', to='planning.planninghebdomadaire')),
            ],
            options={
                'verbose_name': 'Créneau de permanence',
                'verbose_name_plural': 'Créneaux de permanence',
                'ordering': ['ordre', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='lignepermanence',
            name='creneau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.permanencecreneau'),
        ),
    ]
