# Generated by Django 5.2.16 on 2026-09-22 19:44

from django.db import migrations


def backfill(apps, schema_editor):
    """Chaque planning qui avait déjà des lignes de permanence (ancien modèle :
    1 case libre par jour, sans créneau) reçoit un unique créneau créé pour
    l'occasion, auquel on rattache ses lignes existantes."""
    LignePermanence = apps.get_model('planning', 'LignePermanence')
    PermanenceCreneau = apps.get_model('planning', 'PermanenceCreneau')

    plannings_ids = LignePermanence.objects.values_list('planning_id', flat=True).distinct()
    for planning_id in plannings_ids:
        creneau = PermanenceCreneau.objects.create(
            planning_id=planning_id, libelle='Permanence', ordre=0,
        )
        LignePermanence.objects.filter(planning_id=planning_id).update(creneau=creneau)


def unbackfill(apps, schema_editor):
    PermanenceCreneau = apps.get_model('planning', 'PermanenceCreneau')
    PermanenceCreneau.objects.filter(libelle='Permanence', ordre=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_alter_lignepermanence_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
