# Generated by Django 5.2.16 on 2026-09-22 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_backfill_permanence_creneaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignepermanence',
            name='planning',
        ),
        migrations.AlterField(
            model_name='lignepermanence',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.permanencecreneau'),
        ),
        migrations.AlterUniqueTogether(
            name='lignepermanence',
            unique_together={('creneau', 'jour')},
        ),
    ]
