# Generated by Django 5.2.16 on 2026-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_finaliser_permanence_creneau'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanenceCreneauModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40, verbose_name='Créneau (ex. 18h-08h)')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Modèle de créneau de permanence',
                'verbose_name_plural': 'Modèles de créneaux de permanence',
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
