# Generated by Django 5.2.16 on 2026-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_permanencecreneaumodele'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepermanence',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
