# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_lignepermanence_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planninghebdomadaire',
            options={'ordering': ['-semaine_debut'], 'permissions': [('can_gerer_planning', 'Peut gérer le planning'), ('can_supprimer_planning_publie', 'Peut supprimer un planning publié')], 'verbose_name': 'Planning hebdomadaire', 'verbose_name_plural': 'Plannings hebdomadaires'},
        ),
    ]
