# Generated by Django 6.0.4 on 2026-04-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=500)),
                ('categorie', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Diagnostic CIM',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('anamnese', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.rendezvous')),
            ],
            options={
                'verbose_name': 'Consultation',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tension_systolique', models.IntegerField(blank=True, null=True)),
                ('tension_diastolique', models.IntegerField(blank=True, null=True)),
                ('pouls', models.IntegerField(blank=True, null=True)),
                ('saturation_oxygene', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glycemie', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_libre', models.CharField(blank=True, max_length=500)),
                ('type_diagnostic', models.CharField(choices=[('principal', 'Principal'), ('associe', 'Associé'), ('differentiel', 'Différentiel')], default='principal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='consultations.consultation')),
                ('cim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.diagnosticcim')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('laboratoire', 'Laboratoire'), ('imagerie', 'Imagerie'), ('autre', 'Autre')], max_length=20)),
                ('libelle', models.CharField(max_length=300)),
                ('urgence', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('en_cours', 'En cours'), ('resultat', 'Résultat disponible'), ('valide', 'Validé')], default='demande', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_demandes', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Examen demandé',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('emise', 'Émise'), ('delivree', 'Délivrée'), ('partielle', 'Partielle'), ('expiree', 'Expirée')], default='emise', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('type_ordonnance', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='interne', max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Ordonnance',
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_libre', models.CharField(blank=True, max_length=200)),
                ('posologie', models.CharField(max_length=500)),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('quantite', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='consultations.ordonnance')),
            ],
        ),
    ]
