# Generated by Django 6.0.5 on 2026-05-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='consultation',
        ),
        migrations.DeleteModel(
            name='LigneOrdonnance',
        ),
        migrations.DeleteModel(
            name='Ordonnance',
        ),
    ]
