# Generated by Django 5.1.6 on 2026-06-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_constante_new_fields'),
        ('patients', '0017_merge_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_directes', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultations.consultation'),
        ),
    ]
