# Generated by Django 6.0.7 on 2026-09-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_ordonnance_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneordonnance',
            name='medicament',
        ),
    ]
