# Generated by Django 6.0.7 on 2026-09-25 17:36

import consultations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_remove_ligneordonnance_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='date_expiration',
            field=models.DateField(blank=True, default=consultations.models.date_expiration_par_defaut, null=True),
        ),
    ]
