# Generated by Django 6.0.5 on 2026-05-20 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0003_rename_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'db_table': 'employes_fonction',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'employes_grade',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('description', models.CharField(max_length=100, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'employes_jourferie',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('droit_au_conge', models.BooleanField(default=True, help_text='Décocher pour les vacataires, prestataires et autres contrats sans droit au congé.', verbose_name='Droit au congé')),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrat',
                'db_table': 'employes_typecontrat',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=15, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('nationalite', models.CharField(blank=True, default='Ivoirienne', max_length=50)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20)),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/photos/')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('date_embauche', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('quitte', 'Quitté')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_rh', to='utilisateur.departement')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.fonction')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.grade')),
                ('type_contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.typecontrat')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employes_employe',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('diplome', 'Diplôme / Attestation'), ('contrat', 'Contrat de travail'), ('certificat', 'Certificat médical'), ('photo', "Photo d'identité"), ('autre', 'Autre document')], default='autre', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='employes/documents/%Y/')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'employes_documentemploye',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('exceptionnel', 'Congé exceptionnel'), ('mariage_employe', 'Mariage (employé)'), ('mariage_enfant', 'Mariage (enfant)'), ('deces_conjoint', 'Décès conjoint'), ('deces_enfant', 'Décès enfant'), ('deces_parent', 'Décès parent/beau-parent'), ('deces_frere_soeur', 'Décès frère/sœur'), ('naissance_enfant', 'Naissance enfant (père)'), ('sans_solde', 'Congé sans solde')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('valide_service', 'Validé par le service'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='demande', max_length=20)),
                ('nb_jours_ouvres', models.PositiveSmallIntegerField(default=0, help_text='Jours ouvrés décomptés du solde')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rh', models.TextField(blank=True)),
                ('date_validation_service', models.DateTimeField(blank=True, null=True)),
                ('chef_service_commentaire', models.TextField(blank=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to=settings.AUTH_USER_MODEL)),
                ('conge_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragments', to='employer.conge', verbose_name='Congé parent (fractionné)')),
                ('valide_par_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides_service', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'db_table': 'employes_conge',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('soumis', 'Demande soumise'), ('valide_service', 'Validé par le service'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('mis_en_cours', 'Mis en cours'), ('termine', 'Terminé'), ('prolonge', 'Prolongé'), ('absence_injustifiee', 'Absence non justifiée')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='employer.conge')),
                ('fait_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique congé',
                'verbose_name_plural': 'Historique congés',
                'db_table': 'employes_historiqueconge',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_changement', models.CharField(choices=[('creation', 'Création'), ('statut', 'Changement de statut'), ('salaire', 'Changement de salaire'), ('service', 'Changement de service'), ('contrat', 'Renouvellement de contrat'), ('autre', 'Modification')], max_length=20)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=300)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='employer.employe')),
                ('fait_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique employé',
                'verbose_name_plural': 'Historique employés',
                'db_table': 'employes_historiqueemploye',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InfoSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100)),
                ('valeur', models.TextField()),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_supp', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Information supplémentaire',
                'verbose_name_plural': 'Informations supplémentaires',
                'db_table': 'employes_infosupplementaire',
                'ordering': ['ordre', 'cle'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('nouvelle_demande', 'Nouvelle demande'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('valide_service', 'Validé service'), ('annule', 'Annulé')], max_length=20)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employer.conge')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifs_conge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification congé',
                'verbose_name_plural': 'Notifications congés',
                'db_table': 'employes_notificationconge',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='AlerteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echeance', models.CharField(choices=[('2_mois', '2 mois'), ('1_mois', '1 mois')], max_length=10)),
                ('date_expiration', models.DateField()),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='employer.documentemploye')),
            ],
            options={
                'verbose_name': 'Alerte document',
                'verbose_name_plural': 'Alertes documents',
                'db_table': 'employes_alertedocument',
                'ordering': ['date_expiration'],
                'unique_together': {('document', 'echeance')},
            },
        ),
        migrations.CreateModel(
            name='AlerteContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echeance', models.CharField(choices=[('2_mois', '2 mois'), ('1_mois', '1 mois')], max_length=10)),
                ('date_fin_contrat', models.DateField()),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_contrat', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Alerte contrat',
                'verbose_name_plural': 'Alertes contrat',
                'db_table': 'employes_alertecontrat',
                'ordering': ['-cree_le'],
                'unique_together': {('employe', 'echeance')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee_matin', models.TimeField(blank=True, null=True, verbose_name='Arrivée matin')),
                ('heure_depart_matin', models.TimeField(blank=True, null=True, verbose_name='Départ matin')),
                ('heure_arrivee_soir', models.TimeField(blank=True, null=True, verbose_name='Arrivée soir')),
                ('heure_depart_soir', models.TimeField(blank=True, null=True, verbose_name='Départ soir')),
                ('present', models.BooleanField(default=True)),
                ('motif_absence', models.CharField(blank=True, max_length=200)),
                ('remarques', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Présence',
                'db_table': 'employes_presence',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('quota', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('jours_pris', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('jours_reporter', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congé',
                'db_table': 'employes_soldeconge',
                'ordering': ['-annee'],
                'unique_together': {('employe', 'annee')},
            },
        ),
    ]
