# Generated by Django 6.0.5 on 2026-05-28 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='service_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.articleservice', verbose_name='Service de consultation'),
        ),
        migrations.AddField(
            model_name='employe',
            name='service_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.articleservice', verbose_name='Service de suivi'),
        ),
        migrations.AddField(
            model_name='employe',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employes_rh', to='employer.departement'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentemploye',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='medecin_interne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employer.employe', verbose_name='Médecin interne lié'),
        ),
        migrations.AddField(
            model_name='diplomepersonnel',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes_personnels', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='conge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='alertecontrat',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_contrat', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='docteurreferentetiquette',
            name='etiquette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.etiquette'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, related_name='+', through='employer.DocteurReferentEtiquette', to='employer.etiquette', verbose_name='Étiquettes'),
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.fonction'),
        ),
        migrations.AddField(
            model_name='employe',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.grade'),
        ),
        migrations.AddField(
            model_name='historiqueconge',
            name='conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='employer.conge'),
        ),
        migrations.AddField(
            model_name='historiqueconge',
            name='fait_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueemploye',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='historiqueemploye',
            name='fait_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infosupplementaire',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_supp', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='notificationconge',
            name='conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employer.conge'),
        ),
        migrations.AddField(
            model_name='notificationconge',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifs_conge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presence',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='soldeconge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='employer.employe'),
        ),
        migrations.AddField(
            model_name='employe',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_medecins', to='employer.specialite'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employer.specialite', verbose_name='Spécialité'),
        ),
        migrations.AddField(
            model_name='employe',
            name='type_contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.typecontrat'),
        ),
        migrations.AlterUniqueTogether(
            name='alertedocument',
            unique_together={('document', 'echeance')},
        ),
        migrations.AlterUniqueTogether(
            name='alertecontrat',
            unique_together={('employe', 'echeance')},
        ),
        migrations.AlterUniqueTogether(
            name='docteurreferentetiquette',
            unique_together={('docteurreferent', 'etiquette')},
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('employe', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='soldeconge',
            unique_together={('employe', 'annee')},
        ),
    ]
