# Generated by Django 6.0.5 on 2026-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('utilisateur', '0003_rename_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='service',
        ),
        migrations.AddField(
            model_name='employe',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employes_rh', to='utilisateur.departement'),
        ),
    ]
