# Generated by Django 6.0.5 on 2026-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_service_fk_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='numero_ordre',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="N° d'ordre"),
        ),
    ]
