# Generated by Django 6.0.5 on 2026-05-27 14:34
# Edited: SeparateDatabaseAndState pour les modèles déplacés de utilisateur → employer

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_add_numero_ordre'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [

        # ── 1. Modèles déplacés depuis utilisateur (tables déjà existantes) ────────
        #       state_operations uniquement : pas de CREATE TABLE en base
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Departement',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nom', models.CharField(max_length=100)),
                        ('code', models.CharField(max_length=20, unique=True)),
                        ('description', models.TextField(blank=True)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'verbose_name': 'Département',
                        'verbose_name_plural': 'Départements',
                        'db_table': 'utilisateur_departement',
                        'ordering': ['nom'],
                    },
                ),
                migrations.CreateModel(
                    name='Diplome',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('titre', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                    ],
                    options={
                        'verbose_name': 'Diplôme',
                        'verbose_name_plural': 'Diplômes',
                        'db_table': 'utilisateur_diplome',
                        'ordering': ['titre'],
                    },
                ),
                migrations.CreateModel(
                    name='Etiquette',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nom', models.CharField(max_length=50, unique=True)),
                        ('couleur', models.CharField(blank=True, default='#0ea5e9', max_length=7)),
                    ],
                    options={
                        'verbose_name': 'Étiquette',
                        'verbose_name_plural': 'Étiquettes',
                        'db_table': 'utilisateur_etiquette',
                        'ordering': ['nom'],
                    },
                ),
                migrations.CreateModel(
                    name='Specialite',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nom', models.CharField(max_length=100)),
                        ('code', models.CharField(max_length=20, unique=True)),
                        ('description', models.TextField(blank=True)),
                    ],
                    options={
                        'verbose_name': 'Spécialité',
                        'db_table': 'utilisateur_specialite',
                        'ordering': ['nom'],
                    },
                ),
            ],
            database_operations=[],
        ),

        # ── 2. Nouveaux champs sur Employe (ajouts réels en base) ─────────────────
        migrations.AddField(
            model_name='employe',
            name='chirurgien_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='duree_consultation',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Durée consultation (min)'),
        ),
        migrations.AddField(
            model_name='employe',
            name='employe_societe',
            field=models.BooleanField(default=True, verbose_name='Employé de la société'),
        ),
        migrations.AddField(
            model_name='employe',
            name='est_medecin',
            field=models.BooleanField(default=False, verbose_name='Est Médecin/Docteur'),
        ),
        migrations.AddField(
            model_name='employe',
            name='est_referent',
            field=models.BooleanField(default=False, verbose_name='Est Médecin Référent'),
        ),
        migrations.AddField(
            model_name='employe',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='employe',
            name='langue',
            field=models.CharField(blank=True, default='Français', max_length=50, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='employe',
            name='notes_internes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='employe',
            name='ordre_medecin',
            field=models.CharField(blank=True, max_length=50, verbose_name="N° d'ordre médecin"),
        ),
        migrations.AddField(
            model_name='employe',
            name='service_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.articleservice', verbose_name='Service de consultation'),
        ),
        migrations.AddField(
            model_name='employe',
            name='service_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.articleservice', verbose_name='Service de suivi'),
        ),
        migrations.AddField(
            model_name='employe',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='employes/signatures/', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='employe',
            name='stagiaire_societe',
            field=models.BooleanField(default=False, verbose_name='Stagiaire de la société'),
        ),
        migrations.AddField(
            model_name='employe',
            name='taux_honoraire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employe',
            name='titre',
            field=models.CharField(blank=True, choices=[('', '—'), ('dr', 'Dr'), ('pr', 'Pr'), ('m', 'M.'), ('mme', 'Mme'), ('prof', 'Prof.')], max_length=10, verbose_name='Titre'),
        ),

        # ── 3. AlterField sur Employe ─────────────────────────────────────────────
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.TextField(blank=True, verbose_name="Lieu d'habitation"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenoms',
            field=models.CharField(blank=True, max_length=200),
        ),

        # ── 4. Champ M2M services : cible change de utilisateur.Departement → employer.Departement
        #       (même table physique) — state only, pas de recréation de table
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='employe',
                    name='services',
                    field=models.ManyToManyField(blank=True, related_name='employes_rh', to='employer.departement'),
                ),
            ],
            database_operations=[],
        ),

        # ── 5. FK diplome sur Employe (nouvelle colonne réelle) ───────────────────
        migrations.AddField(
            model_name='employe',
            name='diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employer.diplome', verbose_name="Niveau d'éducation"),
        ),

        # ── 6. DiplomePersonnel (nouvelle table réelle) ───────────────────────────
        migrations.CreateModel(
            name='DiplomePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du diplôme')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes_personnels', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Diplôme personnel',
                'verbose_name_plural': 'Diplômes personnels',
                'db_table': 'employes_diplomepersonnel',
                'ordering': ['-annee', 'titre'],
            },
        ),

        # ── 7. DocteurReferent, ContactAdresse, DocteurReferentEtiquette
        #       (tables déjà existantes dans utilisateur) — state only
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DocteurReferent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(blank=True, max_length=20, unique=True)),
                        ('type_contact', models.CharField(choices=[('individu', 'Individu'), ('societe', 'Société')], default='individu', max_length=10, verbose_name='Type')),
                        ('titre', models.CharField(blank=True, choices=[('', '—'), ('dr', 'Dr'), ('pr', 'Pr'), ('m', 'M.'), ('mme', 'Mme'), ('prof', 'Prof.')], max_length=10, verbose_name='Titre')),
                        ('nom', models.CharField(max_length=100)),
                        ('prenoms', models.CharField(blank=True, max_length=200, verbose_name='Prénom(s)')),
                        ('genre', models.CharField(blank=True, choices=[('', '—'), ('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Genre')),
                        ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/referents/')),
                        ('poste_occupe', models.CharField(blank=True, max_length=100, verbose_name='Poste Occupé')),
                        ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                        ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                        ('mobile', models.CharField(blank=True, max_length=20)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('site_web', models.URLField(blank=True, verbose_name='Site Web')),
                        ('langue', models.CharField(blank=True, default='Français', max_length=50, verbose_name='Langue')),
                        ('adresse', models.TextField(blank=True)),
                        ('tva', models.CharField(blank=True, max_length=50, verbose_name='TVA')),
                        ('est_referent', models.BooleanField(default=True, verbose_name='Est le médecin référent')),
                        ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                        ('compte_client', models.CharField(blank=True, max_length=100, verbose_name='Compte client')),
                        ('compte_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Compte fournisseur')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                        ('actif', models.BooleanField(default=True)),
                        ('date_creation', models.DateTimeField(auto_now_add=True)),
                        ('medecin_interne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employer.employe', verbose_name='Médecin interne lié')),
                    ],
                    options={
                        'verbose_name': 'Docteur Référent',
                        'verbose_name_plural': 'Docteurs Référents',
                        'db_table': 'utilisateur_docteurreferent',
                        'ordering': ['nom'],
                    },
                ),
                migrations.CreateModel(
                    name='ContactAdresse',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('type_adresse', models.CharField(choices=[('contact', 'Contact'), ('facturation', 'Adresse de facturation'), ('livraison', 'Adresse de livraison'), ('autre', 'Autre adresse')], default='contact', max_length=20, verbose_name='Type')),
                        ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                        ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                        ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                        ('referent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_adresses', to='employer.docteurreferent')),
                    ],
                    options={
                        'verbose_name': 'Contact / Adresse',
                        'verbose_name_plural': 'Contacts / Adresses',
                        'db_table': 'utilisateur_contactadresse',
                    },
                ),
                migrations.CreateModel(
                    name='DocteurReferentEtiquette',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('docteurreferent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.docteurreferent')),
                        ('etiquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.etiquette')),
                    ],
                    options={
                        'db_table': 'utilisateur_docteurreferent_etiquettes',
                        'unique_together': {('docteurreferent', 'etiquette')},
                    },
                ),
                migrations.AddField(
                    model_name='docteurreferent',
                    name='etiquettes',
                    field=models.ManyToManyField(blank=True, related_name='+', through='employer.DocteurReferentEtiquette', to='employer.etiquette', verbose_name='Étiquettes'),
                ),
                migrations.AddField(
                    model_name='docteurreferent',
                    name='specialite',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employer.specialite', verbose_name='Spécialité'),
                ),
            ],
            database_operations=[],
        ),

        # ── 8. FK specialite sur Employe (nouvelle colonne réelle) ────────────────
        migrations.AddField(
            model_name='employe',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_medecins', to='employer.specialite'),
        ),
    ]
