# Generated by Django 6.0.5 on 2026-05-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_departement_diplome_etiquette_specialite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='employe_societe',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='stagiaire_societe',
        ),
    ]
