# Generated by Django 6.0.5 on 2026-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_conge_jours_ouvres_soldeconge'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecontrat',
            name='droit_au_conge',
            field=models.BooleanField(default=True, help_text='Décocher pour les vacataires, prestataires et autres contrats sans droit au congé.', verbose_name='Droit au congé'),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
