# Generated by Django 6.0.5 on 2026-05-19 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_conge_validation_notifs_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='conge_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragments', to='employer.conge', verbose_name='Congé parent (fractionné)'),
        ),
    ]
