# Generated by Django 6.0.5 on 2026-05-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_conge_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='heure_depart',
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_arrivee_matin',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrivée matin'),
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_arrivee_soir',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrivée soir'),
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_depart_matin',
            field=models.TimeField(blank=True, null=True, verbose_name='Départ matin'),
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_depart_soir',
            field=models.TimeField(blank=True, null=True, verbose_name='Départ soir'),
        ),
        migrations.AddField(
            model_name='presence',
            name='remarques',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='historiqueconge',
            name='action',
            field=models.CharField(choices=[('soumis', 'Demande soumise'), ('valide_service', 'Validé par le service'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('mis_en_cours', 'Mis en cours'), ('termine', 'Terminé'), ('prolonge', 'Prolongé'), ('absence_injustifiee', 'Absence non justifiée')], max_length=20),
        ),
    ]
