# Generated by Django 6.0.5 on 2026-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_presence_4_time_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('description', models.CharField(max_length=100, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'ressources_humaines_jourferie',
                'ordering': ['date'],
            },
        ),
    ]
