# Generated by Django 6.0.5 on 2026-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_fonction_gest_donnees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fonction',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Fonction', 'verbose_name_plural': 'Fonctions'},
        ),
        migrations.AddField(
            model_name='fonction',
            name='categorie',
            field=models.CharField(blank=True, choices=[('direction', 'Direction & Administration'), ('medical', 'Corps Médical'), ('paramedical', 'Paramédical'), ('communautaire', 'Communautaire'), ('support', 'Support')], default='support', max_length=20),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demandé'), ('valide_service', 'Validé par le service'), ('approuve', 'À venir'), ('refuse', 'Annulé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='demande', max_length=20),
        ),
    ]
