# Generated by Django 6.0.5 on 2026-06-02 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_fonction_categorie_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='modifie_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='presence',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
