# Generated by Django 6.0.5 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0020_presence_modifie_le_presence_modifie_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='est_permanence',
            field=models.BooleanField(default=False, help_text='Cocher si cet employé travaille en horaire continu 8h00–15h00.', verbose_name='Horaire de permanence (8h–15h)'),
        ),
    ]
