# Generated by Django 6.0.5 on 2026-06-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0021_employe_est_permanence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='est_permanence',
        ),
        migrations.AddField(
            model_name='presence',
            name='permanence',
            field=models.BooleanField(default=False, verbose_name='Permanence 8h–15h'),
        ),
    ]
