# Generated by Django 6.0.5 on 2026-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0022_remove_employe_est_permanence_presence_permanence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='biometric_id',
            field=models.CharField(blank=True, help_text="Identifiant renseigné par le lecteur d'empreinte digitale.", max_length=100, verbose_name='Identifiant biométrique'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('approuve', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('refuse', 'Annulé'), ('demande', 'Demandé'), ('valide_service', 'Validé service')], default='approuve', max_length=20),
        ),
    ]
