# Generated by Django 6.0.5 on 2026-06-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_employe_biometric_id_alter_conge_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialBiometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True, verbose_name='ID credential (base64url)')),
                ('public_key', models.TextField(verbose_name='Clé publique (base64url)')),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Appareil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials_bio', to='employer.employe')),
            ],
            options={
                'verbose_name': 'Credential biométrique',
                'verbose_name_plural': 'Credentials biométriques',
                'ordering': ['-created_at'],
            },
        ),
    ]
