# Generated by Django 6.0.5 on 2026-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0024_credential_biometrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='am_in_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='am_out_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='pm_in_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='pm_out_locked',
            field=models.BooleanField(default=False),
        ),
    ]
