# Generated by Django 5.2.15 on 2026-07-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0025_presence_locked_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_depart',
            field=models.DateField(blank=True, help_text='Renseignée automatiquement lors du passage au statut « quitté ».', null=True, verbose_name='Date de départ'),
        ),
    ]
