# Generated by Django 5.2.15 on 2026-07-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0027_backfill_date_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecontrat',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
