# Generated by Django 5.2.15 on 2026-07-16 15:33

import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0029_nationalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=employer.models._type_conge_choices, max_length=20),
        ),
    ]
