# Generated by Django 5.2.15 on 2026-07-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0030_alter_conge_type_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='deduit_du_solde',
            field=models.BooleanField(default=True, help_text='Pré-rempli selon le type de congé, modifiable au cas par cas pour cette demande précise.', verbose_name='Déduire du solde de congé'),
        ),
    ]
