# Generated by Django 5.2.15 on 2026-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0032_backfill_deduit_du_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldeconge',
            name='report_effectue',
            field=models.BooleanField(default=False, help_text='Coché automatiquement une fois le solde restant de cette année reporté sur N+1, pour éviter un double report.', verbose_name="Reporté vers l'année suivante"),
        ),
    ]
