# Generated by Django 5.2.15 on 2026-07-20 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0033_soldeconge_report_effectue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['statut', 'date_debut'], name='ressources__statut_7c3ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['statut', 'date_fin'], name='ressources__statut_ee211a_idx'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['type_conge'], name='ressources__type_co_1eb010_idx'),
        ),
    ]
