# Generated by Django 5.2.15 on 2026-07-23 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0034_conge_indexes'),
        ('medecins', '0016_alter_medecin_ordre_medecin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['biometric_id'], name='ressources__biometr_19108a_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['statut'], name='ressources__statut_36445d_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date'], name='ressources__date_eb9ab7_idx'),
        ),
    ]
