# Generated by Django 5.2.15 on 2026-07-25 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0035_presence_employe_indexes'),
        ('medecins', '0017_merge_20260724_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='code_ancien_badge',
            field=models.CharField(blank=True, help_text="Clé normalisée (nom complet + titre, majuscules sans accents) extraite de la vCard de l'ancienne carte de l'employé — renseignée via « Lier un ancien badge ».", max_length=255, verbose_name='Ancien badge (nom + titre normalisés)'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['code_ancien_badge'], name='ressources__code_an_10140c_idx'),
        ),
    ]
