# Generated by Django 5.2.16 on 2026-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0036_code_ancien_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentemploye',
            name='type_document',
            field=models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('diplome', 'Diplôme / Attestation'), ('contrat', 'Contrat de travail'), ('certificat', 'Certificat médical'), ('acte_naissance', 'Acte de naissance'), ('photo', "Photo d'identité"), ('autre', 'Autre document')], default='autre', max_length=20),
        ),
    ]
