# Generated by Django 5.2.16 on 2026-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0037_alter_documentemploye_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldeconge',
            name='jours_deja_pris_avant_saisie',
            field=models.DecimalField(decimal_places=1, default=0, help_text="Congé pris par l'employé avant son enregistrement dans l'application (non traçable via un congé enregistré) — déduit manuellement du solde.", max_digits=5, verbose_name='Jours déjà pris avant saisie'),
        ),
    ]
