# Generated by Django 5.2.16 on 2026-09-22 20:14

from django.db import migrations

ANNEES = [2026, 2027]


def seed(apps, schema_editor):
    from conges.utils import jours_feries_labels
    JourFerie = apps.get_model('employer', 'JourFerie')
    for annee in ANNEES:
        for jour, description in jours_feries_labels(annee).items():
            JourFerie.objects.get_or_create(date=jour, defaults={'description': description})


def unseed(apps, schema_editor):
    from conges.utils import jours_feries_labels
    JourFerie = apps.get_model('employer', 'JourFerie')
    dates = set()
    for annee in ANNEES:
        dates.update(jours_feries_labels(annee).keys())
    JourFerie.objects.filter(date__in=dates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0038_soldeconge_jours_deja_pris_avant_saisie'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
