# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0039_seed_jours_feries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ['-date_demande'], 'permissions': [('can_gerer_conges', 'Peut gérer les congés')], 'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['nom', 'prenoms'], 'permissions': [('can_gerer_personnel', 'Peut gérer le personnel')], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
    ]
