# Generated by Django 6.0.6 on 2026-07-07 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, verbose_name='Rapport')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du rapport')),
                ('periode_debut', models.DateField(verbose_name='Période — début')),
                ('periode_fin', models.DateField(verbose_name='Période — fin')),
                ('format_fichier', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('nb_lignes', models.PositiveIntegerField(default=0)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/%Y/%m/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport généré',
                'verbose_name_plural': 'Historique des rapports',
                'ordering': ['-date_generation'],
            },
        ),
    ]
