# Generated by Django 6.0.6 on 2026-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquerapport',
            name='periode_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Période — début'),
        ),
    ]
