# Generated by Django 6.0.7 on 2026-10-03 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_alter_historiquerapport_periode_debut'),
        ('services', '0019_remove_articleservice_avertissement_grossesse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocFicheSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Bloc de la fiche de soins',
                'verbose_name_plural': 'Blocs de la fiche de soins',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ColonneFicheSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Nombre', max_length=60, verbose_name='Titre')),
                ('type_valeur', models.CharField(choices=[('nombre', 'Nombre')], default='nombre', max_length=20, verbose_name='Type de valeur')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonnes', to='rapports.blocfichesoins', verbose_name='Bloc')),
            ],
            options={
                'verbose_name': 'Colonne de la fiche de soins',
                'verbose_name_plural': 'Colonnes de la fiche de soins',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationFicheSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Configuration par défaut')),
                ('est_active', models.BooleanField(default=False, verbose_name='Active pour ce compte')),
                ('partagee', models.BooleanField(default=False, verbose_name='Proposée aux autres utilisateurs')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations_fiche_soins', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Configuration de la fiche de soins',
                'verbose_name_plural': 'Configurations de la fiche de soins',
                'ordering': ['-est_defaut', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='blocfichesoins',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='rapports.configurationfichesoins', verbose_name='Configuration'),
        ),
        migrations.CreateModel(
            name='LigneFicheSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('source', models.CharField(choices=[('articles', 'Prestations cochées'), ('mo_avec_soin', 'Mises en observation ayant reçu un soin payé'), ('mo_sans_soin', 'Mises en observation payées sans aucun soin'), ('manuelle', 'Case à remplir à la main')], default='articles', max_length=20, verbose_name='Ce que compte la ligne')),
                ('origines', models.CharField(choices=[('procedure', 'Module Soins'), ('mo', 'Mise en observation'), ('les_deux', 'Les deux')], default='procedure', max_length=20, verbose_name='Où chercher les prestations')),
                ('articles', models.ManyToManyField(blank=True, related_name='lignes_fiche_soins', to='services.articleservice', verbose_name='Prestations')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='rapports.blocfichesoins', verbose_name='Bloc')),
            ],
            options={
                'verbose_name': 'Ligne de la fiche de soins',
                'verbose_name_plural': 'Lignes de la fiche de soins',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
