# Generated by Django 6.0.5 on 2026-06-02 19:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0022_remove_employe_est_permanence_presence_permanence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPermanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_du', models.DateField(unique=True, verbose_name='Semaine du (lundi)')),
                ('heure_debut', models.TimeField(default=datetime.time(8, 0), verbose_name="Heure d'arrivée")),
                ('heure_fin', models.TimeField(default=datetime.time(15, 0), verbose_name='Heure de départ')),
                ('cree_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning permanence',
                'verbose_name_plural': 'Plannings permanence',
                'ordering': ['-semaine_du'],
            },
        ),
        migrations.CreateModel(
            name='AffectationPermanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de permanence')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanences', to='employer.employe')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='presence.planningpermanence')),
            ],
            options={
                'verbose_name': 'Affectation permanence',
                'verbose_name_plural': 'Affectations permanence',
                'ordering': ['date', 'employe__nom'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
