# Generated by Django 5.2.15 on 2026-07-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningpermanence',
            name='type_permanence',
            field=models.CharField(choices=[('personnel', 'Personnel'), ('medecins', 'Médecins')], default='personnel', max_length=20),
        ),
        migrations.AlterField(
            model_name='planningpermanence',
            name='semaine_du',
            field=models.DateField(verbose_name='Semaine du (lundi)'),
        ),
        migrations.AlterUniqueTogether(
            name='planningpermanence',
            unique_together={('semaine_du', 'type_permanence')},
        ),
    ]
