# Generated by Django 5.2.15 on 2026-07-23 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_planning_permanence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreVerrou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Jour verrouillé')),
                ('verrouille_le', models.DateTimeField(auto_now_add=True)),
                ('verrouille_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verrou registre',
                'verbose_name_plural': 'Verrous registre',
                'ordering': ['-date'],
            },
        ),
    ]
