# Generated by Django 5.2.15 on 2026-07-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_registre_verrou'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationBiometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False, help_text='Tant que désactivé, le kiosque affiche le message générique « lecteur non configuré ».', verbose_name="Lecteur d'empreinte activé")),
                ('url_agent', models.URLField(blank=True, help_text='Fournie par le SDK du lecteur une fois installé sur le poste du kiosque, ex. http://127.0.0.1:8734/scan', verbose_name='URL du service local du lecteur')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration biométrique',
                'verbose_name_plural': 'Configuration biométrique',
            },
        ),
    ]
