# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_configurationbiometrique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registreverrou',
            options={'ordering': ['-date'], 'permissions': [('can_rouvrir_registre', 'Peut rouvrir un registre verrouillé')], 'verbose_name': 'Verrou registre', 'verbose_name_plural': 'Verrous registre'},
        ),
    ]
