# Generated by Django 6.0.4 on 2026-04-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('type_chambre', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('vip', 'VIP'), ('soins_intensifs', 'Soins intensifs'), ('observation', 'Observation')], default='simple', max_length=20)),
                ('capacite', models.IntegerField(default=1)),
                ('prix_jour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.service')),
            ],
            options={
                'verbose_name': 'Chambre',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_admission', models.DateTimeField(auto_now_add=True)),
                ('date_sortie_prevue', models.DateField(blank=True, null=True)),
                ('date_sortie_effective', models.DateTimeField(blank=True, null=True)),
                ('motif_admission', models.TextField()),
                ('diagnostic_admission', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('admis', 'Admis'), ('en_soins', 'En soins'), ('sortie_prevue', 'Sortie prévue'), ('sorti', 'Sorti'), ('transfere', 'Transféré'), ('decede', 'Décédé')], default='admis', max_length=20)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_payee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.chambre')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'ordering': ['-date_admission'],
            },
        ),
        migrations.CreateModel(
            name='FicheVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('evolution', models.TextField(blank=True)),
                ('prescriptions', models.TextField(blank=True)),
                ('constantes', models.JSONField(blank=True, default=dict)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_visite', to='hospitalisation.hospitalisation')),
            ],
            options={
                'verbose_name': 'Fiche de visite',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoleHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocoles', to='hospitalisation.hospitalisation')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin')),
            ],
            options={
                'verbose_name': 'Protocole hospitalisation',
            },
        ),
    ]
