# Generated by Django 6.0.5 on 2026-05-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0001_initial'),
        ('services', '0007_typeservice_articleservice_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.articleservice', verbose_name='service'),
        ),
    ]
