# Generated by Django 6.0.5 on 2026-05-20 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        ('patients', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='fichevisite',
            name='hospitalisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_visite', to='hospitalisation.hospitalisation'),
        ),
        migrations.AddField(
            model_name='protocolehospitalisation',
            name='hospitalisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocoles', to='hospitalisation.hospitalisation'),
        ),
        migrations.AddField(
            model_name='protocolehospitalisation',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.employe'),
        ),
    ]
