# Generated by Django 6.0.5 on 2026-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_departement_diplome_etiquette_specialite_and_more'),
        ('hospitalisation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichevisite',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employe'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='medecin_traitant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employe'),
        ),
        migrations.AlterField(
            model_name='protocolehospitalisation',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employe'),
        ),
    ]
