# Generated by Django 6.0.5 on 2026-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0005_registredeces'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreHospitalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Centre hospitalier',
                'verbose_name_plural': 'Centres hospitaliers',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='chambre',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='salle_no',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Salle No.'),
        ),
    ]
