# Generated by Django 6.0.5 on 2026-06-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0006_add_centre_hospitalier'),
        ('patients', '0015_add_registres_cpn_accouchement_postnatale_curatif'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModèlePlanSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du plan de soins')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité')),
                ('regime_soins', models.TextField(blank=True, verbose_name='Régime de soins infirmiers')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.pathologie', verbose_name='Maladie')),
                ('unite_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.unitemesure', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'Modèle de plan de soins',
                'verbose_name_plural': 'Modèles de plan de soins',
                'ordering': ['nom'],
            },
        ),
    ]
