# Generated by Django 6.0.5 on 2026-06-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0008_add_soin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeControleAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name="Vérifier l'élément de la liste")),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': "Liste de contrôle d'admission",
                'verbose_name_plural': "Liste de contrôle d'admission",
                'ordering': ['id'],
            },
        ),
    ]
