# Generated by Django 6.0.5 on 2026-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0009_add_liste_controle_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeVerificationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Élément de la liste de contrôle de salle')),
            ],
            options={
                'verbose_name': 'Liste de vérification avant le service',
                'verbose_name_plural': 'Liste de vérification avant le service',
                'ordering': ['id'],
            },
        ),
    ]
