# Generated by Django 6.0.5 on 2026-06-02 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0010_add_liste_verification_service'),
        ('medecins', '0006_medecin_photo_restore'),
        ('patients', '0015_add_registres_cpn_accouchement_postnatale_curatif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.service', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.pathologie', verbose_name='Maladie'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='medecin_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_referent', to='medecins.medecin', verbose_name='Médecin référent'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='mise_en_observation',
            field=models.TextField(blank=True, verbose_name='Mise en observation'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='nom_parent_gardien',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du parent (gardien) du patient'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='phone_parent_gardien',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone du parent (gardien) du patient'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hospitalisations/'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.chambre', verbose_name='Salle/Chambre'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='date_admission',
            field=models.DateTimeField(verbose_name="Date d'hospitalisation"),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='medecin_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_principales', to='medecins.medecin', verbose_name='Docteur principal'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='motif_admission',
            field=models.TextField(blank=True, verbose_name="Motif d'admission"),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('hospitalise', 'Hospitalisé'), ('decharge', 'Déchargé'), ('termine', 'Terminé')], default='brouillon', max_length=20),
        ),
    ]
