# Generated by Django 6.0.5 on 2026-06-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0012_add_log_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Élément')),
                ('verifie', models.BooleanField(default=False, verbose_name='O/N')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_admission', to='hospitalisation.hospitalisation')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Élément')),
                ('termine', models.BooleanField(default=False, verbose_name='Terminé')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_verification', to='hospitalisation.hospitalisation')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
