# Generated by Django 6.0.5 on 2026-06-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0014_add_evaluation_clinique'),
        ('medecins', '0006_medecin_photo_restore'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='cas_legal',
            field=models.BooleanField(default=False, verbose_name='Cas légal'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='infirmiere_primaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_infirmiere', to='medecins.medecin', verbose_name='Infirmière primaire'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='signale_police',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('', '—')], default='', max_length=3, verbose_name='Signalé à la police'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='soins_apportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.soin', verbose_name='Soins apportés'),
        ),
        migrations.CreateModel(
            name='VisiteDocteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('instruction', models.TextField(blank=True, verbose_name='Instruction')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('docteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin', verbose_name='Docteur')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_docteur', to='hospitalisation.hospitalisation')),
            ],
            options={
                'ordering': ['ordre', 'date'],
            },
        ),
        migrations.CreateModel(
            name='VisiteInfirmiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantité')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_infirmieres', to='hospitalisation.hospitalisation')),
                ('infirmiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin', verbose_name='Infirmière')),
                ('soin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.soin', verbose_name='Soin')),
                ('unite_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.unitemesure', verbose_name='Unité de mesure')),
            ],
            options={
                'ordering': ['ordre', 'date'],
            },
        ),
    ]
