# Generated by Django 6.0.5 on 2026-06-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0015_add_visites_juridique_soins'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('hospitalise', 'Hospitalisé'), ('decharge', 'Déchargé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='ResumeDecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfert', models.BooleanField(default=False, verbose_name='Transfert')),
                ('diagnostic_decharge', models.TextField(blank=True, verbose_name='Diagnostic de décharge')),
                ('note_preoperatoire', models.TextField(blank=True, verbose_name='Note préopératoire')),
                ('cours_post_operatoire', models.TextField(blank=True, verbose_name='Cours post-opératoire')),
                ('plan_sortie', models.TextField(blank=True, verbose_name='Plan de sortie')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('hospitalisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_decharge', to='hospitalisation.hospitalisation')),
                ('registre_deces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.registredeces', verbose_name='Registre des décès')),
            ],
            options={
                'verbose_name': 'Résumé de décharge',
            },
        ),
        migrations.CreateModel(
            name='ServiceAFacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantité')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_a_facturer', to='hospitalisation.hospitalisation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.articleservice', verbose_name='Service')),
                ('unite_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.unitemesure', verbose_name='Unité de mesure')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
