# Generated by Django 6.0.5 on 2026-06-02 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_update_visites_saf_articleservice'),
        ('hospitalisation', '0016_add_statut_annule_services_facturer_resume'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceafacturer',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_hospitalisation', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='serviceafacturer',
            name='source',
            field=models.CharField(choices=[('visite_infirmiere', 'Visite infirmière'), ('visite_docteur', 'Visite docteur'), ('chambre', 'Chambre'), ('manuel', 'Manuel')], default='manuel', max_length=20, verbose_name='Origine'),
        ),
        migrations.AddField(
            model_name='visitedocteur',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.articleservice', verbose_name='Soin / Acte'),
        ),
        migrations.AlterField(
            model_name='visiteinfirmiere',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.articleservice', verbose_name='Soin / Acte'),
        ),
    ]
