# Generated by Django 6.0.5 on 2026-06-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0017_update_visites_saf_articleservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisation',
            name='soins_apportes',
        ),
    ]
