# Generated by Django 6.0.5 on 2026-06-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0018_remove_soins_apportes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='prix_jour',
        ),
    ]
