# Generated by Django 6.0.5 on 2026-06-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0019_remove_chambre_prix_jour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modèleplansoins',
            name='maladie',
        ),
        migrations.RemoveField(
            model_name='modèleplansoins',
            name='unite_mesure',
        ),
        migrations.DeleteModel(
            name='Soin',
        ),
        migrations.DeleteModel(
            name='ModèlePlanSoins',
        ),
    ]
