# Generated by Django 6.0.5 on 2026-06-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0020_supprimer_soin_et_modeleplansoins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentreHospitalier',
        ),
    ]
