# Generated by Django 6.0.5 on 2026-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0021_supprimer_centrehospitalier'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='soins_apportes',
            field=models.ManyToManyField(blank=True, related_name='hospitalisations_soins', to='services.articleservice', verbose_name='Soins apportés'),
        ),
    ]
