# Generated by Django 6.0.5 on 2026-06-05 19:39 — restructured to embed data migration

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copier_dates_vers_heures(apps, schema_editor):
    """
    Préserve les données existantes :
    - date_admission → heure_entree pour les dossiers hospitalise / decharge / termine
    - date_sortie_effective (ou date_sortie à minuit) → heure_sortie pour decharge / termine
    Les anciens enregistrements avec d'autres statuts conservent heure_entree/heure_sortie à NULL.
    """
    from django.utils import timezone as tz
    import datetime

    Hospitalisation = apps.get_model('hospitalisation', 'Hospitalisation')
    statuts_entree = {'hospitalise', 'decharge', 'termine'}
    statuts_sortie = {'decharge', 'termine'}

    for h in Hospitalisation.objects.all():
        changed = False

        if h.statut in statuts_entree and h.date_admission and not h.heure_entree:
            h.heure_entree = h.date_admission
            changed = True

        if h.statut in statuts_sortie and not h.heure_sortie:
            if h.date_sortie_effective:
                h.heure_sortie = h.date_sortie_effective
                changed = True
            elif h.date_sortie:
                # DateField → DateTimeField : on fixe à minuit heure locale
                h.heure_sortie = datetime.datetime(
                    h.date_sortie.year,
                    h.date_sortie.month,
                    h.date_sortie.day,
                    tzinfo=datetime.timezone.utc,
                )
                changed = True

        if changed:
            h.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_constante_new_fields'),
        ('hospitalisation', '0022_soins_apportes_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Supprimer caution / caution_payee immédiatement (pas de données à migrer)
        migrations.RemoveField(
            model_name='hospitalisation',
            name='caution',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='caution_payee',
        ),

        # 2. Ajouter tous les nouveaux champs AVANT la data migration
        migrations.AddField(
            model_name='hospitalisation',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations', to='consultations.consultation', verbose_name="Consultation d'origine"),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='date_termine',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='etablissement_destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='Établissement de destination'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='heure_entree',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Heure d'entrée"),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='heure_sortie',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Heure de sortie'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='motif_reference',
            field=models.TextField(blank=True, verbose_name='Motif du référé'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='termine_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_terminees', to=settings.AUTH_USER_MODEL, verbose_name='Terminé par'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('hospitalise', 'Hospitalisé'), ('decharge', 'Déchargé'), ('refere', 'Référé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceafacturer',
            name='source',
            field=models.CharField(choices=[('visite_infirmiere', 'Visite infirmière'), ('visite_docteur', 'Visite docteur'), ('chambre', 'Chambre'), ('soin', 'Soin apporté'), ('manuel', 'Manuel')], default='manuel', max_length=20, verbose_name='Origine'),
        ),

        # 3. Data migration : copier date_admission → heure_entree, date_sortie → heure_sortie
        #    (date_sortie et date_sortie_effective existent encore à ce stade)
        migrations.RunPython(copier_dates_vers_heures, reverse_code=noop),

        # 4. Supprimer les anciens champs de date maintenant que les données sont copiées
        migrations.RemoveField(
            model_name='hospitalisation',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='date_sortie_effective',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='date_sortie_prevue',
        ),
    ]
