# Generated by Django 6.0.5 on 2026-06-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0023_remove_hospitalisation_caution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalisation',
            options={'ordering': ['-date_admission'], 'permissions': [('can_creer_facture', 'Peut créer une facture depuis une hospitalisation'), ('can_decharger', 'Peut décharger (sortie médicale) un patient en observation'), ('can_referer', 'Peut référer un patient vers un autre établissement')], 'verbose_name': 'Hospitalisation'},
        ),
    ]
