# Generated by Django 6.0.5 on 2026-06-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0025_update_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisation',
            name='diagnostic_admission',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='photo',
        ),
        migrations.AlterField(
            model_name='serviceafacturer',
            name='source',
            field=models.CharField(choices=[('visite_infirmiere', 'Visite infirmière'), ('visite_docteur', 'Visite docteur'), ('soin', 'Soin apporté'), ('manuel', 'Manuel')], default='manuel', max_length=20, verbose_name='Origine'),
        ),
        migrations.DeleteModel(
            name='ProtocoleHospitalisation',
        ),
    ]
