# Generated by Django 6.0.5 on 2026-06-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0026_remove_photo_diagnostic_admission_protocole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalisation',
            options={'ordering': ['-date_admission'], 'permissions': [('can_confirmer_demande', "Peut confirmer une demande d'hospitalisation"), ('can_creer_facture', "Peut créer une facture d'hospitalisation"), ('can_installer_patient', 'Peut installer le patient (passage en Hospitalisé)'), ('can_decharger_patient', 'Peut décharger un patient (sortie médicale)'), ('can_cloturer_dossier', 'Peut clôturer un dossier (passage à Terminé)'), ('can_annuler_demande', 'Peut annuler une demande')], 'verbose_name': 'Hospitalisation'},
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='motif_reference',
            field=models.TextField(blank=True, verbose_name='Motif du transfert'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('hospitalise', 'Hospitalisé'), ('decharge', 'Déchargé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
    ]
