# Generated by Django 6.0.5 on 2026-06-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0029_remove_chambre_capacite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisation',
            name='departement',
        ),
    ]
