# Generated by Django 6.0.6 on 2026-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0030_remove_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='nombre_lits',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de lits'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='numero_lit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de lit'),
        ),
        migrations.AlterField(
            model_name='serviceafacturer',
            name='source',
            field=models.CharField(choices=[('visite_infirmiere', 'Visite infirmière'), ('visite_docteur', 'Visite docteur'), ('soin', 'Soin apporté'), ('meo', 'Mise en observation'), ('manuel', 'Manuel')], default='manuel', max_length=20, verbose_name='Origine'),
        ),
    ]
