# Generated by Django 6.0.5 on 2026-06-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0030_remove_departement'),
        ('stock', '0012_unitemesure_alter_produit_unite_mesure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceafacturer',
            name='unite_mesure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.unitemesure', verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='visiteinfirmiere',
            name='unite_mesure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.unitemesure', verbose_name='Unité de mesure'),
        ),
    ]
