# Generated by Django 6.0.6 on 2026-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0031_add_nombre_lits_numero_lit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='date_admission',
            field=models.DateTimeField(verbose_name="Date de la demande d'hospitalisation"),
        ),
    ]
