# Generated by Django 6.0.6 on 2026-06-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0032_rename_date_admission_verbose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalisation',
            options={'ordering': ['-date_admission'], 'permissions': [('can_confirmer_demande', "Peut confirmer une demande d'hospitalisation"), ('can_creer_facture', "Peut créer une facture d'hospitalisation"), ('can_installer_patient', 'Peut installer le patient (passage en Hospitalisé)'), ('can_ajouter_soin', 'Peut ajouter des soins infirmiers (patient hospitalisé)'), ('can_decharger_patient', 'Peut décharger un patient (sortie médicale)'), ('can_cloturer_dossier', 'Peut clôturer un dossier (passage à Terminé)'), ('can_annuler_demande', 'Peut annuler une demande')], 'verbose_name': 'Hospitalisation'},
        ),
    ]
