# Generated by Django 5.1.6 on 2026-08-13 23:23

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_creer_centres_initiaux'),
        ('hospitalisation', '0034_alter_serviceafacturer_unite_mesure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'base_manager_name': 'all_objects', 'ordering': ['salle_no'], 'verbose_name': 'Chambre'},
        ),
        migrations.AlterModelManagers(
            name='chambre',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
