# Generated by Django 5.1.6 on 2026-08-13 23:24

from django.db import migrations


def backfill_centre(apps, schema_editor):
    """Rattache les chambres existantes (créées avant le cloisonnement par
    centre) au centre Walé Yamoussoukro (WALE) — c'est le centre historique/
    principal, déjà utilisé comme repli par défaut ailleurs (voir
    core.migrations.0007_backfill_userprofile_centres)."""
    Centre = apps.get_model('centres', 'Centre')
    Chambre = apps.get_model('hospitalisation', 'Chambre')
    wale = Centre.objects.filter(code='WALE').first()
    if wale is not None:
        Chambre.objects.filter(centre__isnull=True).update(centre=wale)


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0035_chambre_centre'),
    ]

    operations = [
        migrations.RunPython(backfill_centre, reverse_backfill),
    ]
