# Generated by Django 6.0.6 on 2026-08-22 18:23

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_creer_centres_initiaux'),
        ('hospitalisation', '0036_backfill_chambre_centre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalisation',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_admission'], 'permissions': [('can_confirmer_demande', "Peut confirmer une demande d'hospitalisation"), ('can_creer_facture', "Peut créer une facture d'hospitalisation"), ('can_installer_patient', 'Peut installer le patient (passage en Hospitalisé)'), ('can_ajouter_soin', 'Peut ajouter des soins infirmiers (patient hospitalisé)'), ('can_decharger_patient', 'Peut décharger un patient (sortie médicale)'), ('can_cloturer_dossier', 'Peut clôturer un dossier (passage à Terminé)'), ('can_annuler_demande', 'Peut annuler une demande')], 'verbose_name': 'Hospitalisation'},
        ),
        migrations.AlterModelOptions(
            name='registredeces',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_deces'], 'verbose_name': 'Registre des décès', 'verbose_name_plural': 'Registre des décès'},
        ),
        migrations.AlterModelManagers(
            name='hospitalisation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='registredeces',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='registredeces',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
