# Generated by Django 6.0.6 on 2026-08-25 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0037_alter_hospitalisation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationclinique',
            options={'ordering': ['-date_saisie'], 'verbose_name': 'Évaluation clinique'},
        ),
        migrations.AlterField(
            model_name='evaluationclinique',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluationclinique',
            name='hospitalisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hospitalisation.hospitalisation'),
        ),
    ]
