# Generated by Django 6.0.7 on 2026-09-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0038_alter_evaluationclinique_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'default_permissions': (), 'ordering': ['nom'], 'permissions': [('view_batiment', 'Peut consulter les bâtiments'), ('add_batiment', 'Peut créer un bâtiment'), ('change_batiment', 'Peut modifier un bâtiment'), ('delete_batiment', 'Peut supprimer un bâtiment')], 'verbose_name': 'Bâtiment', 'verbose_name_plural': 'Bâtiments'},
        ),
        migrations.AlterModelOptions(
            name='chambre',
            options={'base_manager_name': 'all_objects', 'default_permissions': (), 'ordering': ['salle_no'], 'permissions': [('view_chambre', 'Peut consulter les chambres'), ('add_chambre', 'Peut créer une chambre'), ('change_chambre', 'Peut modifier une chambre'), ('delete_chambre', 'Peut supprimer une chambre')], 'verbose_name': 'Chambre'},
        ),
        migrations.AlterModelOptions(
            name='checklistadmission',
            options={'default_permissions': (), 'ordering': ['ordre', 'id'], 'permissions': [('view_checklistadmission', "Peut consulter les lignes de contrôle d'admission"), ('add_checklistadmission', "Peut créer une ligne de contrôle d'admission"), ('change_checklistadmission', "Peut modifier une ligne de contrôle d'admission"), ('delete_checklistadmission', "Peut supprimer une ligne de contrôle d'admission")]},
        ),
        migrations.AlterModelOptions(
            name='checklistverification',
            options={'default_permissions': (), 'ordering': ['ordre', 'id'], 'permissions': [('view_checklistverification', 'Peut consulter les lignes de vérification avant service'), ('add_checklistverification', 'Peut créer une ligne de vérification avant service'), ('change_checklistverification', 'Peut modifier une ligne de vérification avant service'), ('delete_checklistverification', 'Peut supprimer une ligne de vérification avant service')]},
        ),
        migrations.AlterModelOptions(
            name='evaluationclinique',
            options={'default_permissions': (), 'ordering': ['-date_saisie'], 'permissions': [('view_evaluationclinique', 'Peut consulter les évaluations cliniques'), ('add_evaluationclinique', 'Peut créer une évaluation clinique'), ('change_evaluationclinique', 'Peut modifier une évaluation clinique'), ('delete_evaluationclinique', 'Peut supprimer une évaluation clinique')], 'verbose_name': 'Évaluation clinique'},
        ),
        migrations.AlterModelOptions(
            name='fichevisite',
            options={'default_permissions': (), 'ordering': ['-date_visite'], 'permissions': [('view_fichevisite', 'Peut consulter les fiches de visite'), ('add_fichevisite', 'Peut créer une fiche de visite'), ('change_fichevisite', 'Peut modifier une fiche de visite'), ('delete_fichevisite', 'Peut supprimer une fiche de visite')], 'verbose_name': 'Fiche de visite'},
        ),
        migrations.AlterModelOptions(
            name='hospitalisation',
            options={'base_manager_name': 'all_objects', 'default_permissions': (), 'ordering': ['-date_admission'], 'permissions': [('view_hospitalisation', 'Peut consulter les hospitalisations'), ('add_hospitalisation', 'Peut créer une hospitalisation'), ('change_hospitalisation', 'Peut modifier une hospitalisation'), ('delete_hospitalisation', 'Peut supprimer une hospitalisation'), ('can_confirmer_demande', "Peut confirmer une demande d'hospitalisation"), ('can_creer_facture', "Peut créer une facture d'hospitalisation"), ('can_installer_patient', 'Peut installer le patient (passage en Hospitalisé)'), ('can_ajouter_soin', 'Peut ajouter des soins infirmiers (patient hospitalisé)'), ('can_decharger_patient', 'Peut décharger un patient (sortie médicale)'), ('can_cloturer_dossier', 'Peut clôturer un dossier (passage à Terminé)'), ('can_annuler_demande', 'Peut annuler une demande')], 'verbose_name': 'Hospitalisation'},
        ),
        migrations.AlterModelOptions(
            name='listecontroleadmission',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': [('view_listecontroleadmission', "Peut consulter la liste de contrôle d'admission"), ('add_listecontroleadmission', "Peut ajouter un élément à la liste de contrôle d'admission"), ('change_listecontroleadmission', "Peut modifier un élément de la liste de contrôle d'admission"), ('delete_listecontroleadmission', "Peut supprimer un élément de la liste de contrôle d'admission")], 'verbose_name': "Liste de contrôle d'admission", 'verbose_name_plural': "Liste de contrôle d'admission"},
        ),
        migrations.AlterModelOptions(
            name='listeverificationservice',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': [('view_listeverificationservice', 'Peut consulter la liste de vérification avant le service'), ('add_listeverificationservice', 'Peut ajouter un élément à la liste de vérification avant le service'), ('change_listeverificationservice', 'Peut modifier un élément de la liste de vérification avant le service'), ('delete_listeverificationservice', 'Peut supprimer un élément de la liste de vérification avant le service')], 'verbose_name': 'Liste de vérification avant le service', 'verbose_name_plural': 'Liste de vérification avant le service'},
        ),
        migrations.AlterModelOptions(
            name='logactivitehospitalisation',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': [('view_logactivitehospitalisation', "Peut consulter les logs d'activité"), ('add_logactivitehospitalisation', "Peut créer un log d'activité"), ('change_logactivitehospitalisation', "Peut modifier un log d'activité"), ('delete_logactivitehospitalisation', "Peut supprimer un log d'activité")], 'verbose_name': "Log d'activité"},
        ),
        migrations.AlterModelOptions(
            name='registredeces',
            options={'base_manager_name': 'all_objects', 'default_permissions': (), 'ordering': ['-date_deces'], 'permissions': [('view_registredeces', 'Peut consulter le registre des décès'), ('add_registredeces', 'Peut créer un enregistrement de décès'), ('change_registredeces', 'Peut modifier un enregistrement de décès'), ('delete_registredeces', 'Peut supprimer un enregistrement de décès')], 'verbose_name': 'Registre des décès', 'verbose_name_plural': 'Registre des décès'},
        ),
        migrations.AlterModelOptions(
            name='resumedecharge',
            options={'default_permissions': (), 'permissions': [('view_resumedecharge', 'Peut consulter les résumés de décharge'), ('add_resumedecharge', 'Peut créer un résumé de décharge'), ('change_resumedecharge', 'Peut modifier un résumé de décharge'), ('delete_resumedecharge', 'Peut supprimer un résumé de décharge')], 'verbose_name': 'Résumé de décharge'},
        ),
        migrations.AlterModelOptions(
            name='serviceafacturer',
            options={'default_permissions': (), 'ordering': ['ordre', 'id'], 'permissions': [('view_serviceafacturer', 'Peut consulter les services à facturer'), ('add_serviceafacturer', 'Peut créer un service à facturer'), ('change_serviceafacturer', 'Peut modifier un service à facturer'), ('delete_serviceafacturer', 'Peut supprimer un service à facturer')]},
        ),
        migrations.AlterModelOptions(
            name='visitedocteur',
            options={'default_permissions': (), 'ordering': ['ordre', 'date'], 'permissions': [('view_visitedocteur', 'Peut consulter les visites du docteur'), ('add_visitedocteur', 'Peut créer une visite du docteur'), ('change_visitedocteur', 'Peut modifier une visite du docteur'), ('delete_visitedocteur', 'Peut supprimer une visite du docteur')]},
        ),
        migrations.AlterModelOptions(
            name='visiteinfirmiere',
            options={'default_permissions': (), 'ordering': ['ordre', 'date'], 'permissions': [('view_visiteinfirmiere', 'Peut consulter les visites infirmières'), ('add_visiteinfirmiere', 'Peut créer une visite infirmière'), ('change_visiteinfirmiere', 'Peut modifier une visite infirmière'), ('delete_visiteinfirmiere', 'Peut supprimer une visite infirmière')]},
        ),
    ]
