# Generated by Django 6.0.7 on 2026-10-03 13:21

from django.db import migrations, models


def _reprendre_les_heures(apps, schema_editor):
    """Les dossiers d'avant ces champs : leurs heures SONT celles du système.

    Personne n'a jamais pu les modifier — elles étaient `editable=False` et
    seules les transitions de statut les posaient. On peut donc les recopier
    sans rien inventer, et l'écart part de zéro pour tout le monde.
    """
    Hospitalisation = apps.get_model('hospitalisation', 'Hospitalisation')
    Hospitalisation.objects.filter(heure_entree__isnull=False).update(
        heure_entree_systeme=models.F('heure_entree'))
    Hospitalisation.objects.filter(heure_sortie__isnull=False).update(
        heure_sortie_systeme=models.F('heure_sortie'))


def _oublier_les_heures(apps, schema_editor):
    """Rien à défaire : les colonnes disparaissent avec le retour en arrière."""


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0040_permissions_en_francais'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='heure_entree_systeme',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Heure d'entrée enregistrée par le système"),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='heure_sortie_systeme',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Heure de sortie enregistrée par le système'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='heure_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Heure d'entrée"),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='heure_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de sortie'),
        ),
        migrations.RunPython(_reprendre_les_heures, _oublier_les_heures),
    ]
