# Generated by Django 6.0.4 on 2026-04-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actif', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caisse',
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('solde_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='caisse.caisse')),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_transaction', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('transfert', 'Transfert')], max_length=20)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement')], default='especes', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.facture')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='caisse.sessioncaisse')),
            ],
            options={
                'verbose_name': 'Transaction de caisse',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
