# Generated by Django 6.0.5 on 2026-05-20 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=300)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acte médical',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('assurance', 'Assurance'), ('bon', 'Bon')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_facture', models.CharField(choices=[('consultation', 'Consultation'), ('hospitalisation', 'Hospitalisation'), ('pharmacie', 'Pharmacie'), ('laboratoire', 'Laboratoire'), ('imagerie', 'Imagerie'), ('autre', 'Autre')], default='consultation', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ticket_moderateur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('partielle', 'Partielle'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-date_emission'],
            },
        ),
    ]
