# Generated by Django 6.0.5 on 2026-05-20 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        ('hospitalisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.hospitalisation'),
        ),
    ]
