# Generated by Django 6.0.5 on 2026-06-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('soins', 'Soins'), ('hospitalisation', 'Hospitalisation'), ('pharmacie', 'Pharmacie'), ('laboratoire', 'Laboratoire'), ('imagerie', 'Imagerie'), ('autre', 'Autre')], default='consultation', max_length=20),
        ),
    ]
