# Generated by Django 6.0.5 on 2026-05-20 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0002_initial'),
        ('patients', '0001_initial'),
        ('pharmacie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='acte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.acte'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.medicament'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recu_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
