# Generated by Django 6.0.6 on 2026-07-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_facture_rendez_vous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'permissions': [('can_valider_facture', 'Peut valider une facture (brouillon → émise)')], 'verbose_name': 'Facture'},
        ),
    ]
