# Generated by Django 5.1.6 on 2026-07-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_alter_facture_options'),
    ]

    operations = [
    ]
