# Generated by Django 5.1.6 on 2026-07-11 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_ordonnance_medecin'),
        ('facturation', '0006_restore_rendez_vous'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='consultations.ordonnance', verbose_name='Ordonnance'),
        ),
    ]
