# Generated by Django 6.0.6 on 2026-08-24 21:38

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0004_rattacher_rendez_vous'),
        ('facturation', '0007_add_ordonnance_to_facture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_emission'], 'permissions': [('can_valider_facture', 'Peut valider une facture (brouillon → émise)')], 'verbose_name': 'Facture'},
        ),
        migrations.AlterModelManagers(
            name='facture',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
