# Generated by Django 6.0.7 on 2026-09-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0011_demontage_application_caisse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'default_permissions': (), 'ordering': ['nom'], 'permissions': [('view_caisse', 'Peut consulter les caisses'), ('add_caisse', 'Peut créer une caisse'), ('change_caisse', 'Peut modifier une caisse'), ('delete_caisse', 'Peut supprimer une caisse')], 'verbose_name': 'Caisse', 'verbose_name_plural': 'Caisses'},
        ),
    ]
