# Generated by Django 6.0.7 on 2026-09-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0013_libelles_permissions_caisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='responsable',
        ),
    ]
