# Generated by Django 6.0.7 on 2026-09-23 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0014_remove_caisse_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='facturation.caisse', verbose_name='Caisse'),
        ),
    ]
