# Generated by Django 6.0.7 on 2026-09-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0015_paiement_caisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='solde_actuel',
        ),
    ]
