# Generated by Django 6.0.7 on 2026-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0016_remove_caisse_solde_actuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='modes_paiement',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Modes de paiement acceptés'),
        ),
    ]
