# Generated by Django 6.0.7 on 2026-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0017_caisse_modes_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant reçu'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='modes_paiement',
            field=models.CharField(blank=True, default='especes', max_length=200, verbose_name='Modes de paiement acceptés'),
        ),
    ]
