# Generated by Django 6.0.7 on 2026-09-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0019_especes_sur_les_caisses_existantes'),
        ('services', '0016_articleservice_type_test_labo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='services.articleservice', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('soins', 'Soins'), ('hospitalisation', 'Hospitalisation'), ('pharmacie', 'Pharmacie'), ('laboratoire', 'Laboratoire'), ('imagerie', 'Imagerie'), ('mixte', 'Mixte'), ('autre', 'Autre')], default='consultation', max_length=20),
        ),
    ]
