# Generated by Django 6.0.7 on 2026-09-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0020_lignefacture_article_alter_facture_type_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignefacture',
            name='medicament',
        ),
    ]
