# Generated by Django 6.0.7 on 2026-09-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0021_remove_lignefacture_medicament'),
        ('stock', '0016_merge_20260724_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='stock.produit', verbose_name='Produit'),
        ),
    ]
