# Generated by Django 6.0.7 on 2026-09-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_alter_ordonnance_date_expiration'),
        ('facturation', '0022_lignefacture_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='ligne_ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='consultations.ligneordonnance', verbose_name="Ligne d'ordonnance"),
        ),
    ]
