# Generated by Django 6.0.7 on 2026-09-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0023_lignefacture_ligne_ordonnance'),
        ('laboratoire', '0009_lignedemandeexamen_article_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='ligne_demande_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='laboratoire.lignedemandeexamen', verbose_name="Ligne de demande d'examen"),
        ),
    ]
