# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0024_lignefacture_ligne_demande_examen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_paiement'], 'permissions': [('can_encaisser', 'Peut enregistrer un encaissement')], 'verbose_name': 'Paiement'},
        ),
    ]
