# Generated by Django 6.0.7 on 2026-10-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0025_alter_paiement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'permissions': [('can_modifier_prix_ligne', "Peut modifier le prix d'une ligne de facture")], 'verbose_name': 'ligne facture', 'verbose_name_plural': 'lignes facture'},
        ),
    ]
