# Generated by Django 6.0.7 on 2026-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0026_alter_lignefacture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_emission'], 'permissions': [('can_valider_facture', 'Peut valider une facture (brouillon → émise)'), ('can_annuler_facture', 'Peut annuler une facture (et rembourser)')], 'verbose_name': 'Facture'},
        ),
    ]
