# Generated by Django 6.0.5 on 2026-05-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generer_codes_medecins(apps, schema_editor):
    Medecin = apps.get_model('medecins', 'Medecin')
    annee = 2026
    for i, medecin in enumerate(Medecin.objects.filter(code='').order_by('id'), start=1):
        medecin.code = f'DR{annee}{i:04d}'
        medecin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['titre'],
            },
        ),
        migrations.AlterModelOptions(
            name='medecin',
            options={'ordering': ['nom'], 'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom'], 'verbose_name': 'Service / Département', 'verbose_name_plural': 'Services / Départements'},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['nom'], 'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='taux_honoraire',
        ),
        migrations.RemoveField(
            model_name='service',
            name='chef_service',
        ),
        migrations.AddField(
            model_name='medecin',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='chirurgien_principal',
            field=models.BooleanField(default=False, verbose_name='Chirurgien principal'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code médecin'),
        ),
        migrations.RunPython(generer_codes_medecins, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='medecin',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code médecin'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='duree_consultation',
            field=models.PositiveSmallIntegerField(default=15, help_text='Durée par défaut en minutes', verbose_name='Durée de consultation (min)'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='fonction',
            field=models.CharField(blank=True, help_text='Ex: Directeur Médical, Médecin généraliste', max_length=100, verbose_name='Fonction / Titre'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medecins/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='service_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_consultation', to='medecins.service', verbose_name='Service de consultation'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='service_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_suivi', to='medecins.service', verbose_name='Service de suivi'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='medecins', to='medecins.service', verbose_name='Départements / Services'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='tva_numero_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='TVA / Numéro fiscal'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='ordre_medecin',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Ordre des médecins'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='prenoms',
            field=models.CharField(max_length=200, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.specialite', verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='service',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.CreateModel(
            name='MedecinDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution')),
                ('annee_obtention', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Année d'obtention")),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.diplome', verbose_name='Diplôme')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='medecins.medecin', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Diplôme du médecin',
                'verbose_name_plural': 'Diplômes du médecin',
            },
        ),
    ]
