# Generated by Django 6.0.5 on 2026-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_diplome_alter_medecin_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['type_service', 'nom'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Coût interne (FCFA)'),
        ),
        migrations.AddField(
            model_name='service',
            name='reference_interne',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence interne'),
        ),
        migrations.AddField(
            model_name='service',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix de vente (FCFA)'),
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.CharField(choices=[('departement', 'Département'), ('consultation', 'Consultation'), ('suivi', 'Suivi'), ('urgence', 'Urgence'), ('chirurgie', 'Chirurgie'), ('autre', 'Autre')], default='departement', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='service',
            name='unite',
            field=models.CharField(choices=[('unite', 'Unité'), ('heure', 'Heure'), ('seance', 'Séance'), ('jour', 'Jour')], default='unite', max_length=10, verbose_name='Unité de mesure'),
        ),
    ]
