# Generated by Django 6.0.5 on 2026-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0003_alter_service_options_service_cout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['categorie_article', 'nom'], 'verbose_name': 'Service médical', 'verbose_name_plural': 'Services médicaux'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='tarif',
            new_name='prix_vente',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type_service',
        ),
        migrations.AddField(
            model_name='service',
            name='categorie_article',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('suivi', 'Suivi'), ('chirurgie', 'Chirurgie'), ('urgence', 'Urgence'), ('analyse', 'Analyse / Laboratoire'), ('imagerie', 'Imagerie'), ('soins', 'Soins infirmiers'), ('autre', 'Autre')], default='consultation', max_length=20, verbose_name="Catégorie d'article"),
        ),
        migrations.AddField(
            model_name='service',
            name='code_barres',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code barres'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantite_prevue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantités prévues'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantités en stock'),
        ),
        migrations.AddField(
            model_name='service',
            name='type_article',
            field=models.CharField(choices=[('service', 'Service'), ('consommable', 'Consommable')], default='service', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='service',
            name='valeur_variante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valeur de la variante'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Coût (FCFA)'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='medecins', to='medecins.departement', verbose_name='Départements'),
        ),
    ]
