# Generated by Django 6.0.5 on 2026-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0003_service_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medecins/photos/'),
        ),
    ]
