# Generated by Django 6.0.5 on 2026-05-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0004_medecin_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='photo',
        ),
        migrations.AddField(
            model_name='medecin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='medecins.service', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='service',
            name='chef_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to='medecins.medecin'),
        ),
    ]
