# Generated by Django 6.0.5 on 2026-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0004_departement_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categorie_article',
            field=models.CharField(blank=True, max_length=100, verbose_name="Catégorie d'article"),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_article',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unite',
            field=models.CharField(blank=True, max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
