# Generated by Django 6.0.5 on 2026-05-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0006_categoriearticle_typearticle_unitemesure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categorie_article',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='departements',
        ),
        migrations.RemoveField(
            model_name='medecindiplome',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='medecindiplome',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type_article',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unite',
        ),
        migrations.AlterModelOptions(
            name='medecin',
            options={'ordering': ['nom'], 'verbose_name': 'Médecin'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'verbose_name': 'Spécialité'},
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='chirurgien_principal',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='duree_consultation',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='service_consultation',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='service_suivi',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='tva_numero_fiscal',
        ),
        migrations.RemoveField(
            model_name='service',
            name='code_barres',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cout',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prix_vente',
        ),
        migrations.RemoveField(
            model_name='service',
            name='quantite_prevue',
        ),
        migrations.RemoveField(
            model_name='service',
            name='quantite_stock',
        ),
        migrations.RemoveField(
            model_name='service',
            name='reference_interne',
        ),
        migrations.RemoveField(
            model_name='service',
            name='valeur_variante',
        ),
        migrations.AddField(
            model_name='medecin',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='taux_honoraire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='chef_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin'),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='ordre_medecin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='prenoms',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.specialite'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CategorieArticle',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Diplome',
        ),
        migrations.DeleteModel(
            name='MedecinDiplome',
        ),
        migrations.DeleteModel(
            name='TypeArticle',
        ),
        migrations.DeleteModel(
            name='UniteMesure',
        ),
    ]
