# Generated by Django 6.0.5 on 2026-06-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0005_departement'),
        ('medecins', '0006_medecin_photo_restore'),
    ]

    operations = [
    ]
