# Generated by Django 6.0.5 on 2026-05-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0007_remove_service_categorie_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['titre'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom'], 'verbose_name': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['nom'], 'verbose_name': 'Spécialité'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='chef_service',
        ),
        migrations.AddField(
            model_name='medecin',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='chirurgien_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medecin',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='duree_consultation',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Durée consultation (min)'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fonction / Titre'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medecins/photos/'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='service_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_consultation', to='medecins.service', verbose_name='Service de consultation'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='service_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_suivi', to='medecins.service', verbose_name='Service de suivi'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='tva_numero_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='TVA / N° fiscal'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.specialite'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medecin',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='medecins', to='medecins.departement', verbose_name='Départements'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.diplome', verbose_name='Éducation'),
        ),
    ]
