# Generated by Django 6.0.5 on 2026-06-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_employe_biometric_id_alter_conge_statut'),
        ('medecins', '0007_merge_0005_departement_0006_medecin_photo_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_medecin', to='employer.employe', verbose_name='Employé lié'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.specialite'),
        ),
    ]
