# Generated by Django 6.0.5 on 2026-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0008_departement_diplome_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='employe_societe',
            field=models.BooleanField(default=True, verbose_name='Employé de la société'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='medecins/signatures/', verbose_name='Signature'),
        ),
    ]
