# Generated by Django 6.0.5 on 2026-05-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0009_add_employe_societe_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocteurReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_contact', models.CharField(choices=[('individu', 'Individu'), ('societe', 'Société')], default='individu', max_length=10, verbose_name='Type')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(blank=True, max_length=200, verbose_name='Prénom(s)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/referents/')),
                ('poste_occupe', models.CharField(blank=True, max_length=100, verbose_name='Poste Occupé')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True, verbose_name='Site Web')),
                ('adresse', models.TextField(blank=True)),
                ('est_referent', models.BooleanField(default=True, verbose_name='Est le médecin référent')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.specialite', verbose_name='Spécialité')),
            ],
            options={
                'verbose_name': 'Docteur Référent',
                'verbose_name_plural': 'Docteurs Référents',
                'ordering': ['nom'],
            },
        ),
    ]
