# Generated by Django 6.0.6 on 2026-07-09 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0010_service_medecine_generale_gynecologie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='departement',
        ),
        migrations.AddField(
            model_name='medecin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='medecins.departement', verbose_name='Département'),
        ),
    ]
