# Generated by Django 6.0.5 on 2026-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0010_docteurreferent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('couleur', models.CharField(blank=True, default='#0ea5e9', max_length=7)),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='langue',
            field=models.CharField(blank=True, default='Français', max_length=50, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='titre',
            field=models.CharField(blank=True, choices=[('', '—'), ('dr', 'Dr'), ('pr', 'Pr'), ('m', 'M.'), ('mme', 'Mme'), ('prof', 'Prof.')], max_length=10, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='tva',
            field=models.CharField(blank=True, max_length=50, verbose_name='TVA'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, to='medecins.etiquette', verbose_name='Étiquettes'),
        ),
    ]
