# Generated by Django 5.2.15 on 2026-07-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0010_service_medecine_generale_gynecologie'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='medecins.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='medecins.service', verbose_name='Service'),
        ),
    ]
