# Generated by Django 6.0.6 on 2026-07-09 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0010_service_medecine_generale_gynecologie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='departement',
        ),
    ]
