# Generated by Django 6.0.5 on 2026-05-14 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0011_add_etiquette_titre_langue_tva_referent'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteurreferent',
            name='compte_client',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compte client'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='compte_fournisseur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compte fournisseur'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='medecin_interne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referents_associes', to='medecins.medecin', verbose_name='Docteur référent (interne)'),
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence'),
        ),
    ]
