# Generated by Django 6.0.6 on 2026-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0011_remove_medecin_service_remove_service_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSpecialise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('departements', models.ManyToManyField(blank=True, related_name='modules_specialises', to='medecins.departement')),
            ],
            options={
                'verbose_name': 'Module spécialisé',
                'ordering': ['nom'],
            },
        ),
    ]
