# Generated by Django 5.2.15 on 2026-07-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0012_modulespecialise'),
        ('medecins', '0012_unify_medecin_employe'),
    ]

    operations = [
    ]
