# Generated by Django 6.0.5 on 2026-05-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0012_add_medecin_interne_reference_comptes_referent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docteurreferent',
            options={},
        ),
        migrations.CreateModel(
            name='ContactAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(choices=[('contact', 'Contact'), ('facturation', 'Adresse de facturation'), ('livraison', 'Adresse de livraison'), ('autre', 'Autre adresse')], default='contact', max_length=20, verbose_name='Type')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('referent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_adresses', to='medecins.docteurreferent')),
            ],
            options={
                'verbose_name': 'Docteur Référent',
                'verbose_name_plural': 'Docteurs Référents',
                'ordering': ['nom'],
            },
        ),
    ]
