# Generated by Django 5.2.15 on 2026-07-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0013_merge_20260712_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleSpecialise',
        ),
    ]
