# Generated by Django 6.0.5 on 2026-05-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0013_add_contact_adresse_referent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactadresse',
            options={'verbose_name': 'Contact / Adresse', 'verbose_name_plural': 'Contacts / Adresses'},
        ),
        migrations.AlterModelOptions(
            name='docteurreferent',
            options={'ordering': ['nom'], 'verbose_name': 'Docteur Référent', 'verbose_name_plural': 'Docteurs Référents'},
        ),
        migrations.AddField(
            model_name='docteurreferent',
            name='genre',
            field=models.CharField(blank=True, choices=[('', '—'), ('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='genre',
            field=models.CharField(blank=True, choices=[('', '—'), ('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Genre'),
        ),
    ]
