# Generated by Django 6.0.5 on 2026-05-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0002_alter_chambre_service'),
        ('medecins', '0014_alter_contactadresse_options_and_more'),
        ('ressources_humaines', '0002_alter_poste_service'),
        ('services', '0007_typeservice_articleservice_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='service_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_consultation', to='services.articleservice', verbose_name='service de consultation'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='service_suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_suivi', to='services.articleservice', verbose_name='service de suivi'),
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
