# Generated by Django 5.2.15 on 2026-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0015_ordre_medecin_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='ordre_medecin',
            field=models.CharField(blank=True, help_text="Numéro d'inscription à l'Ordre des Médecins — saisi, pas généré.", max_length=50, null=True, unique=True, verbose_name="Numéro d'ordre"),
        ),
    ]
