# Generated by Django 5.2.15 on 2026-07-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0015_replace_departements_defaut'),
        ('medecins', '0016_alter_medecin_ordre_medecin'),
    ]

    operations = [
    ]
