# Generated by Django 6.0.7 on 2026-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0017_merge_20260724_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecin',
            options={'ordering': ['employe__nom'], 'permissions': [('can_gerer_medecins', "Peut gérer l'annuaire des médecins")], 'verbose_name': 'Médecin'},
        ),
    ]
