# Generated by Django 5.2.16 on 2026-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0018_alter_medecin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='nom_affichage',
            field=models.CharField(blank=True, help_text='Remplace le raccourci automatique (ex. « Dr Konan E ») partout où le nom est abrégé — planning, liste des rendez-vous. Laissez vide pour garder le raccourci automatique.', max_length=40, verbose_name='Nom à afficher (raccourci)'),
        ),
    ]
