# Generated by Django 6.0.4 on 2026-04-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('taux_prise_en_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assurance',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(default='Yamoussoukro', max_length=100)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('antecedents', models.TextField(blank=True)),
                ('numero_assurance', models.CharField(blank=True, max_length=100)),
                ('date_expiration_assurance', models.DateField(blank=True, null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.assurance')),
            ],
            options={
                'verbose_name': 'Patient',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('duree_minutes', models.IntegerField(default=30)),
                ('type_rdv', models.CharField(choices=[('consultation', 'Consultation'), ('controle', 'Contrôle'), ('urgence', 'Urgence'), ('examen', 'Examen'), ('vaccination', 'Vaccination')], default='consultation', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('absent', 'Absent')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'ordering': ['date_heure'],
            },
        ),
    ]
