# Generated by Django 5.1.6 on 2026-05-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='code_confirmation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='departement',
            field=models.CharField(blank=True, choices=[('medecine_generale', 'Médecine générale'), ('gynecologie_cpn', 'Gynécologie / CPN')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='temps_attente_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='temps_constante_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='temps_consultation_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
