# Generated by Django 5.1.6 on 2026-05-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0002_rendezvous_code_confirmation_rendezvous_departement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='type_rdv',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='medecins.service'),
        ),
    ]
