# Generated by Django 6.0.5 on 2026-05-13 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0002_rendezvous_code_confirmation_rendezvous_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_accouchement', models.DateTimeField(verbose_name="Date d'accouchement")),
                ('mode_accouchement', models.CharField(choices=[('voie_basse', 'Voie basse'), ('cesarienne', 'Césarienne'), ('forceps', 'Forceps'), ('ventouse', 'Ventouse')], default='voie_basse', max_length=20, verbose_name="Mode d'accouchement")),
                ('nom_enfant', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'enfant")),
                ('prenoms_enfant', models.CharField(blank=True, max_length=200, verbose_name="Prénoms de l'enfant")),
                ('sexe_enfant', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name="Sexe de l'enfant")),
                ('poids_naissance', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Poids (g)')),
                ('taille_naissance', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Taille (cm)')),
                ('apgar_1min', models.IntegerField(blank=True, null=True, verbose_name='Apgar 1 min')),
                ('apgar_5min', models.IntegerField(blank=True, null=True, verbose_name='Apgar 5 min')),
                ('statut', models.CharField(choices=[('vivant', 'Vivant'), ('mort_ne', 'Mort-né')], default='vivant', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin', verbose_name='Médecin')),
                ('mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naissances', to='patients.patient', verbose_name='Mère')),
            ],
            options={
                'verbose_name': 'Naissance',
                'ordering': ['-date_accouchement'],
            },
        ),
    ]
