# Generated by Django 6.0.5 on 2026-05-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0010_docteurreferent'),
        ('patients', '0002_rendezvous_code_confirmation_rendezvous_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medecin_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='medecins.docteurreferent', verbose_name='Médecin référent'),
        ),
    ]
