# Generated by Django 6.0.5 on 2026-05-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naissance',
            name='notes',
        ),
        migrations.AddField(
            model_name='naissance',
            name='age_mere',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge de la mère'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='education_mere',
            field=models.CharField(blank=True, choices=[('', '—'), ('aucun', 'Aucun'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur')], max_length=20, verbose_name='Éducation'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='groupe_sanguin_enfant',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='info_parents',
            field=models.TextField(blank=True, verbose_name='Information sur les parents'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='nombre_filles',
            field=models.IntegerField(default=0, verbose_name='Fille(s)'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='nombre_garcons',
            field=models.IntegerField(default=0, verbose_name='Garçon(s)'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='parite',
            field=models.IntegerField(default=0, verbose_name='Parité'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='remarques',
            field=models.TextField(blank=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='statut_dossier',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('termine', 'Terminé')], default='brouillon', max_length=20, verbose_name='Statut du dossier'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='taux_hemoglobine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Taux d'hémoglobine"),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='poids_naissance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids (g)'),
        ),
    ]
