# Generated by Django 6.0.5 on 2026-05-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_naissance_notes_naissance_age_mere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_attente', 'En attente'), ('en_consultation', 'En consultation'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('absent', 'Absent')], default='planifie', max_length=20),
        ),
    ]
