# Generated by Django 6.0.5 on 2026-05-14 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0005_add_rdv_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='antecedents_maladie',
            field=models.TextField(blank=True, verbose_name='Antécédents de la maladie actuelle'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='code_rdv',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Code RDV'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_suivi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suivi'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='docteur_jr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_docteur_jr', to='medecins.medecin', verbose_name='Docteur Jr. responsable'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='historique_passee',
            field=models.TextField(blank=True, verbose_name='Historique passée'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='maladies',
            field=models.TextField(blank=True, verbose_name='Maladies'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='niveau_urgence',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=20, verbose_name="Niveau d'urgence"),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='principales_plaintes',
            field=models.TextField(blank=True, verbose_name='Principales plaintes'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='rdv_exterieur',
            field=models.BooleanField(default=False, verbose_name='Rendez-vous extérieur'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='salle_consultation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Salle de consultation'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='medecins.medecin'),
        ),
    ]
