# Generated by Django 6.0.5 on 2026-05-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_rdv_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_visite_cpn',
            field=models.CharField(blank=True, choices=[('cpn1', 'CPN 1'), ('cpn2', 'CPN 2'), ('cpn3', 'CPN 3'), ('cpn4', 'CPN 4'), ('autre', 'Autre')], default='', max_length=10, verbose_name='Type de visite CPN'),
        ),
    ]
