# Generated by Django 5.1.6 on 2026-05-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_replace_type_rdv_with_service_fk'),
        ('patients', '0007_add_service_and_type_rdv'),
    ]

    operations = [
    ]
