# Generated by Django 6.0.5 on 2026-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_add_type_visite_cpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='type_visite_cpn',
            field=models.CharField(blank=True, choices=[('cpn1', 'CPN 1'), ('cpn1_at', 'CPN 1 – Autre trimestre'), ('cpn2', 'CPN 2'), ('cpn2_at', 'CPN 2 – Autre trimestre'), ('cpn3', 'CPN 3'), ('cpn3_at', 'CPN 3 – Autre trimestre'), ('cpn4', 'CPN 4'), ('cpn4_at', 'CPN 4 – Autre trimestre'), ('autre', 'Autre')], default='', max_length=10, verbose_name='Type de visite CPN'),
        ),
    ]
