# Generated by Django 5.1.6 on 2026-05-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_typevisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='cur_mode_entree',
            field=models.CharField(blank=True, choices=[('venu_lui_meme', 'Patient venu de lui-même'), ('reference_centre', "Référence d'un centre de santé"), ('refere_tradipraticien', 'Référé par un tradipraticien'), ('autre', 'Autre')], default='', max_length=30, verbose_name="Mode d'entrée"),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='cur_mode_entree_autre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Mode d'entrée (préciser)"),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='cur_type_visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_curatifs', to='patients.typevisite', verbose_name='Type de visite'),
        ),
    ]
