# Generated by Django 5.1.6 on 2026-05-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_add_cpn_fields_to_rendezvous'),
        ('services', '0008_add_quantite_stock_to_articleservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='services.articleservice', verbose_name='Type de consultation'),
        ),
    ]
