# Generated by Django 5.1.6 on 2026-05-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_add_type_consultation_to_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreAccouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registre_accouchement', to='patients.rendezvous')),
            ],
            options={
                'verbose_name': 'Registre Accouchement',
            },
        ),
        migrations.CreateModel(
            name='RegistreCPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registre_cpn', to='patients.rendezvous')),
            ],
            options={
                'verbose_name': 'Registre CPN',
            },
        ),
        migrations.CreateModel(
            name='RegistreCuratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registre_curatif', to='patients.rendezvous')),
            ],
            options={
                'verbose_name': 'Registre Curatif',
            },
        ),
        migrations.CreateModel(
            name='RegistrePostnatale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registre_postnatale', to='patients.rendezvous')),
            ],
            options={
                'verbose_name': 'Registre Postnatale',
            },
        ),
    ]
