# Generated by Django 6.0.5 on 2026-05-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_add_cpn5plus_choice'),
        ('patients', '0015_add_registres_cpn_accouchement_postnatale_curatif'),
    ]

    operations = [
    ]
