# Generated by Django 6.0.6 on 2026-07-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_rendezvous_departement_service_step2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_rdv',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('controle', 'Contrôle'), ('urgence', 'Urgence'), ('examen', 'Examen'), ('vaccination', 'Vaccination')], default='consultation', max_length=20),
        ),
    ]
