# Generated by Django 6.0.6 on 2026-07-09 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0011_remove_medecin_service_remove_service_departement_and_more'),
        ('patients', '0021_rendezvous_type_rdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='departement',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='medecins.departement', verbose_name='Département'),
        ),
    ]
