# Generated by Django 6.0.6 on 2026-07-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gynecologie', '0001_initial'),
        ('patients', '0022_alter_rendezvous_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='cpn_type_visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_cpn', to='gynecologie.typevisite', verbose_name='Type de visite CPN'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='cur_type_visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_curatifs', to='gynecologie.typevisite', verbose_name='Type de visite curative'),
        ),
        migrations.DeleteModel(
            name='TypeVisite',
        ),
    ]
