# Generated by Django 5.1.6 on 2026-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_alter_rendezvous_cpn_type_visite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='duree_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
