# Generated by Django 5.1.6 on 2026-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_duree_minutes_default_zero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='actif',
        ),
    ]
