# Generated by Django 6.0.6 on 2026-07-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_remove_patient_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologie',
            name='categorie',
            field=models.CharField(choices=[('generale', 'Générale'), ('grossesse', 'Pathologie sur grossesse'), ('infectieuse', 'Maladie infectieuse'), ('autre_gyneco', 'Autre maladie gynécologique')], default='generale', max_length=20, verbose_name='Catégorie'),
        ),
    ]
