# Generated by Django 6.0.6 on 2026-07-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_pathologie_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ancien_identifiant',
            field=models.CharField(blank=True, help_text="Identifiant du patient dans un système externe (conservé lors d'un import, non affiché).", max_length=50),
        ),
    ]
