# Generated by Django 5.1.6 on 2026-07-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0017_merge_20260724_1343'),
        ('patients', '0027_patient_ancien_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologie',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathologies', to='medecins.departement', verbose_name='Département'),
        ),
    ]
