# Generated by Django 5.1.6 on 2026-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_pathologie_departement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologie',
            name='categorie',
            field=models.CharField(choices=[('generale', 'Générale'), ('grossesse', 'Pathologie sur grossesse'), ('infectieuse', 'Maladie infectieuse'), ('non_infectieuse', 'Autre maladie non infectieuse'), ('ist', 'IST / MST'), ('autre_gyneco', 'Autre maladie gynécologique')], default='generale', max_length=20, verbose_name='Catégorie'),
        ),
    ]
