# Generated by Django 6.0.6 on 2026-07-27 10:33

import django.db.models.deletion
from django.db import migrations, models


def vider_ancienne_fk(apps, schema_editor):
    """Neutralise cur_type_visite avant de changer la table visée.

    Le champ pointait vers gynecologie.TypeVisite (les CPN) : les identifiants
    présents désignent des lignes d'une autre table et deviendraient des
    références invalides. Aucune valeur n'est exploitable de toute façon — le
    formulaire postait du texte et la conversion en clé étrangère échouait
    systématiquement, si bien qu'aucun rendez-vous réel n'était renseigné.
    """
    RendezVous = apps.get_model('patients', 'RendezVous')
    RendezVous.objects.exclude(cur_type_visite=None).update(cur_type_visite=None)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_pathologie_epidemiologie_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVisiteCurative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de visite curative',
                'verbose_name_plural': 'Types de visite curative',
                'ordering': ['nom'],
            },
        ),
        # Doit précéder l'AlterField : sinon les anciens identifiants deviennent
        # des clés étrangères invalides et SQLite rejette la migration.
        migrations.RunPython(vider_ancienne_fk, noop),
        migrations.AlterField(
            model_name='rendezvous',
            name='cur_type_visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_curatifs', to='patients.typevisitecurative', verbose_name='Type de visite curative'),
        ),
    ]
