# Generated by Django 5.1.6 on 2026-08-03 22:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
        ('patients', '0035_seed_types_visite_curative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_creation'], 'verbose_name': 'Patient'},
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
