# Generated by Django 5.1.6 on 2026-08-03 22:50

from django.db import migrations


def rattacher_a_wale(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    Centre = apps.get_model('centres', 'Centre')
    wale = Centre.objects.filter(code='WALE').first()
    if wale is not None:
        Patient.objects.filter(centre__isnull=True).update(centre=wale)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_alter_patient_options_alter_patient_managers_and_more'),
        ('centres', '0002_creer_centres_initiaux'),
    ]

    operations = [
        migrations.RunPython(rattacher_a_wale, noop),
    ]
