# Generated by Django 6.0.6 on 2026-08-23 22:33

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0003_rattacher_soins_et_hospitalisations'),
        ('patients', '0037_patient_centre_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'base_manager_name': 'all_objects', 'ordering': ['date_heure'], 'verbose_name': 'Rendez-vous'},
        ),
        migrations.AlterModelManagers(
            name='rendezvous',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='centre',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='centres.centre'),
        ),
    ]
