# Generated by Django 5.2.16 on 2026-09-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_alter_rendezvous_options_alter_rendezvous_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='demarre_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur connecté au moment du passage « En consultation » — peut différer du médecin assigné si un autre a pris le relais.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_demarres', to=settings.AUTH_USER_MODEL, verbose_name='Consultation démarrée par'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='termine_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_termines', to=settings.AUTH_USER_MODEL, verbose_name='Consultation terminée par'),
        ),
    ]
