# Generated by Django 5.1.6 on 2026-10-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_rendezvous_demarre_par_rendezvous_termine_par'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'base_manager_name': 'all_objects', 'ordering': ['date_heure'], 'permissions': [('confirmer_rendezvous', 'Rendez-vous : peut confirmer (Brouillon → Confirmé)'), ('mettre_en_attente_rendezvous', 'Rendez-vous : peut mettre en attente (évaluation, médecin)'), ('consulter_rendezvous', 'Rendez-vous : peut mener la consultation (En attente → Terminé)'), ('annuler_rendezvous', 'Rendez-vous : peut annuler')], 'verbose_name': 'Rendez-vous'},
        ),
    ]
