# Generated by Django 6.0.7 on 2026-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0041_type_visite_cpn_depuis_registre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(db_index=True),
        ),
    ]
