# Generated by Django 6.0.7 on 2026-10-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_alter_patient_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
