# Generated by Django 5.2.15 on 2026-07-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('couleur', models.CharField(default='blue', max_length=20, verbose_name='Couleur (calendrier)')),
                ('deductible', models.BooleanField(default=True, help_text='Décocher pour les congés qui ne consomment pas le quota annuel (ex. congé sans solde).', verbose_name='Déductible du solde annuel')),
                ('duree_forfaitaire', models.PositiveSmallIntegerField(blank=True, help_text='Nombre de jours fixé par le Code du travail pour ce type (ex. mariage, décès). Laisser vide si la durée est libre (congé annuel, maladie...).', null=True, verbose_name='Durée forfaitaire (jours)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
                'db_table': 'conges_typeconge',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
