# Generated by Django 5.2.16 on 2026-09-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_seed_types_conge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeconge',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Type de demande', 'verbose_name_plural': 'Types de demande'},
        ),
        migrations.AddField(
            model_name='typeconge',
            name='nature',
            field=models.CharField(choices=[('conge', 'Congé'), ('permission', 'Permission'), ('absence', 'Absence')], default='conge', help_text="Détermine le libellé affiché sur le bon et l'attestation (Congé, Permission ou Absence).", max_length=12, verbose_name='Nature'),
        ),
    ]
