# Generated by Django 5.2.16 on 2026-09-17 10:17

from django.db import migrations

PERMISSION_CODES = [
    'exceptionnel',
    'mariage_employe', 'mariage_enfant',
    'deces_conjoint', 'deces_enfant', 'deces_parent', 'deces_frere_soeur',
    'naissance_enfant',
]


def assigner_nature(apps, schema_editor):
    TypeConge = apps.get_model('conges', 'TypeConge')
    TypeConge.objects.filter(code__in=PERMISSION_CODES).update(nature='permission')


def revenir_conge(apps, schema_editor):
    TypeConge = apps.get_model('conges', 'TypeConge')
    TypeConge.objects.filter(code__in=PERMISSION_CODES).update(nature='conge')


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_alter_typeconge_options_typeconge_nature'),
    ]

    operations = [
        migrations.RunPython(assigner_nature, revenir_conge),
    ]
