# Generated by Django 5.2.16 on 2026-09-17 11:32

from django.db import migrations

NOUVEAUX_TYPES = [
    # code, nom, duree_forfaitaire, ordre
    ('deces_pere_mere',     'Décès père/mère',              5, 9),
    ('bapteme_enfant',      "Baptême d'un enfant",          1, 13),
    ('premiere_communion',  'Première communion',           1, 14),
    ('demenagement',        'Déménagement',                 1, 15),
]


def corriger_durees(apps, schema_editor):
    TypeConge = apps.get_model('conges', 'TypeConge')

    TypeConge.objects.filter(code='mariage_employe').update(duree_forfaitaire=4)
    TypeConge.objects.filter(code='naissance_enfant').update(duree_forfaitaire=2)
    TypeConge.objects.filter(code='deces_conjoint').update(duree_forfaitaire=5)

    # Cet ancien type mélangeait décès de parent (5j) et de beau-parent (2j) sous
    # une seule durée (3j) qui ne correspondait à aucun des deux cas légaux.
    # Aucune demande existante ne l'utilise (vérifié avant migration) : on peut
    # le repurposer sans risque en "Décès beau-parent" et créer un type dédié
    # pour le décès d'un père/mère.
    TypeConge.objects.filter(code='deces_parent').update(
        code='deces_beau_parent', nom='Décès beau-père / belle-mère', duree_forfaitaire=2,
    )

    for code, nom, duree, ordre in NOUVEAUX_TYPES:
        TypeConge.objects.update_or_create(
            code=code,
            defaults={
                'nom': nom, 'nature': 'permission', 'deductible': True,
                'duree_forfaitaire': duree, 'actif': True, 'ordre': ordre,
            },
        )


def revenir(apps, schema_editor):
    TypeConge = apps.get_model('conges', 'TypeConge')

    TypeConge.objects.filter(code='mariage_employe').update(duree_forfaitaire=5)
    TypeConge.objects.filter(code='naissance_enfant').update(duree_forfaitaire=3)
    TypeConge.objects.filter(code='deces_conjoint').update(duree_forfaitaire=None)
    TypeConge.objects.filter(code='deces_beau_parent').update(
        code='deces_parent', nom='Décès parent/beau-parent', duree_forfaitaire=3,
    )
    TypeConge.objects.filter(
        code__in=[c for c, *_ in NOUVEAUX_TYPES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_backfill_nature'),
    ]

    operations = [
        migrations.RunPython(corriger_durees, revenir),
    ]
