# Generated by Django 5.2.16 on 2026-09-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0005_corriger_durees_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalierAnciennete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annees_min', models.PositiveSmallIntegerField(unique=True, verbose_name='Ancienneté minimale (années)')),
                ('jours_bonus', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Jours bonus')),
            ],
            options={
                'verbose_name': "Palier d'ancienneté",
                'verbose_name_plural': "Paliers d'ancienneté",
                'ordering': ['annees_min'],
            },
        ),
        migrations.CreateModel(
            name='ReglesConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_par_mois', models.DecimalField(decimal_places=2, default=2.2, help_text='Base légale ivoirienne : 2,2 jours ouvrés par mois (soit 26,4 jours/an).', max_digits=4, verbose_name='Jours acquis par mois travaillé')),
            ],
            options={
                'verbose_name': 'Règles de calcul du quota',
            },
        ),
    ]
