# Generated by Django 5.2.16 on 2026-09-22 12:12

from django.db import migrations

PALIERS = [
    (5, 1), (10, 2), (15, 3), (20, 4), (25, 5),
]


def seed(apps, schema_editor):
    PalierAnciennete = apps.get_model('conges', 'PalierAnciennete')
    for annees_min, jours_bonus in PALIERS:
        PalierAnciennete.objects.get_or_create(
            annees_min=annees_min, defaults={'jours_bonus': jours_bonus},
        )


def unseed(apps, schema_editor):
    PalierAnciennete = apps.get_model('conges', 'PalierAnciennete')
    PalierAnciennete.objects.filter(
        annees_min__in=[a for a, _ in PALIERS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0006_palieranciennete_reglesconge'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
